table Calendar
	lineageTag: 7b82c505-c4c2-4f47-afe7-ec2250a1fcb2
	dataCategory: Time

	measure 'Date Range' = ```
			
			VAR Min_Date= MIN('Calendar'[Date])
			VAR Start_Range =
			CALCULATE ( 
			FORMAT (
			MIN ( 'Calendar'[Date] ),
			"dd-mmm-yyyy"
			),
			ALLSELECTED ( 'Calendar' )
			)
			VAR End_Range =
			CALCULATE (
			FORMAT (
			MAX ( 'Calendar'[Date] ),
			"dd-mmm-yyyy"
			),
			ALLSELECTED ( 'Calendar' )
			)
			RETURN
			IF ( ISBLANK(Min_Date) ||
			DATEDIFF (
			Start_Range,
			End_Range,
			DAY
			) = 0 ,
			Start_Range & " ",
			Start_Range & " - " & End_Range
			)
			```
		lineageTag: 22b5a4ae-f648-4b47-b495-e511a0621d90

	measure 'Timeline Visualization' = ```
			
			// This is the measure for the Value field of the timeline matrix. It takes the total duration (first start -> last end) in scope and divides it by the number of columns
			// in the matrix. That is the duration that each cell in the matrix represents. It then determies whether each cell should be painted (1 or 0) depending on whether the event's duration falls within the timeframe that the cell represents.
			VAR RangeStart =
			    CALCULATE (
			         FIRSTNONBLANK (
			            Operation[Start Date/Time],
			            TRUE ()
			        ),
			        ALLSELECTED ( 'Operation' )
			    )
			VAR RangeEnd =
			      CALCULATE (
			        MAX ( Operation[End Date/Time] ),
			        ALLSELECTED ( 'Operation' )
			    )
			VAR _numberOfColumnsInMatrix =
			    CALCULATE (
			        COUNTROWS ( 'Timeline Visual Columns' ),
			        REMOVEFILTERS ()
			    ) // How many columns will the matrix visual have? 
			VAR TimeSliceSeconds =
			    DIVIDE (
			        DATEDIFF (
			            RangeStart,
			            RangeEnd,
			            SECOND
			        ),
			        _numberOfColumnsInMatrix
			    )
			VAR CurrentSlice =
			    MAX ( 'Timeline Visual Columns'[Time Slice] )
			VAR CurrentColumnMin = RangeStart + ( CurrentSlice - 1 ) * TimeSliceSeconds / ( 60 * 60 * 24 )
			VAR CurrentColumnMax = RangeStart + CurrentSlice * TimeSliceSeconds / ( 60 * 60 * 24 )
			RETURN
			    IF (
			        AND (
			            MIN ( 'Operation'[Start Date/Time] ) <= CurrentColumnMax,
			            MIN (  'Operation'[End Date/Time] ) >= CurrentColumnMin
			        ),
			        1,
			        0
			    )
			```
		formatString: 0
		lineageTag: d4332b6d-c6c6-4f21-9024-02bb1e01863c

	measure 'Gantt value(new)' =
			
			VAR MinCalendar = MIN('Calendar'[Date])
			VAR MaxCalendar = MAX('Calendar'[Date])+1
			RETURN
			IF( (
			MIN(Operation[Start Date/Time]) >= MinCalendar && MAX(Operation[Start Date/Time]) < MaxCalendar),[Timeline Visualization],BLANK())
		formatString: 0
		lineageTag: e5d228c4-ad42-4024-b6d0-95fe119906b7

	measure 'Date New Customer' =
			
			CALCULATE (
			    MIN ( Operation[Start Date] ),
			    ALLEXCEPT (
			        Operation,
			        Operation[Executing User],
			        User
			    )
			)
		formatString: General Date
		lineageTag: 1b24d9c8-c5ed-4e71-9e80-ef019ac511ca

	column Date
		dataType: dateTime
		isKey
		formatString: dd-mmm-yyyy
		lineageTag: 474ae045-c17c-42c4-ba02-ea351f783a7f
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Date]

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Date (no year)'
		dataType: dateTime
		formatString: dd mmm
		lineageTag: ef79d332-b628-469b-bffa-b628fc8224d0
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Date (no year)]

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Day of Month'
		dataType: int64
		formatString: 0
		lineageTag: fbb04464-0b66-4fd3-bcd9-e827157c1d94
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Day of Month]

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 159a7988-2d0f-4493-a0c2-7609ef13c44c
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Year]

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 4f2c347a-bb37-4f7a-ba18-9cc877ca58b4
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Quarter]

		annotation SummarizationSetBy = Automatic

	column 'Week number'
		dataType: int64
		formatString: 0
		lineageTag: f8b87ebb-c8a3-461a-96b6-debe149ea737
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Week number]

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: string
		lineageTag: b94b150b-06b2-47bf-bf53-7cbe155080de
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Year Month]

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: c5e38b38-72c1-4fcd-9bdb-4db7f8bf5fed
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Month Number]

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: c16a6a1c-3ec9-4be8-8f6b-2948de8175f7
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Month Name]

		annotation SummarizationSetBy = Automatic

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: 94f43165-e3a8-465a-90e5-cebcd4121d10
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Day of Year]

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: 3baa4f07-9b24-4d07-a25b-ba5b37462c01
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Day of Week]

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 48c13969-f68b-4858-9261-35992283dd8d
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Day Name]

		annotation SummarizationSetBy = Automatic

	partition Calendar-b535fc8f-9bfc-4148-8351-a8816d252b96 = calculated
		mode: import
		source =
				
				VAR _firstDate =
				    MIN ( 'Operation'[Start Date] )
				VAR _lastDate =
				    MAX ( 'Operation'[Start Date] )
				RETURN
				    ADDCOLUMNS (
				        CALENDAR (
				            _firstDate,
				            _lastDate
				        ),
				        "Date (no year)", [Date],
				           "Day of Month",DAY([Date]),
				    "Year", YEAR([Date]),
				    "Quarter", CONCATENATE("Q", QUARTER([Date])),
				    "Week number", WEEKNUM([Date], 1),
				    "Year Month",YEAR([Date]) & "-" & MONTH([Date]),
				    "Month Number",MONTH([Date]),
				    "Month Name", FORMAT([Date],"MMMM"),
				    "Day of Year",DATEDIFF(DATE(YEAR([Date]),1,1),[Date],DAY)+1,
				    "Day of Week",WEEKDAY([Date],1),
				    "Day Name", FORMAT([Date],"DDDD"))

	annotation PBI_Id = a32c670634a44885b109a0f30041dfc5

