table 'Query Duration Segment'
	lineageTag: 8a57a8e1-9245-4166-8216-2dbaf3f7b255

	column Segment
		dataType: string
		lineageTag: 329a2c2e-4a05-44d7-b7ff-c71b3bcf686c
		summarizeBy: none
		sourceColumn: Segment
		sortByColumn: 'Query Duration Segment Key'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Min
		dataType: int64
		formatString: 0
		lineageTag: fa878882-70d1-48b5-a9f3-02409890a3c3
		summarizeBy: none
		sourceColumn: Min

		annotation SummarizationSetBy = Automatic

	column Max
		dataType: int64
		formatString: 0
		lineageTag: 59b64642-4bf7-49dc-9b7a-5fcbf789d313
		summarizeBy: none
		sourceColumn: Max

		annotation SummarizationSetBy = Automatic

	column 'Query Duration Segment Key'
		dataType: string
		isHidden
		lineageTag: 202fcddb-139d-4967-93fd-da7845d4743b
		summarizeBy: none
		sourceColumn: Query Duration Segment Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Query Duration Segment-8ed21b8c-7cff-431a-9ada-a994d7b31e72' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("PY89DoAwCEavYtiMHaj4dwFPUTsZRyfj/aUf4EIK3+OFlkJMiaSV42WWU/h+tMlUU7F55lZLC1Knzf302o8ALBMjkKVOAhF3uMQtpgEwhcMlZmkKxHPsh8AMuALA8u+HwO/AFUDW3wHJPuQxvnopou+Nav0A", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Min = _t, Max = _t, Legend = _t, #"Query Duration Segment Key" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Min", Int64.Type}, {"Max", Int64.Type}, {"Legend", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Legend", "Segment"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

