table Scenario
	lineageTag: 3c725c55-0d60-4e92-b834-c3a24545ef07

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 39a67267-e3ad-438a-8fdc-aec003c70670
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Scenario
		dataType: string
		lineageTag: bb997841-b056-4c61-8d97-92879eb58fc4
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 1b9b1c4c-7007-45d8-b8bf-ef16ae14a480
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition Scenario-f1538f01-4f99-48f0-8b30-64d06f1697fa = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Vc09DsIwDIbhq0SeO6S/J4ADgMQUdahSI6qWuLJbELfHMSzdXun5ZIcAHgq4pTnRO2mV3kNfBCi1r3hnlIeL9FwX3HDMblppXXbkz8Eqs0brNEmkF/KBa+M2vxMlQZGJkpNt4N+gsUGtdWYmdowr/ak16vJpHMaF4uwoxp3ZtIO+/wI=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Scenario = _t, Sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Scenario", type text}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

