table 'Suboperation - Query'
	lineageTag: b30684f7-5eca-4be9-9562-ec24dea79b36

	column ApplicationName
		dataType: string
		lineageTag: 27b49925-8de2-4b44-9da1-c6dea58aa8e1
		summarizeBy: none
		sourceColumn: ApplicationName

		annotation SummarizationSetBy = Automatic

	column CpuTimeMs
		dataType: int64
		formatString: 0
		lineageTag: e3cca5b2-02c4-4d1e-affd-024c4ae4d63e
		summarizeBy: sum
		sourceColumn: CpuTimeMs

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: c4a44b95-2722-49b2-97c5-49401f2d44db
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column Dataset
		dataType: string
		lineageTag: d13e448d-510c-401f-ab72-47a15850a1a4
		summarizeBy: none
		sourceColumn: Dataset

		annotation SummarizationSetBy = Automatic

	column ArtifactKind
		dataType: string
		lineageTag: acba530f-c53c-4804-875f-55593df85794
		summarizeBy: none
		sourceColumn: ArtifactKind

		annotation SummarizationSetBy = Automatic

	column DatasetMode
		dataType: string
		lineageTag: b4f9f850-1772-44cb-89eb-f12a620525c8
		summarizeBy: none
		sourceColumn: DatasetMode

		annotation SummarizationSetBy = Automatic

	column 'Duration (ms)'
		dataType: int64
		formatString: 0
		lineageTag: b34cce8f-6ef6-4eae-9da8-2117a56337e7
		summarizeBy: sum
		sourceColumn: Duration (ms)

		annotation SummarizationSetBy = Automatic

	column EventText
		dataType: string
		lineageTag: e9c6eaab-c234-40e7-965d-8591a5e4f7a5
		summarizeBy: none
		sourceColumn: EventText

		annotation SummarizationSetBy = Automatic

	column ExecutingUser
		dataType: string
		lineageTag: 04ccddf2-6016-4758-a3a9-cb533e8b5d45
		summarizeBy: none
		sourceColumn: ExecutingUser

		annotation SummarizationSetBy = Automatic

	column 'Operation Detail'
		dataType: string
		lineageTag: 20703c7d-81b6-43f6-9b88-176012ae1cd6
		summarizeBy: none
		sourceColumn: Operation Detail

		annotation SummarizationSetBy = Automatic

	column Operation
		dataType: string
		lineageTag: 0ce4b603-d557-465a-88c0-74278227b2df
		summarizeBy: none
		sourceColumn: Operation

		annotation SummarizationSetBy = Automatic

	column PremiumCapacityId
		dataType: string
		lineageTag: dd654e91-a651-4d35-ae38-00ded9b1adde
		summarizeBy: none
		sourceColumn: PremiumCapacityId

		annotation SummarizationSetBy = Automatic

	column SourceSystem
		dataType: string
		lineageTag: 24f63433-455c-413b-9277-4446c2600044
		summarizeBy: none
		sourceColumn: SourceSystem

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: ea2b68a7-f1ed-4be9-a674-1cf7d50e5b71
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column StatusCode
		dataType: string
		lineageTag: 86fc5826-8108-469d-b5c0-8933c079b7f6
		summarizeBy: none
		sourceColumn: StatusCode

		annotation SummarizationSetBy = Automatic

	column TenantId
		dataType: string
		lineageTag: 61ac1573-1cb1-48d5-9cf5-73bb61ca5b75
		summarizeBy: none
		sourceColumn: TenantId

		annotation SummarizationSetBy = Automatic

	column TextDataHash
		dataType: string
		lineageTag: 31afae6f-9a9d-45bf-aaf0-fbd04e2bd82b
		summarizeBy: none
		sourceColumn: TextDataHash

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 343b9feb-acdc-477b-81f2-59ffbb7bf179
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column User
		dataType: string
		lineageTag: bfdedfb9-3786-41b3-a778-5bd21594116f
		summarizeBy: none
		sourceColumn: User

		annotation SummarizationSetBy = Automatic

	column WorkspaceId
		dataType: string
		lineageTag: 219dcca6-7868-4ae7-a694-29520254e533
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: a2145eb8-1dc5-4238-8746-fca88d5596a8
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column XmlaRequestId
		dataType: string
		lineageTag: c046699d-1538-44a6-a864-9feb8185ca07
		summarizeBy: none
		sourceColumn: XmlaRequestId

		annotation SummarizationSetBy = Automatic

	column XmlaSessionId
		dataType: string
		lineageTag: 5e3a5c76-272f-4f3d-af9f-495831741997
		summarizeBy: none
		sourceColumn: XmlaSessionId

		annotation SummarizationSetBy = Automatic

	column XmlaObjectPath
		dataType: string
		lineageTag: f20e2ef8-5dee-496b-84b4-5f1c18364669
		summarizeBy: none
		sourceColumn: XmlaObjectPath

		annotation SummarizationSetBy = Automatic

	column ResourceId
		dataType: string
		lineageTag: 87a0fea4-a8fa-4c8f-9d04-c00cefbc2dfd
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column SubscriptionId
		dataType: string
		lineageTag: 3069584a-90bb-4978-8d03-c44bbb7d1379
		summarizeBy: none
		sourceColumn: SubscriptionId

		annotation SummarizationSetBy = Automatic

	column 'Start Date/Time'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss AM/PM
		lineageTag: 0f4ad009-1f53-46bb-b990-205b61375e47
		summarizeBy: none
		sourceColumn: Start Date/Time

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Start Date'
		dataType: dateTime
		formatString: dd-mmm-yyyy
		lineageTag: 949929f6-384b-4de3-81df-d5378eb8c903
		summarizeBy: none
		sourceColumn: Start Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Start Time (s)'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 4ff9c81c-9d42-48f1-ab6b-6f9e95669fd0
		summarizeBy: none
		sourceColumn: Start Time (s)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column EndTime
		dataType: dateTime
		formatString: General Date
		lineageTag: b5e4cba1-ef9d-49b7-b25f-bc4c6033d5ee
		summarizeBy: none
		sourceColumn: EndTime

		annotation SummarizationSetBy = Automatic

	partition 'Suboperation - Query-5659c75a-1b51-4285-9120-1b9f9f37b382' = m
		mode: import
		source = ```
				let
				    StartValue = (#"Days Ago To Start") - 1,
				    Source = List.Generate(() => StartValue, each _ > #"Days Ago To Finish"-1, each _ - 1),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Added Custom3" = Table.AddColumn(#"Converted to Table", "Hours", each List.Generate(() => 24-(#"Pagination Hours"), each _> -1, each _ -#"Pagination Hours")),
				    #"Expanded Custom" = Table.ExpandListColumn(#"Added Custom3", "Hours"),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Custom",{{"Column1", "Ago"}}),
				    #"Invoked Custom Function" = Table.AddColumn(#"Renamed Columns", "GetLogAnalytics_AS", each fnGetQuerySuboperations([Ago], [Ago],[Hours],#"Pagination Hours", #"Log Analytics Table",  #"UTC Offset Hours")),
				    #"Expanded GetLogAnalytics_AS1" = Table.ExpandTableColumn(#"Invoked Custom Function", "GetLogAnalytics_AS", {"ApplicationName", "CpuTimeMs", "DatasetId", "Dataset", "ArtifactKind", "DatasetMode", "Duration (ms)", "EventText", "ExecutingUser", "OperationDetailName", "OperationName", "PremiumCapacityId", "SourceSystem", "Status", "StatusCode", "TenantId", "TextDataHash", "Type", "User", "PowerBIWorkspaceId", "PowerBIWorkspaceName", "XmlaRequestId", "XmlaSessionId", "XmlaObjectPath", "ResourceId", "SubscriptionId", "StartTime", "TimeGenerated"}, {"ApplicationName", "CpuTimeMs", "DatasetId", "Dataset", "ArtifactKind", "DatasetMode", "Duration (ms)", "EventText", "ExecutingUser", "OperationDetailName", "OperationName", "PremiumCapacityId", "SourceSystem", "Status", "StatusCode", "TenantId", "TextDataHash", "Type", "User", "WorkspaceId", "WorkspaceName", "XmlaRequestId", "XmlaSessionId", "XmlaObjectPath", "ResourceId", "SubscriptionId", "StartTime", "TimeGenerated"}), 
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded GetLogAnalytics_AS1",{"Ago", "Hours"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    
				    #"Added Start DateTime (UTC offset)" = Table.AddColumn(#"Removed Blank Rows", "Start DateTime", each[TimeGenerated] + #duration(0,Number.RoundDown(#"UTC Offset Hours"),Number.RoundDown(60 * Number.Mod(#"UTC Offset Hours", 1)),0),type datetime),
				    //#"Added Start DateTime (UTC offset)" = Table.AddColumn(#"AnalyticsQuery", "Start DateTime", each [TimeGenerated] + #duration(0, #"UTC Offset",0,0)),
				    #"Inserted StartDate" = Table.AddColumn(#"Added Start DateTime (UTC offset)", "Start Date", each DateTime.Date([Start DateTime]), type date),
				    #"Start Time (s)" = Table.AddColumn(#"Inserted StartDate", "Start Time (s)", each DateTime.Time([Start DateTime]), type time),
				    //#"Inserted StartDate" = Table.AddColumn(#"Added Start DateTime (UTC offset)", "Start Date", each Text.BeforeDelimiter(Text.From([Start DateTime], "en-us"), " ") as text),
				    //#"Start Time (s)" = Table.AddColumn(#"Inserted StartDate", "Start Time (s)", each Text.BetweenDelimiters(Text.From([Start DateTime], "en-US"), " ", " ", 0, 1), type time),    
				    //#"Renamed Columns" = Table.RenameColumns(#"Start Time (s)",{{"DurationMs", "Duration (ms)"}}),
				    #"Added End Date/Time" = Table.AddColumn(#"Start Time (s)", "EndTime", each [Start DateTime] + #duration(0, 0, 0, [#"Duration (ms)"] / 1000)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added End Date/Time",{{"Start Date", type date}, {"Start DateTime", type datetimezone}, {"EndTime", type datetimezone}}),
				    #"Removed StartTime, TimeGenerated" = Table.RemoveColumns(#"Changed Type",{"TimeGenerated", "StartTime"}),
				
				    
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed StartTime, TimeGenerated",{{"CpuTimeMs", Int64.Type}, {"Duration (ms)", Int64.Type}, {"Start DateTime", type datetimezone}, {"Start Date", type date}, {"Start Time (s)", type time}, {"EndTime", type datetimezone}, {"TextDataHash", type text}}),
				    #"Removed Duplicates1" = Table.Distinct(#"Changed Type1"),
				
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Duplicates1",{{"Start DateTime", "Start Date/Time"}, {"OperationDetailName", "Operation Detail"}, {"OperationName", "Operation"}})
				in
				    #"Renamed Columns1"
				```

	annotation PBI_ResultType = Exception

