{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Operation\",\"Suboperation - Refresh\",\"Suboperation - Query\",\"Report Measures\",\"Time\",\"Days Ago To Start\",\"Days Ago To Finish\",\"Log Analytics Table\",\"fnGetOperationsExceptRefreshes\",\"fnGetRefreshOperations\",\"fnGetQuerySuboperations\",\"fnGetRefreshSuboperations\",\"fnGetRelatedRefreshOperationsForSubOpTable\",\"Log Analytics WorkspaceId\",\"UTC Offset Hours\",\"Pagination Hours\",\"UTCOffsetTable\",\"OperationExceptRefresh_stage\",\"RefreshOperations\",\"RefreshSuboperations\",\"RelatedRefreshOperationsForSubOpTable\",\"Scenario\",\"Query Duration Segment\",\"Object Type\",\"Refresh Duration Segment\",\"StartTime\",\"EndTime\",\"Parent page\",\"Child page\",\"Current page\",\"GetWorkspaceId\",\"Suboperation - Aggregations\",\"fnGetAggSuboperations\",\"Last Refresh\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.442.0 (23.10)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Days Ago To Start",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Number"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "description": "From how many days ago should the report start loading data? (For example: 30,28,21,14,7)",
        "expression": "30 meta [IsParameterQuery=true, List={30, 28, 21, 14, 7}, DefaultValue=30, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "2e31fdcb-319b-49aa-a417-067aa158797b",
        "queryGroup": "Params"
      },
      {
        "name": "Days Ago To Finish",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "description": "Until how many days ago should the report stop loading data? (For example: 0,7,14,21 use 0 for today)",
        "expression": "0 meta [IsParameterQuery=true, List={21, 14, 7, 0}, DefaultValue=0, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "2377307e-2c45-4dd5-aa6f-22857558ac12",
        "queryGroup": "Params"
      },
      {
        "name": "fnGetQuerySuboperations",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let\r",
          "    Source = (#\"Days Ago To Start\" as number, #\"Days Ago To Finish\" as number, #\"Hours\" as number,#\"Pagination Hours\" as number, #\"Log Analytics Table\" as text, #\"UTC Offset Hours\" as number) => let AnalyticsQuery =\r",
          "let Source = Json.Document(Web.Contents(\"https://api.loganalytics.io/v1/workspaces/\" & GetWorkspaceId & \"/query\", \r",
          "[Query=[#\"query\"=\"\r",
          "set notruncation;\r",
          "\r",
          "\r",
          "let startDate = startofday(ago(\" & Number.ToText(#\"Days Ago To Start\") & \"d))- \"& Number.ToText(#\"UTC Offset Hours\" * 60) & \"m ;\r",
          "let startIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Hours\") & \",todatetime(startDate));\r",
          "let endIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Pagination Hours\") & \",todatetime(startIngestionTime));\r",
          "\r",
          "\"& #\"Log Analytics Table\" & \" \r",
          "| where TimeGenerated >= startIngestionTime and TimeGenerated < endIngestionTime\r",
          "| where (OperationName == 'VertiPaqSEQueryEnd' and OperationDetailName == 'VertiPaqScan') // Queries with EventSubclass = 0\r",
          "      or OperationName == 'DirectQueryEnd' // Queries\r",
          "      or OperationName == 'VertiPaqSEQueryCacheMatch' // Cache hits\r",
          "| extend TextDataHash = hash(EventText)\r",
          "| extend DurationMs = coalesce(DurationMs, 0)\r",
          "| distinct ApplicationName, CpuTimeMs, ArtifactId, ArtifactName, ArtifactKind, DatasetMode, DurationMs, EventText, ExecutingUser, OperationDetailName, OperationName, PremiumCapacityId, SourceSystem, Status, StatusCode, TenantId, TextDataHash, TimeGenerated, Type, User, PowerBIWorkspaceId, PowerBIWorkspaceName, XmlaRequestId, XmlaSessionId, XmlaObjectPath, _ResourceId, _SubscriptionId\r",
          "| project ApplicationName, CpuTimeMs, DatasetId = ArtifactId, Dataset = ArtifactName, ArtifactKind, DatasetMode, ['Duration (ms)'] = DurationMs, EventText, ExecutingUser, OperationDetailName, OperationName, PremiumCapacityId, SourceSystem, Status, StatusCode, TenantId, TextDataHash, TimeGenerated, Type, User, PowerBIWorkspaceId, PowerBIWorkspaceName, XmlaRequestId, XmlaSessionId, XmlaObjectPath, ResourceId = _ResourceId, SubscriptionId = _SubscriptionId, StartTime = TimeGenerated\r",
          "\r",
          "\"],Timeout=#duration(0,0,60,0)])),\r",
          "TypeMap = #table(\r",
          "{ \"AnalyticsTypes\", \"Type\" }, \r",
          "{ \r",
          "{ \"string\",   Text.Type },\r",
          "{ \"int\",      Int32.Type },\r",
          "{ \"long\",     Int64.Type },\r",
          "{ \"real\",     Double.Type },\r",
          "{ \"timespan\", Duration.Type },\r",
          "{ \"datetime\", DateTimeZone.Type },\r",
          "{ \"bool\",     Logical.Type },\r",
          "{ \"guid\",     Text.Type },\r",
          "{ \"dynamic\",  Text.Type }\r",
          "}),\r",
          "DataTable = Source[tables]{0},\r",
          "Columns = Table.FromRecords(DataTable[columns]),\r",
          "ColumnsWithType = Table.Join(Columns, {\"type\"}, TypeMap , {\"AnalyticsTypes\"}),\r",
          "Rows = Table.FromRows(DataTable[rows], Columns[name]), \r",
          "Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))\r",
          "in\r",
          "Table\r",
          "\r",
          "in\r",
          "    AnalyticsQuery\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "e92cda24-52ca-48e7-beb3-f13e4813716a",
        "queryGroup": "Kusto queries"
      },
      {
        "name": "Log Analytics Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Which table from Azure Log Analytics should be used? (For example: PowerBIDatasetsWorkspace)",
        "expression": "\"PowerBIDatasetsWorkspace\" meta [IsParameterQuery=true, List={\"PowerBIDatasetsWorkspace\"}, DefaultValue=\"PowerBIDatasetsWorkspace\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "f09d3b22-11a7-47f8-9530-1d18c2531a8f",
        "queryGroup": "Params"
      },
      {
        "name": "Log Analytics WorkspaceId",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "description": "The unique identifier of the Azure Log Analytics workspace containing the activity data.",
        "expression": "\"309df71c-8de4-4982-8902-3891219de160\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9c7f0ca2-e9f8-48cb-a070-b01b133c1425",
        "queryGroup": "Params"
      },
      {
        "name": "UTCOffsetTable",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Table.FromList\r",
          "    (\r",
          "        {\r",
          "            [Column1=\"UTC Offset\", Offset = #\"UTC Offset Hours\"]\r",
          "        },\r",
          "        Record.FieldValues,\r",
          "        {\r",
          "            \"Description\",\r",
          "            \"Offset\"\r",
          "        }\r",
          "    ),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Offset\", type number}})\r",
          "in\r",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "e54f4725-d3b9-4e11-80ee-073f816de5be",
        "queryGroup": "Helper queries"
      },
      {
        "name": "RefreshOperations",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let\r",
          "    StartValue = (#\"Days Ago To Start\") - 1,\r",
          "    Source = List.Generate(() => StartValue, each _ > #\"Days Ago To Finish\"-1, each _ - 1),\r",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Converted to Table\", \"Hours\", each List.Generate(() => 24-(#\"Pagination Hours\"), each _> -1, each _ -#\"Pagination Hours\")),\r",
          "    #\"Expanded Custom\" = Table.ExpandListColumn(#\"Added Custom3\", \"Hours\"),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Custom\",{{\"Column1\", \"Ago\"}}),\r",
          "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Renamed Columns\", \"fnGetEvents\", each fnGetRefreshOperations([Ago], [Ago],[Hours],#\"Pagination Hours\", #\"Log Analytics Table\",  #\"UTC Offset Hours\")),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Invoked Custom Function\",{\"Ago\", \"Hours\"}),\r",
          "    #\"Expanded fnGetEvents\" = Table.ExpandTableColumn(#\"Removed Columns\", \"fnGetEvents\", {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"ArtifactKind\", \"Dataset\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"ReportId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Type\", \"User\", \"PowerBIWorkspaceId\", \"PowerBIWorkspaceName\", \"XmlaRequestId\", \"XmlaSessionId\", \"ResourceId\", \"SubscriptionId\", \"RefreshSubeventKey\", \"StartTime\"}, {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"ArtifactKind\", \"Dataset\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"ReportId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Type\", \"User\", \"WorkspaceId\", \"WorkspaceName\", \"XmlaRequestId\", \"XmlaSessionId\", \"ResourceId\", \"SubscriptionId\", \"RefreshSubeventKey\", \"StartTime\"}),\r",
          "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Expanded fnGetEvents\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null})))\r",
          "    \r",
          "in\r",
          "    #\"Removed Blank Rows\""
        ],
        "kind": "m",
        "lineageTag": "8a6fbd83-e012-483c-81aa-ccd97594b384",
        "queryGroup": "Helper queries"
      },
      {
        "name": "RelatedRefreshOperationsForSubOpTable",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let\r",
          "    StartValue = (#\"Days Ago To Start\") - 1,\r",
          "    Source = List.Generate(() => StartValue, each _ > #\"Days Ago To Finish\"-1, each _ - 1),\r",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Converted to Table\", \"Hours\", each List.Generate(() => 24-(#\"Pagination Hours\"), each _> -1, each _ -#\"Pagination Hours\")),\r",
          "    #\"Expanded Custom\" = Table.ExpandListColumn(#\"Added Custom3\", \"Hours\"),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Custom\",{{\"Column1\", \"Ago\"}}),\r",
          "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Renamed Columns\", \"GetLogAnalytics_AS\", each fnGetRelatedRefreshOperationsForSubOpTable([Ago], [Ago],[Hours],#\"Pagination Hours\", #\"Log Analytics Table\",  #\"UTC Offset Hours\")),\r",
          "    #\"Expanded GetRelatedRefreshOperations\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"GetLogAnalytics_AS\", {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"Dataset\", \"ArtifactKind\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Type\", \"User\", \"PowerBIWorkspaceId\", \"PowerBIWorkspaceName\", \"XmlaRequestId\", \"XmlaObjectPath\", \"XmlaSessionId\", \"ResourceId\", \"SubscriptionId\", \"StartTime\", \"TimeGenerated\"}, {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"Dataset\", \"ArtifactKind\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Type\", \"User\", \"WorkspaceId\", \"WorkspaceName\", \"XmlaRequestId\", \"XmlaObjectPath\", \"XmlaSessionId\", \"ResourceId\", \"SubscriptionId\", \"StartTime\", \"TimeGenerated\"}),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded GetRelatedRefreshOperations\",{\"Ago\", \"Hours\"}),\r",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),\r",
          "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null})))\r",
          "    \r",
          "in\r",
          "    #\"Removed Blank Rows\""
        ],
        "kind": "m",
        "lineageTag": "024d34fa-9547-41d3-bed2-3237cabfbef2",
        "queryGroup": "Helper queries"
      },
      {
        "name": "fnGetRefreshOperations",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let\r",
          "    Source = (#\"Days Ago To Start\" as number, #\"Days Ago To Finish\" as number, #\"Hours\" as number,#\"Pagination Hours\" as number, #\"Log Analytics Table\" as text, #\"UTC Offset Hours\" as number) => let AnalyticsQuery =\r",
          "let Source = Json.Document(Web.Contents(\"https://api.loganalytics.io/v1/workspaces/\" & GetWorkspaceId & \"/query\", \r",
          "[Query=[#\"query\"=\"\r",
          "// Refreshes can contain several CommandEnd and DiscoveryEnd events that share the same rootActivityId. This report's data model typically has these in the Operation table, however\r",
          "// to keep these events grouped together we move such events to the Suboperation table.\r",
          "set notruncation;\r",
          "let workspaceIdList = dynamic(['50EA7149-43DC-4DE3-8E56-4D5DBBC83E8F', 'C839BDCB-81B5-4DC3-9F92-818FE71432A1', '80FA5101-D77B-4AC3-B86A-EEAFE28E64AC']);\r",
          "\r",
          "let startDate = startofday(ago(\" & Number.ToText(#\"Days Ago To Start\") & \"d))- \"& Number.ToText(#\"UTC Offset Hours\" * 60) & \"m ;\r",
          "let startIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Hours\") & \",todatetime(startDate));\r",
          "let endIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Pagination Hours\") & \",todatetime(startIngestionTime));\r",
          "\r",
          "\r",
          "\"& #\"Log Analytics Table\" & \"\r",
          "| where TimeGenerated >= startIngestionTime and TimeGenerated < endIngestionTime\r",
          "| where OperationName  == 'CommandEnd'\r",
          "| where OperationDetailName == 'Batch' \r",
          "| where EventText contains_cs '<Refresh xmlns=' // high-level refresh operation\r",
          "| extend DatasetId = tostring(parse_json(ApplicationContext).DatasetId)\r",
          "| extend Sources = parse_json(ApplicationContext).Sources\r",
          "| mv-expand Sources\r",
          "| extend ReportId = tostring(parse_json(Sources).ReportId)\r",
          "| extend TextDataHash = hash(EventText)\r",
          "| extend DurationMs = coalesce(DurationMs, 0)\r",
          "| extend User = iff(toupper(PowerBIWorkspaceId) in (workspaceIdList), hash_md5(User), User)\r",
          "| extend ExecutingUser = iff(toupper(PowerBIWorkspaceId) in (workspaceIdList), hash_md5(ExecutingUser), ExecutingUser)\r",
          "| distinct  ApplicationName, CpuTimeMs, ArtifactId, ArtifactKind, ArtifactName, DatasetMode, DurationMs, EventText, ExecutingUser, OperationDetailName, OperationName, PremiumCapacityId, ReportId, SourceSystem, Status, StatusCode, TenantId, TextDataHash, TimeGenerated, Type, User, PowerBIWorkspaceId, PowerBIWorkspaceName, XmlaRequestId, XmlaSessionId, _ResourceId, _SubscriptionId\r",
          "| extend RefreshSubeventKey = XmlaRequestId \r",
          "| project-rename DatasetId = ArtifactId, Dataset = ArtifactName, StartTime = TimeGenerated, ResourceId = _ResourceId, SubscriptionId = _SubscriptionId, ['Duration (ms)'] = DurationMs\r",
          "\r",
          "\",#\"x-ms-app\"=\"OmsAnalyticsPBI\",#\"prefer\"=\"ai.response-thinning=true\"],Timeout=#duration(0,0,60,0)])),\r",
          "TypeMap = #table(\r",
          "{ \"AnalyticsTypes\", \"Type\" }, \r",
          "{ \r",
          "{ \"string\",   Text.Type },\r",
          "{ \"int\",      Int32.Type },\r",
          "{ \"long\",     Int64.Type },\r",
          "{ \"real\",     Double.Type },\r",
          "{ \"timespan\", Duration.Type },\r",
          "{ \"datetime\", DateTimeZone.Type },\r",
          "{ \"bool\",     Logical.Type },\r",
          "{ \"guid\",     Text.Type },\r",
          "{ \"dynamic\",  Text.Type }\r",
          "}),\r",
          "DataTable = Source[tables]{0},\r",
          "Columns = Table.FromRecords(DataTable[columns]),\r",
          "ColumnsWithType = Table.Join(Columns, {\"type\"}, TypeMap , {\"AnalyticsTypes\"}),\r",
          "Rows = Table.FromRows(DataTable[rows], Columns[name]), \r",
          "Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))\r",
          "in\r",
          "Table\r",
          "\r",
          "in\r",
          "    AnalyticsQuery\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "0ed96e55-1b98-4ee8-b8a2-6df4b5f2f163",
        "queryGroup": "Kusto queries"
      },
      {
        "name": "fnGetOperationsExceptRefreshes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let\r",
          "    Source = (#\"Days Ago To Start\" as number, #\"Days Ago To Finish\" as number,#\"Hours\" as number,#\"Pagination Hours\" as number, #\"Log Analytics Table\" as text, #\"UTC Offset Hours\" as number) => let AnalyticsQuery =\r",
          "let Source = Json.Document(Web.Contents(\"https://api.loganalytics.io/v1/workspaces/\" & GetWorkspaceId & \"/query\", \r",
          "[Query=[#\"query\"=\"\r",
          "set notruncation;\r",
          "let workspaceIdList = dynamic(['50EA7149-43DC-4DE3-8E56-4D5DBBC83E8F', 'C839BDCB-81B5-4DC3-9F92-818FE71432A1', '80FA5101-D77B-4AC3-B86A-EEAFE28E64AC']);\r",
          "\r",
          "\r",
          "let startDate = startofday(ago(\" & Number.ToText(#\"Days Ago To Start\") & \"d))- \"& Number.ToText(#\"UTC Offset Hours\" * 60) & \"m ;\r",
          "let startIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Hours\") & \",todatetime(startDate));\r",
          "let endIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Pagination Hours\") & \",todatetime(startIngestionTime));\r",
          "\r",
          "\" & #\"Log Analytics Table\" & \" \r",
          "    | where TimeGenerated >= startIngestionTime and TimeGenerated < endIngestionTime\r",
          "    | where OperationName  in ('DiscoverEnd', 'QueryEnd', 'Error', 'Deadlock', 'SessionInitialize')\r",
          "    | where not (OperationName  == 'CommandEnd' and OperationDetailName == 'Batch' and EventText contains_cs '<Refresh xmlns=')  // remove refreshes. We add them in Power Query\r",
          "    | extend Sources = parse_json(ApplicationContext).Sources\r",
          "    | mv-expand Sources\r",
          "    | extend ReportId = tostring(parse_json(Sources).ReportId)\r",
          "    | extend TextDataHash = hash(EventText)\r",
          "    | extend DurationMs = coalesce(DurationMs, 0)\r",
          "    | extend User = iff(toupper(PowerBIWorkspaceId) in (workspaceIdList), hash_md5(User), User)\r",
          "    | extend ExecutingUser = iff(toupper(PowerBIWorkspaceId) in (workspaceIdList), hash_md5(ExecutingUser), ExecutingUser)\r",
          "    | distinct  ApplicationName, CpuTimeMs, ArtifactId, ArtifactName, ArtifactKind, DatasetMode, DurationMs, EventText, ExecutingUser, OperationDetailName, OperationName, PremiumCapacityId, ReportId, SourceSystem, Status, StatusCode, TenantId, TextDataHash, TimeGenerated, Type, User, PowerBIWorkspaceId, PowerBIWorkspaceName, XmlaRequestId, XmlaSessionId, _ResourceId, _SubscriptionId\r",
          "    | extend QuerySubeventKey = case(\r",
          "        OperationName == 'QueryEnd' and isnotempty(XmlaRequestId), XmlaRequestId,  // add rootActivityId as the key if this is a QueryEnd. This joins to the Suboperation table.\r",
          "        dynamic(null)) // if we are not expecting subevents then make this null. In PowerQuery we will add a dummy index value for null values to keep this column unique for the 1:* relationship\r",
          "    | project-rename DatasetId = ArtifactId, Dataset = ArtifactName, StartTime = TimeGenerated, ResourceId = _ResourceId, SubscriptionId = _SubscriptionId,  ['Duration (ms)'] = DurationMs\r",
          "\"],Timeout=#duration(0,0,60,0)])),\r",
          "TypeMap = #table(\r",
          "{ \"AnalyticsTypes\", \"Type\" }, \r",
          "{ \r",
          "{ \"string\",   Text.Type },\r",
          "{ \"int\",      Int32.Type },\r",
          "{ \"long\",     Int64.Type },\r",
          "{ \"real\",     Double.Type },\r",
          "{ \"timespan\", Duration.Type },\r",
          "{ \"datetime\", DateTimeZone.Type },\r",
          "{ \"bool\",     Logical.Type },\r",
          "{ \"guid\",     Text.Type },\r",
          "{ \"dynamic\",  Text.Type }\r",
          "}),\r",
          "DataTable = Source[tables]{0},\r",
          "Columns = Table.FromRecords(DataTable[columns]),\r",
          "ColumnsWithType = Table.Join(Columns, {\"type\"}, TypeMap , {\"AnalyticsTypes\"}),\r",
          "Rows = Table.FromRows(DataTable[rows], Columns[name]), \r",
          "Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))\r",
          "in\r",
          "Table\r",
          "    \r",
          "in\r",
          "    AnalyticsQuery\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "30cb2ffe-308f-46ce-91f2-27f29f333f6c",
        "queryGroup": "Kusto queries"
      },
      {
        "name": "OperationExceptRefresh_stage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let\r",
          "    StartValue = (#\"Days Ago To Start\") - 1,\r",
          "    Source = List.Generate(() => StartValue, each _ > #\"Days Ago To Finish\"-1, each _ - 1),\r",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Converted to Table\", \"Hours\", each List.Generate(() => 24-(#\"Pagination Hours\"), each _> -1, each _ -#\"Pagination Hours\")),\r",
          "    #\"Expanded Custom\" = Table.ExpandListColumn(#\"Added Custom3\", \"Hours\"),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Custom\",{{\"Column1\", \"Ago\"}}),\r",
          "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Renamed Columns\", \"fnGetEvents\", each fnGetOperationsExceptRefreshes([Ago], [Ago],[Hours],#\"Pagination Hours\", #\"Log Analytics Table\",  #\"UTC Offset Hours\")),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Invoked Custom Function\",{\"Ago\", \"Hours\"}),\r",
          "    #\"Expanded fnGetEvents\" = Table.ExpandTableColumn(#\"Removed Columns\", \"fnGetEvents\", {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"Dataset\", \"ArtifactKind\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"ReportId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Type\", \"User\", \"PowerBIWorkspaceId\", \"PowerBIWorkspaceName\", \"XmlaRequestId\", \"XmlaSessionId\", \"ResourceId\", \"SubscriptionId\", \"QuerySubeventKey\", \"StartTime\"}, {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"Dataset\", \"ArtifactKind\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"ReportId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Type\", \"User\", \"WorkspaceId\", \"WorkspaceName\", \"XmlaRequestId\", \"XmlaSessionId\", \"ResourceId\", \"SubscriptionId\", \"QuerySubeventKey\", \"StartTime\"}),\r",
          "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Expanded fnGetEvents\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null})))\r",
          "    \r",
          "in\r",
          "    #\"Removed Blank Rows\""
        ],
        "kind": "m",
        "lineageTag": "a6bd73c4-0b56-40e3-b038-991ed6ddb704",
        "queryGroup": "Helper queries"
      },
      {
        "name": "Object Type",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"bZK7bsMwDEX/xXMGP+Q2GYNkaNEYMYygi+GBTpmGhSwHEp2if18qKPyqNZ4rvi5ZlkEUyouDVbAHhhocBtWqDNZhtEjjMEqE7lrdNWZgStiW2VLdMb4QWrDn68+gp6LnYJmY2lHYk+ACNXjqrnQblGdRMgTX2VHltcCF5BvBB7yj7lEc+n6MaRkmBeNI+Fv+OgA/4q7TPK4T+wmP9Ree+WTBOD1L4oc9kPnsyDGdM2T4EJN6PfFt5mjdTRLQfcibbKbCCWo9qCpcUGc+q2jhz39HVLzwbe6m8lMW7bgD9UcybGqJHi9E+Q0+8kjehpwbO6L8Ht/B0tSoNOovZSEofVyXmEe6aL/dHi9kpueR+ppbzWgNMB4vQVX9Ag==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ObjectTypeId = _t, ObjectTypeDescription = _t]),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ObjectTypeId\", Int64.Type}, {\"ObjectTypeDescription\", type text}})\r",
          "in\r",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "721aa807-db8a-4b66-a00a-c7771e01c4ee",
        "queryGroup": "Helper queries"
      },
      {
        "name": "fnGetRelatedRefreshOperationsForSubOpTable",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let\r",
          "    Source = (#\"Days Ago To Start\" as number, #\"Days Ago To Finish\" as number, #\"Hours\" as number,#\"Pagination Hours\" as number, #\"Log Analytics Table\" as text, #\"UTC Offset Hours\" as number) => let AnalyticsQuery =\r",
          "let Source = Json.Document(Web.Contents(\"https://api.loganalytics.io/v1/workspaces/\" & GetWorkspaceId & \"/query\", \r",
          "[Query=[#\"query\"=\"\r",
          " // Refreshes can contain several CommandEnd and DiscoveryEnd events that share the same rootActivityId. This report's data model typically has these in the Operation table, however\r",
          "    // to keep these events grouped together as related to a refresh we move such events to the Suboperation table.\r",
          "    set notruncation;\r",
          "    let workspaceIdList = dynamic(['50EA7149-43DC-4DE3-8E56-4D5DBBC83E8F', 'C839BDCB-81B5-4DC3-9F92-818FE71432A1', '80FA5101-D77B-4AC3-B86A-EEAFE28E64AC']);\r",
          "    \r",
          "    let startDate = startofday(ago(\" & Number.ToText(#\"Days Ago To Start\") & \"d))- \"& Number.ToText(#\"UTC Offset Hours\" * 60) & \"m ;\r",
          "    let startIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Hours\") & \",todatetime(startDate));\r",
          "    let endIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Pagination Hours\") & \",todatetime(startIngestionTime));\r",
          "\r",
          "    let relatedRefreshEvents = \"& #\"Log Analytics Table\" & \"\r",
          "    | where (TimeGenerated >= startIngestionTime and TimeGenerated < endIngestionTime) \r",
          "    | where ((OperationName in ('DiscoverEnd', 'QueryEnd', 'Error', 'Deadlock', 'SessionInitialize')) or (OperationName  == 'CommandEnd' and not(EventText contains_cs '<Refresh xmlns=' and OperationDetailName == 'Batch'))) and XmlaRequestId  in (\r",
          "    // Subquery that returns rootActivityIds of all refresh operations. We expand the window -- NEED TO TEST IF  +/- 24h IS NECESSARY\r",
          "    (\"& #\"Log Analytics Table\" & \" \r",
          "    | where (TimeGenerated >= startIngestionTime - 24h and TimeGenerated < endIngestionTime + 24h) // create a window in case these events happen outside of the base event's StartTime\r",
          "    | where OperationName  == 'CommandEnd'\r",
          "    | where OperationDetailName == 'Batch'\r",
          "    | where EventText contains_cs '<Refresh xmlns=' \r",
          "    | project XmlaRequestId\r",
          "    )\r",
          "    )\r",
          "    ;\r",
          "    relatedRefreshEvents\r",
          "    | extend TextDataHash = hash(EventText)\r",
          "    | extend DurationMs = coalesce(DurationMs, 0)\r",
          "    | extend User = iff(toupper(PowerBIWorkspaceId) in (workspaceIdList), hash_md5(User), User)\r",
          "    | extend ExecutingUser = iff(toupper(PowerBIWorkspaceId) in (workspaceIdList), hash_md5(ExecutingUser), ExecutingUser)\r",
          "| distinct ApplicationName, CpuTimeMs, ArtifactId, ArtifactName, ArtifactKind, DatasetMode, DurationMs, EventText, ExecutingUser, OperationDetailName, OperationName, PremiumCapacityId, SourceSystem, Status, StatusCode, TenantId, TextDataHash, TimeGenerated, Type, User, PowerBIWorkspaceId, PowerBIWorkspaceName, XmlaRequestId, XmlaObjectPath, XmlaSessionId, _ResourceId, _SubscriptionId\r",
          "| project ApplicationName, CpuTimeMs, DatasetId = ArtifactId, Dataset = ArtifactName, ArtifactKind, DatasetMode, ['Duration (ms)'] = DurationMs, EventText, ExecutingUser, OperationDetailName, OperationName, PremiumCapacityId, SourceSystem, Status, StatusCode, TenantId, TextDataHash, StartTime = TimeGenerated,Microsecond=datetime_part(\"\"microsecond\"\",TimeGenerated), Type, User, PowerBIWorkspaceId, PowerBIWorkspaceName, XmlaRequestId, XmlaObjectPath, XmlaSessionId,  ResourceId = _ResourceId, SubscriptionId = _SubscriptionId \r",
          "    \"],Timeout=#duration(0,0,60,0)])),\r",
          "TypeMap = #table(\r",
          "{ \"AnalyticsTypes\", \"Type\" }, \r",
          "{ \r",
          "{ \"string\",   Text.Type },\r",
          "{ \"int\",      Int32.Type },\r",
          "{ \"long\",     Int64.Type },\r",
          "{ \"real\",     Double.Type },\r",
          "{ \"timespan\", Duration.Type },\r",
          "{ \"datetime\", DateTimeZone.Type },\r",
          "{ \"bool\",     Logical.Type },\r",
          "{ \"guid\",     Text.Type },\r",
          "{ \"dynamic\",  Text.Type }\r",
          "}),\r",
          "DataTable = Source[tables]{0},\r",
          "Columns = Table.FromRecords(DataTable[columns]),\r",
          "ColumnsWithType = Table.Join(Columns, {\"type\"}, TypeMap , {\"AnalyticsTypes\"}),\r",
          "Rows = Table.FromRows(DataTable[rows], Columns[name]), \r",
          "Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))\r",
          "in\r",
          "Table\r",
          "         \r",
          "in\r",
          "    AnalyticsQuery\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "8fa0e5de-e537-4909-8950-4437ce8a68af",
        "queryGroup": "Kusto queries"
      },
      {
        "name": "fnGetRefreshSuboperations",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let\r",
          "    Source = (#\"Days Ago To Start\" as number, #\"Days Ago To Finish\" as number, #\"Hours\" as number,#\"Pagination Hours\" as number,  #\"Log Analytics Table\" as text, #\"UTC Offset Hours\" as number) => let AnalyticsQuery =\r",
          "let Source = Json.Document(Web.Contents(\"https://api.loganalytics.io/v1/workspaces/\" & GetWorkspaceId & \"/query\", \r",
          "[Query=[#\"query\"=\"\r",
          "set notruncation;\r",
          "\r",
          "\r",
          "let startDate = startofday(ago(\" & Number.ToText(#\"Days Ago To Start\") & \"d))- \"& Number.ToText(#\"UTC Offset Hours\" * 60) & \"m ;\r",
          "let startIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Hours\") & \",todatetime(startDate));\r",
          "let endIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Pagination Hours\") & \",todatetime(startIngestionTime));\r",
          "\r",
          "\"& #\"Log Analytics Table\" & \" \r",
          "| where TimeGenerated >= startIngestionTime and TimeGenerated < endIngestionTime\r",
          "| where (OperationName == 'ProgressReportEnd') // Refreshes\r",
          "| extend TextDataHash = hash(EventText)\r",
          "| extend DurationMs = coalesce(DurationMs, 0)\r",
          "| extend Microsecond = datetime_part(\"\"microsecond\"\",TimeGenerated)\r",
          "| distinct ApplicationName, CpuTimeMs, ArtifactId, ArtifactName, ArtifactKind, DatasetMode, DurationMs, EventText, ExecutingUser, OperationDetailName, OperationName, PremiumCapacityId, SourceSystem, Status, StatusCode, TenantId, TextDataHash, TimeGenerated, Microsecond, Type, User, PowerBIWorkspaceId, PowerBIWorkspaceName, XmlaRequestId, XmlaSessionId, XmlaObjectPath, _ResourceId, _SubscriptionId\r",
          "| project ApplicationName, CpuTimeMs, DatasetId = ArtifactId, Dataset = ArtifactName, ArtifactKind, DatasetMode, ['Duration (ms)'] = DurationMs, EventText, ExecutingUser, OperationDetailName, OperationName, PremiumCapacityId, SourceSystem, Status, StatusCode, TenantId, TextDataHash, TimeGenerated, Microsecond, Type, User, PowerBIWorkspaceId, PowerBIWorkspaceName, XmlaRequestId, XmlaSessionId, XmlaObjectPath, ResourceId = _ResourceId, SubscriptionId = _SubscriptionId, StartTime = TimeGenerated\r",
          "\r",
          "\"],Timeout=#duration(0,0,60,0)])),\r",
          "TypeMap = #table(\r",
          "{ \"AnalyticsTypes\", \"Type\" }, \r",
          "{ \r",
          "{ \"string\",   Text.Type },\r",
          "{ \"int\",      Int32.Type },\r",
          "{ \"long\",     Int64.Type },\r",
          "{ \"real\",     Double.Type },\r",
          "{ \"timespan\", Duration.Type },\r",
          "{ \"datetime\", DateTimeZone.Type },\r",
          "{ \"bool\",     Logical.Type },\r",
          "{ \"guid\",     Text.Type },\r",
          "{ \"dynamic\",  Text.Type }\r",
          "}),\r",
          "DataTable = Source[tables]{0},\r",
          "Columns = Table.FromRecords(DataTable[columns]),\r",
          "ColumnsWithType = Table.Join(Columns, {\"type\"}, TypeMap , {\"AnalyticsTypes\"}),\r",
          "Rows = Table.FromRows(DataTable[rows], Columns[name]), \r",
          "Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))\r",
          "in\r",
          "Table\r",
          "\r",
          "in\r",
          "    AnalyticsQuery\r",
          "in\r",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "7fa045e7-47a3-433e-8e79-2ef4ed038b71",
        "queryGroup": "Kusto queries"
      },
      {
        "name": "RefreshSuboperations",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let\r",
          "    StartValue = (#\"Days Ago To Start\") - 1,\r",
          "    Source = List.Generate(() => StartValue, each _ > #\"Days Ago To Finish\"-1, each _ - 1),\r",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r",
          "    #\"Added Custom3\" = Table.AddColumn(#\"Converted to Table\", \"Hours\", each List.Generate(() => 24-(#\"Pagination Hours\"), each _> -1, each _ -#\"Pagination Hours\")),\r",
          "    #\"Expanded Custom\" = Table.ExpandListColumn(#\"Added Custom3\", \"Hours\"),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Custom\",{{\"Column1\", \"Ago\"}}),\r",
          "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Renamed Columns\", \"GetLogAnalytics_AS\", each fnGetRefreshSuboperations([Ago], [Ago],[Hours],#\"Pagination Hours\", #\"Log Analytics Table\", #\"UTC Offset Hours\")),\r",
          "    #\"Expanded GetLogAnalytics_AS1\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"GetLogAnalytics_AS\", {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"Dataset\", \"ArtifactKind\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Microsecond\", \"Type\", \"User\", \"PowerBIWorkspaceId\", \"PowerBIWorkspaceName\", \"XmlaRequestId\", \"XmlaSessionId\", \"XmlaObjectPath\", \"ResourceId\", \"SubscriptionId\", \"StartTime\", \"TimeGenerated\"}, {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"Dataset\", \"ArtifactKind\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Microsecond\", \"Type\", \"User\", \"WorkspaceId\", \"WorkspaceName\", \"XmlaRequestId\", \"XmlaSessionId\", \"XmlaObjectPath\", \"ResourceId\", \"SubscriptionId\", \"StartTime\", \"TimeGenerated\"}),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded GetLogAnalytics_AS1\",{\"Ago\",\"Hours\"}),\r",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),\r",
          "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null})))\r",
          "    \r",
          "in\r",
          "    #\"Removed Blank Rows\""
        ],
        "kind": "m",
        "lineageTag": "e71d890f-d78f-4948-a679-3d0e334491b2",
        "queryGroup": "Helper queries"
      },
      {
        "name": "fnGetAggSuboperations",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (#\"Days Ago To Start\" as number, #\"Days Ago To Finish\" as number, #\"Hours\" as number,#\"Pagination Hours\" as number, #\"Log Analytics Table\" as text, #\"UTC Offset Hours\" as number) => let AnalyticsQuery =",
          "let Source = Json.Document(Web.Contents(\"https://api.loganalytics.io/v1/workspaces/\" & GetWorkspaceId & \"/query\", ",
          "[Query=[#\"query\"=\"",
          "set notruncation;",
          "let workspaceIdList = dynamic(['50EA7149-43DC-4DE3-8E56-4D5DBBC83E8F', 'C839BDCB-81B5-4DC3-9F92-818FE71432A1', '80FA5101-D77B-4AC3-B86A-EEAFE28E64AC']);",
          "",
          "let startDate = startofday(ago(\" & Number.ToText(#\"Days Ago To Start\") & \"d))- \"& Number.ToText(#\"UTC Offset Hours\" * 60) & \"m ;",
          "let endDate = endofday(ago(\" & Number.ToText(#\"Days Ago To Finish\") & \"d));",
          "let startIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Hours\") & \",todatetime(startDate));",
          "let endIngestionTime = datetime_add('hour', \" & Number.ToText(#\"Pagination Hours\") & \",todatetime(startIngestionTime));",
          "",
          "\"& #\"Log Analytics Table\" &  \" ",
          "| where TimeGenerated >= startIngestionTime and TimeGenerated < endIngestionTime",
          "| where (OperationName == 'AggregateTableRewriteQuery') ",
          "| extend TextDataHash = hash(EventText)",
          "| extend DurationMs = coalesce(DurationMs, 0)",
          "| extend User = iff(toupper(PowerBIWorkspaceId) in (workspaceIdList), hash_md5(User), User)",
          "| extend ExecutingUser = iff(toupper(PowerBIWorkspaceId) in (workspaceIdList), hash_md5(ExecutingUser), ExecutingUser)",
          "| distinct ApplicationName, CpuTimeMs, ArtifactId, ArtifactName, ArtifactKind, DatasetMode, DurationMs, EventText, ExecutingUser, OperationDetailName, OperationName, PremiumCapacityId, SourceSystem, Status, StatusCode, TenantId, TextDataHash, TimeGenerated, Type, User, PowerBIWorkspaceId, PowerBIWorkspaceName, XmlaRequestId, XmlaSessionId, XmlaObjectPath, _ResourceId, _SubscriptionId",
          "| project ApplicationName, CpuTimeMs, DatasetId = ArtifactId, Dataset = ArtifactName, ArtifactKind, DatasetMode, ['Duration (ms)'] = DurationMs, EventText, ExecutingUser, OperationDetailName, OperationName, PremiumCapacityId, SourceSystem, Status, StatusCode, TenantId, TextDataHash, TimeGenerated, Type, User, PowerBIWorkspaceId, PowerBIWorkspaceName, XmlaRequestId, XmlaSessionId, XmlaObjectPath, ResourceId = _ResourceId, SubscriptionId = _SubscriptionId, StartTime = TimeGenerated",
          "",
          "\"],Timeout=#duration(0,0,60,0)])),",
          "TypeMap = #table(",
          "{ \"AnalyticsTypes\", \"Type\" }, ",
          "{ ",
          "{ \"string\",   Text.Type },",
          "{ \"int\",      Int32.Type },",
          "{ \"long\",     Int64.Type },",
          "{ \"real\",     Double.Type },",
          "{ \"timespan\", Duration.Type },",
          "{ \"datetime\", DateTimeZone.Type },",
          "{ \"bool\",     Logical.Type },",
          "{ \"guid\",     Text.Type },",
          "{ \"dynamic\",  Text.Type }",
          "}),",
          "DataTable = Source[tables]{0},",
          "Columns = Table.FromRecords(DataTable[columns]),",
          "ColumnsWithType = Table.Join(Columns, {\"type\"}, TypeMap , {\"AnalyticsTypes\"}),",
          "Rows = Table.FromRows(DataTable[rows], Columns[name]), ",
          "Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))",
          "in",
          "Table,",
          "    #\"Added Start DateTime (UTC offset)\" = Table.AddColumn(#\"AnalyticsQuery\", \"Start DateTime\", each [TimeGenerated] + #duration(0,Number.RoundDown(#\"UTC Offset Hours\"),Number.RoundDown(60 * Number.Mod(#\"UTC Offset Hours\", 1)),0),type datetime),   ",
          "    #\"Inserted StartDate\" = Table.AddColumn(#\"Added Start DateTime (UTC offset)\", \"Start Date\", each DateTime.Date([Start DateTime]), type date),",
          "    #\"Start Time (s)\" = Table.AddColumn(#\"Inserted StartDate\", \"Start Time (s)\", each DateTime.Time([Start DateTime]), type time),",
          "    // #\"Inserted StartDate\" = Table.AddColumn(#\"Added Start DateTime (UTC offset)\", \"Start Date\", each Text.BeforeDelimiter(Text.From([Start DateTime], \"en-us\"), \" \") as text),",
          "    //#\"Start Time (s)\" = Table.AddColumn(#\"Inserted StartDate\", \"Start Time (s)\", each Text.BetweenDelimiters(Text.From([Start DateTime], \"en-US\"), \" \", \" \", 0, 1), type time),",
          "        ",
          "    //#\"Renamed Columns\" = Table.RenameColumns(#\"Start Time (s)\",{{\"DurationMs\", \"Duration (ms)\"}}),",
          "    #\"Added End Date/Time\" = Table.AddColumn(#\"Start Time (s)\", \"EndTime\", each [Start DateTime] + #duration(0, 0, 0, [#\"Duration (ms)\"] / 1000)),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added End Date/Time\",{{\"Start Date\", type date}, {\"Start DateTime\", type datetimezone}, {\"EndTime\", type datetimezone}}),",
          "    #\"Removed StartTime, TimeGenerated\" = Table.RemoveColumns(#\"Changed Type\",{\"TimeGenerated\", \"StartTime\"})",
          "in",
          "    #\"Removed StartTime, TimeGenerated\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "2efc6cbc-bace-4da8-b0c8-4edb39057561",
        "queryGroup": "Kusto queries"
      },
      {
        "name": "UTC Offset Hours",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "description": "Your offset in hours from UTC time. You can enter part hours, for example 5.5 for India.",
        "expression": "1 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "21d78875-0c22-44ca-b13a-730dcda605ac",
        "queryGroup": "Params"
      },
      {
        "name": "Pagination Hours",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "description": "To avoid query failure reduce the pagination hours. This strategy is useful when the initial failing query is too \"wide\". (Kusto limits the number of records returned to the client to 500,000, and the overall data size for those records to 64 MB.)",
        "expression": "4 meta [IsParameterQuery=true, List={1, 2, 4, 8, 12, 24}, DefaultValue=4, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d5b01e3e-c1d3-4c39-9cb9-2b6819422ff8",
        "queryGroup": "Params"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Params"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Helper queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Kusto queries"
      }
    ],
    "relationships": [
      {
        "name": "b528a2e5-c53a-4084-bf3e-46b79c82c51e",
        "fromColumn": "Start Time",
        "fromTable": "Operation",
        "toColumn": "Time (s)",
        "toTable": "Time"
      },
      {
        "name": "9e3753f4-39ac-4a47-b2a5-287535113465",
        "fromColumn": "Scenario ID",
        "fromTable": "Operation",
        "toColumn": "ID",
        "toTable": "Scenario"
      },
      {
        "name": "1d8cf401-9ece-4dd2-9342-1238f998769f",
        "fromColumn": "Query Duration Key",
        "fromTable": "Operation",
        "toColumn": "Query Duration Segment Key",
        "toTable": "Query Duration Segment"
      },
      {
        "name": "1ee4fc68-3481-4550-b51a-48505388bd45",
        "fromColumn": "XmlaRequestId",
        "fromTable": "Suboperation - Refresh",
        "toColumn": "Refresh Suboperation Key",
        "toTable": "Operation"
      },
      {
        "name": "f11f20aa-9e17-48b7-8b06-8a70af2d59da",
        "fromColumn": "XmlaRequestId",
        "fromTable": "Suboperation - Query",
        "toColumn": "Query Suboperation Key",
        "toTable": "Operation"
      },
      {
        "name": "333652f5-7c62-44c1-86d3-f211a62d2d09",
        "fromColumn": "XmlaRequestId",
        "fromTable": "Suboperation - Aggregations",
        "toColumn": "Agg Suboperation Key",
        "toTable": "Operation"
      },
      {
        "name": "bcbc260d-ac2f-4648-ba0c-d311741b507a",
        "fromColumn": "Executing User",
        "fromTable": "Operation",
        "toColumn": "Executing User",
        "toTable": "User"
      },
      {
        "name": "e0b3572b-f1c4-42df-be29-392449be7a19",
        "fromColumn": "Start Date",
        "fromTable": "Operation",
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a32c670634a44885b109a0f30041dfc5"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "474ae045-c17c-42c4-ba02-ea351f783a7f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Date (no year)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd mmm",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ef79d332-b628-469b-bffa-b628fc8224d0",
            "sourceColumn": "[Date (no year)]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fbb04464-0b66-4fd3-bcd9-e827157c1d94",
            "sourceColumn": "[Day of Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "159a7988-2d0f-4493-a0c2-7609ef13c44c",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4f2c347a-bb37-4f7a-ba18-9cc877ca58b4",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f8b87ebb-c8a3-461a-96b6-debe149ea737",
            "sourceColumn": "[Week number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b94b150b-06b2-47bf-bf53-7cbe155080de",
            "sourceColumn": "[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c5e38b38-72c1-4fcd-9bdb-4db7f8bf5fed",
            "sourceColumn": "[Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c16a6a1c-3ec9-4be8-8f6b-2948de8175f7",
            "sourceColumn": "[Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "94f43165-e3a8-465a-90e5-cebcd4121d10",
            "sourceColumn": "[Day of Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3baa4f07-9b24-4d07-a25b-ba5b37462c01",
            "sourceColumn": "[Day of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "48c13969-f68b-4858-9261-35992283dd8d",
            "sourceColumn": "[Day Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "7b82c505-c4c2-4f47-afe7-ec2250a1fcb2",
        "measures": [
          {
            "name": "Date Range",
            "expression": [
              "",
              "VAR Min_Date= MIN('Calendar'[Date])",
              "VAR Start_Range =",
              "CALCULATE ( ",
              "FORMAT (",
              "MIN ( 'Calendar'[Date] ),",
              "\"dd-mmm-yyyy\"",
              "),",
              "ALLSELECTED ( 'Calendar' )",
              ")",
              "VAR End_Range =",
              "CALCULATE (",
              "FORMAT (",
              "MAX ( 'Calendar'[Date] ),",
              "\"dd-mmm-yyyy\"",
              "),",
              "ALLSELECTED ( 'Calendar' )",
              ")",
              "RETURN",
              "IF ( ISBLANK(Min_Date) ||",
              "DATEDIFF (",
              "Start_Range,",
              "End_Range,",
              "DAY",
              ") = 0 ,",
              "Start_Range & \" \",",
              "Start_Range & \" - \" & End_Range",
              ")"
            ],
            "lineageTag": "22b5a4ae-f648-4b47-b495-e511a0621d90"
          },
          {
            "name": "Timeline Visualization",
            "expression": [
              "",
              "// This is the measure for the Value field of the timeline matrix. It takes the total duration (first start -> last end) in scope and divides it by the number of columns",
              "// in the matrix. That is the duration that each cell in the matrix represents. It then determies whether each cell should be painted (1 or 0) depending on whether the event's duration falls within the timeframe that the cell represents.",
              "VAR RangeStart =",
              "    CALCULATE (",
              "         FIRSTNONBLANK (",
              "            Operation[Start Date/Time],",
              "            TRUE ()",
              "        ),",
              "        ALLSELECTED ( 'Operation' )",
              "    )",
              "VAR RangeEnd =",
              "      CALCULATE (",
              "        MAX ( Operation[End Date/Time] ),",
              "        ALLSELECTED ( 'Operation' )",
              "    )",
              "VAR _numberOfColumnsInMatrix =",
              "    CALCULATE (",
              "        COUNTROWS ( 'Timeline Visual Columns' ),",
              "        REMOVEFILTERS ()",
              "    ) // How many columns will the matrix visual have? ",
              "VAR TimeSliceSeconds =",
              "    DIVIDE (",
              "        DATEDIFF (",
              "            RangeStart,",
              "            RangeEnd,",
              "            SECOND",
              "        ),",
              "        _numberOfColumnsInMatrix",
              "    )",
              "VAR CurrentSlice =",
              "    MAX ( 'Timeline Visual Columns'[Time Slice] )",
              "VAR CurrentColumnMin = RangeStart + ( CurrentSlice - 1 ) * TimeSliceSeconds / ( 60 * 60 * 24 )",
              "VAR CurrentColumnMax = RangeStart + CurrentSlice * TimeSliceSeconds / ( 60 * 60 * 24 )",
              "RETURN",
              "    IF (",
              "        AND (",
              "            MIN ( 'Operation'[Start Date/Time] ) <= CurrentColumnMax,",
              "            MIN (  'Operation'[End Date/Time] ) >= CurrentColumnMin",
              "        ),",
              "        1,",
              "        0",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "d4332b6d-c6c6-4f21-9024-02bb1e01863c"
          },
          {
            "name": "Gantt value(new)",
            "expression": [
              "",
              "VAR MinCalendar = MIN('Calendar'[Date])",
              "VAR MaxCalendar = MAX('Calendar'[Date])+1",
              "RETURN",
              "IF( (",
              "MIN(Operation[Start Date/Time]) >= MinCalendar && MAX(Operation[Start Date/Time]) < MaxCalendar),[Timeline Visualization],BLANK())"
            ],
            "formatString": "0",
            "lineageTag": "e5d228c4-ad42-4024-b6d0-95fe119906b7"
          },
          {
            "name": "Date New Customer",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( Operation[Start Date] ),",
              "    ALLEXCEPT (",
              "        Operation,",
              "        Operation[Executing User],",
              "        User",
              "    )",
              ")"
            ],
            "formatString": "General Date",
            "lineageTag": "1b24d9c8-c5ed-4e71-9e80-ef019ac511ca"
          }
        ],
        "partitions": [
          {
            "name": "Calendar-b535fc8f-9bfc-4148-8351-a8816d252b96",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _firstDate =",
                "    MIN ( 'Operation'[Start Date] )",
                "VAR _lastDate =",
                "    MAX ( 'Operation'[Start Date] )",
                "RETURN",
                "    ADDCOLUMNS (",
                "        CALENDAR (",
                "            _firstDate,",
                "            _lastDate",
                "        ),",
                "        \"Date (no year)\", [Date],",
                "           \"Day of Month\",DAY([Date]),",
                "    \"Year\", YEAR([Date]),",
                "    \"Quarter\", CONCATENATE(\"Q\", QUARTER([Date])),",
                "    \"Week number\", WEEKNUM([Date], 1),",
                "    \"Year Month\",YEAR([Date]) & \"-\" & MONTH([Date]),",
                "    \"Month Number\",MONTH([Date]),",
                "    \"Month Name\", FORMAT([Date],\"MMMM\"),",
                "    \"Day of Year\",DATEDIFF(DATE(YEAR([Date]),1,1),[Date],DAY)+1,",
                "    \"Day of Week\",WEEKDAY([Date],1),",
                "    \"Day Name\", FORMAT([Date],\"DDDD\"))"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Report Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "29e6330a-9023-428e-aacb-04c2bda03b37",
        "measures": [
          {
            "name": "Duration (ms)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "SUM( 'Operation'[Duration (ms)] ) "
            ],
            "formatString": "#,0",
            "lineageTag": "4d67fbc1-f59f-43bd-9a13-78b865f8c07c"
          },
          {
            "name": "CPU Time (ms)",
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "SUM ( 'Operation'[CPUTime (ms)] )"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "80518690-131b-4df7-92cc-1bb8ba995a0f"
          },
          {
            "name": "Operations",
            "displayFolder": "Count",
            "expression": [
              "",
              "COUNTROWS ( 'Operation' )"
            ],
            "formatString": "#,0",
            "lineageTag": "1c169129-4370-4b10-ab39-37bd7d37000d"
          },
          {
            "name": "CPU Time 50th Percentile",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "PERCENTILE.INC (",
              "    'Operation'[CPUTime (calculated)],",
              "    .5",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "7707ff0a-73b1-4e1d-ac1d-10231ebf478a"
          },
          {
            "name": "CPU Time 90th Percentile",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "PERCENTILE.INC (",
              "    'Operation'[CPUTime (calculated)],",
              "    .9",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "d5031911-99a9-4260-bf29-bdca7b1a28e1"
          },
          {
            "name": "CPU Time Std Dev",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "STDEV.P('Operation'[CPUTime (calculated)])"
            ],
            "formatString": "#,0",
            "lineageTag": "1c4063a2-f385-4d17-ab0d-aebefe16f4d9"
          },
          {
            "name": "CPU Time Std Dev %",
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "DIVIDE (",
              "    [CPU Time Std Dev],",
              "    [CPU Time Mean]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "1ee3f56f-4420-4fcc-ba8d-f4a63aa35ea2"
          },
          {
            "name": "CPU Time Mean",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "AVERAGE ( 'Operation'[CPUTime (calculated)] )"
            ],
            "formatString": "#,0",
            "lineageTag": "d8bc98af-adab-4083-a2d1-4d8950f2874e"
          },
          {
            "name": "Avg Duration",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "AVERAGE('Operation'[Duration (ms)])"
            ],
            "formatString": "#,0",
            "lineageTag": "2e5e0578-50e2-463c-a7c0-34aec55f25d0"
          },
          {
            "name": "Duration (ms) 50th Percentile",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "PERCENTILE.INC (",
              "    'Operation'[Duration (ms)],",
              "    .5",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "00042f3e-00ca-4dd0-8109-d3f4b66fa961"
          },
          {
            "name": "Duration (ms) 90th Percentile",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "PERCENTILE.INC (",
              "    'Operation'[Duration (ms)],",
              "    .9",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "6f588e63-4dde-4a78-8aab-55559e39dcb9"
          },
          {
            "name": "Duration Std Dev",
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "STDEV.P('Operation'[Duration (ms)]) "
            ],
            "formatString": "#,0.0",
            "lineageTag": "e518bab6-1e90-46a9-b82b-aaafe3fac135"
          },
          {
            "name": "Duration Std Dev %",
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "DIVIDE (",
              "    [Duration Std Dev],",
              "    [Avg Duration]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "4be92f10-8651-4e4b-adb2-cf4b14a42848"
          },
          {
            "name": "Suboperations - Refresh",
            "displayFolder": "Count",
            "expression": [
              "",
              "COUNTROWS ( 'Suboperation - Refresh' )"
            ],
            "formatString": "#,0",
            "lineageTag": "a4c804af-7d59-465e-abcf-06794cd50bbe"
          },
          {
            "name": "Refreshes",
            "displayFolder": "Count",
            "expression": [
              "",
              "CALCULATE (",
              "    [Operations],",
              "    'Operation'[Scenario ID] = 1",
              ")",
              "-- Refreshes"
            ],
            "formatString": "#,0",
            "lineageTag": "f6357772-910e-45f0-aa52-d36e053764b0"
          },
          {
            "name": "Queries",
            "displayFolder": "Count",
            "expression": [
              "",
              "CALCULATE (",
              "    [Operations],",
              "    Operation[Operation] = \"QueryEnd\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "bc288d3a-aa01-4442-b689-26576677a73d"
          },
          {
            "name": "CPU Time - Query",
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "// For DAX QueryEnds, CPU Time is calculated by adding the CPU Time of all VertiPaqSEQueryEnd suboperations to the CPU Time of the QueryEnd operation.",
              "// For DirectQuery queries, CPU Time is simply the QueryEnd CPU Time.",
              "VAR QueryEndSum =",
              "    CALCULATE (",
              "        SUM ( 'Operation'[CPUTime (ms)] ),",
              "        'Operation'[Operation] = \"QueryEnd\"",
              "    )",
              "VAR isDQ =",
              "    CALCULATE (",
              "        COUNTROWS (",
              "            VALUES ( 'Suboperation - Refresh'[Operation Detail] )",
              "        ),",
              "        'Suboperation - Refresh'[Operation Detail] = \"VertiPaqSEQueryEnd\"",
              "    )",
              "RETURN",
              "    IF (",
              "        isDQ,",
              "        QueryEndSum,",
              "        QueryEndSum + [CPU Time SE]",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "e14957a3-889c-414a-bd4b-daf331afc411"
          },
          {
            "name": "CPU Time - Refresh",
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "VAR OperationCPUTime =",
              "    CALCULATE (",
              "        SUM ( 'Operation'[CPUTime (ms)] ),",
              "        Scenario[ID] = 1",
              "    )",
              "VAR SuboperationCPUTime =",
              "    SUM ( 'Suboperation - Refresh'[CpuTimeMs] )",
              "RETURN",
              "    OperationCPUTime + SuboperationCPUTime"
            ],
            "formatString": "#,0",
            "lineageTag": "5cf7b60c-ef5e-4532-be08-94b464ea4057"
          },
          {
            "name": "CPU Time SE",
            "displayFolder": "CPU Time - Suboperation",
            "expression": [
              "",
              "// Storage Engine",
              "// https://github.com/DaxStudio/DaxStudio/blob/3cf6ef12dae03dcd06369e4248774068359fee7b/src/DaxStudio.UI/ViewModels/ServerTimesViewModel.cs#L287",
              "CALCULATE(",
              "        [CPU Time (ms) Suboperation - Query],",
              "        'Suboperation - Query'[Operation] IN ({\"VertiPaqSEQueryEnd\", \"DirectQueryEnd\"})",
              ")",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "a63d90c2-9bc4-4356-a2ed-740e2a3c265d"
          },
          {
            "name": "Duration SE",
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "CALCULATE(",
              "        [Duration - Suboperation - Refresh],",
              "        'Suboperation - Refresh'[Operation] IN ({\"VertiPaqSEQueryEnd\", \"DirectQueryEnd\"})",
              ")",
              "//Storage Engine",
              "//https://github.com/DaxStudio/DaxStudio/blob/3cf6ef12dae03dcd06369e4248774068359fee7b/src/DaxStudio.UI/ViewModels/ServerTimesViewModel.cs#L287"
            ],
            "formatString": "#,0",
            "lineageTag": "fdac3ac8-a8c5-41e9-9237-acd2f8372c9a"
          },
          {
            "name": "Query Rank by Duration 50th Percentile",
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "IF (",
              "    HASONEVALUE ( 'Operation'[TextDataHash] ),",
              "    RANKX (",
              "        ALLSELECTED ( 'Operation'[TextDataHash] ),",
              "        [Duration (ms) 50th Percentile],",
              "        ,",
              "        DESC",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "36ca1eac-49a2-4aac-a0b3-9b0d09df57a9"
          },
          {
            "name": "Duration FE",
            "displayFolder": "Duration - Operation",
            "expression": [
              "[Duration (ms)] - [Duration SE]",
              "//Formula engine",
              "//https://github.com/DaxStudio/DaxStudio/blob/3cf6ef12dae03dcd06369e4248774068359fee7b/src/DaxStudio.UI/ViewModels/ServerTimesViewModel.cs#L287"
            ],
            "formatString": "#,0",
            "lineageTag": "dab28dc3-a087-41cb-8543-67655521d550"
          },
          {
            "name": "Suboperations - Refresh (card)",
            "displayFolder": "Count",
            "expression": [
              "",
              "-- This measure is intended for card visuals only so any blanks will show a \"0\" instead of \"(Blank)\"",
              "VAR _return = [Suboperations - Refresh]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _return ),",
              "        0,",
              "        _return",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "13aa6366-158f-4e03-a899-e2b9b13db7c1"
          },
          {
            "name": "Refreshes (card)",
            "displayFolder": "Count",
            "expression": [
              "",
              "-- This measure is intended for card visuals only so any blanks will show a \"0\" instead of \"(Blank)\"",
              "VAR _return = [Refreshes]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _return ),",
              "        0,",
              "        _return",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "37424972-f5ab-46e1-9ba5-669b14ad6385"
          },
          {
            "name": "Queries (card)",
            "displayFolder": "Count",
            "expression": [
              "",
              "-- This measure is intended for card visuals only so any blanks will show a \"0\" instead of \"(Blank)\"",
              "VAR _return = [Queries]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _return ),",
              "        0,",
              "        _return",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "8d1894e3-09bc-4bd1-9eab-10a2f6345b02"
          },
          {
            "name": "CPU Time FE",
            "displayFolder": "CPU Time - Suboperation",
            "expression": [
              "[CPU Time - Query] - [CPU Time SE]",
              "//Formula engine",
              "//https://github.com/DaxStudio/DaxStudio/blob/3cf6ef12dae03dcd06369e4248774068359fee7b/src/DaxStudio.UI/ViewModels/ServerTimesViewModel.cs#L287"
            ],
            "formatString": "#,0",
            "lineageTag": "2790d27c-dd1d-4389-b5c0-385d11af37c6"
          },
          {
            "name": "Query Cache Hits",
            "displayFolder": "Count",
            "expression": [
              "",
              "CALCULATE (",
              "    [Queries],",
              "    'Suboperation - Query'[Operation] = \"VertiPaqSEQueryCacheMatch\",",
              "    CROSSFILTER ( Operation[Query Suboperation Key], 'Suboperation - Query'[XmlaRequestId], BOTH )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0baf7ae5-8872-4c81-b70b-0db6042ac414"
          },
          {
            "name": "CPU Time (ms) Suboperation - Refresh",
            "displayFolder": "CPU Time - Suboperation",
            "expression": [
              "",
              "SUM('Suboperation - Refresh'[CpuTimeMs]) "
            ],
            "formatString": "#,0",
            "lineageTag": "65302eb2-6e8a-42eb-8757-c7b00157389a"
          },
          {
            "name": "Duration - Suboperation - Refresh",
            "displayFolder": "Duration - Suboperation",
            "expression": [
              "",
              "SUM( 'Suboperation - Refresh'[Duration (ms)] ) "
            ],
            "formatString": "#,0",
            "lineageTag": "f4c7e3b6-eac7-4cb7-99a4-c89a09f081bf"
          },
          {
            "name": "Operations (card)",
            "displayFolder": "Count",
            "expression": [
              "",
              "-- This measure is intended for card visuals only so any blanks will show a \"0\" instead of \"(Blank)\"",
              "VAR _return = [Operations]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _return ),",
              "        0,",
              "        _return",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "bb17a1ca-b7d1-4b99-978c-6e44a3db399d"
          },
          {
            "name": "CPUTime Max Suboperation - Refresh",
            "displayFolder": "CPU Time - Suboperation",
            "expression": [
              "",
              "MAX('Suboperation - Refresh'[CpuTimeMs])"
            ],
            "formatString": "#,0",
            "lineageTag": "f3b85869-14d9-44ec-bd90-8cf649124310"
          },
          {
            "name": "CPU Time - Max",
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "MAX ( Operation[CPUTime (calculated)] )"
            ],
            "formatString": "#,0",
            "lineageTag": "c1f29fca-9c9a-4580-8990-54be66e43ed3"
          },
          {
            "name": "Report DCount",
            "displayFolder": "Count",
            "expression": [
              "",
              "DISTINCTCOUNT ( Operation[ReportId] )"
            ],
            "formatString": "#,0",
            "lineageTag": "a8ed4df9-9696-47ca-a91f-c00e97cbc213"
          },
          {
            "name": "User count",
            "displayFolder": "Count",
            "expression": [
              "",
              "DISTINCTCOUNT (Operation[Executing User] )"
            ],
            "formatString": "#,0",
            "lineageTag": "64fe7776-96bc-4f9f-a93d-b66547228650"
          },
          {
            "name": "Dataset Dcount",
            "displayFolder": "Count",
            "expression": [
              "",
              "DISTINCTCOUNT ( Operation[DatasetId] )"
            ],
            "formatString": "#,0",
            "lineageTag": "30ade1d2-5968-4270-ae43-28611efcd955"
          },
          {
            "name": "Query Detail.Related Queries",
            "displayFolder": "Titles",
            "expression": [
              "",
              "\"Related queries details (\"",
              "    & FORMAT (",
              "        [Suboperations - Query (card)],",
              "        \"#,##0\"",
              "    ) & \")\""
            ],
            "lineageTag": "02faa3f8-7aa1-4864-9a7f-8c7e23643110"
          },
          {
            "name": "Dataset Refresh.Data Refresh Operations",
            "displayFolder": "Titles",
            "expression": [
              "",
              "\"Dataset refresh operations (\"",
              "    & FORMAT (",
              "        [Refreshes (card)],",
              "        \"#,##0\"",
              "    ) & \")\""
            ],
            "lineageTag": "24917862-4900-4ea0-8608-c2e4da282ec0"
          },
          {
            "name": "Workspace DCount",
            "displayFolder": "Count",
            "expression": [
              "",
              "DISTINCTCOUNT ( Operation[WorkspaceId] )"
            ],
            "formatString": "#,0",
            "lineageTag": "acc18f81-093a-4b86-baf8-26f1e157a145"
          },
          {
            "name": "Operations.Operations",
            "displayFolder": "Titles",
            "expression": [
              "",
              "\"Operations (\"",
              "    & FORMAT (",
              "        [Operations (card)],",
              "        \"#,##0\"",
              "    ) & \")\""
            ],
            "lineageTag": "859ef5cb-dd92-485f-8ea7-bec7dae77072"
          },
          {
            "name": "Query History.Query Executions",
            "displayFolder": "Titles",
            "expression": [
              "",
              "\"Query executions (\"",
              "    & FORMAT (",
              "        [Operations],",
              "        \"#,##0\"",
              "    ) & \")\""
            ],
            "lineageTag": "73317778-9851-4232-8002-8233e5860d82"
          },
          {
            "name": "CPU Time P50 Sparkline",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline",
            "expression": [
              "",
              "VAR LineColor = \"#363636\" // Line color",
              "VAR FillColor = \"#ffffff\" // Fill color",
              "VAR MaxDotColor = \"#649398\" // Max dot color",
              "VAR MinDotColor = \"#D9655D\" // Min dot color",
              "VAR FirstDotColor = \"#363636\" // First dot color",
              "VAR LastDotColor = \"#363636\" // Last dot color",
              "VAR NumOfDashes = 0 // Change this number to the number of dashes you'd like the line to be, 0 is a solid line",
              "VAR DataPointPoint = DISTINCTCOUNT('Calendar'[Date]) // Put \"date\" here, distinct count of x axis data points",
              "VAR StrokeWidth = // Dynamic line stroke width, decreases stroke width as data points increase",
              "    SWITCH( TRUE(), ",
              "    DataPointPoint > 24, 3, ",
              "    DataPointPoint > 12, 4, ",
              "    5)",
              "VAR CircleSize = // Dynamic circle size, decreases circle size as data points increase",
              "    SWITCH(TRUE(), ",
              "    DataPointPoint > 24, 8, ",
              "    DataPointPoint > 12, 9, ",
              "    10)",
              "VAR ViewboxOffset = // Viewbox Offset for circle size, matches circles to keep them visible as size changes",
              "    SWITCH(TRUE(), ",
              "    DataPointPoint > 24, -8, ",
              "    DataPointPoint > 12, -9, ",
              "    -10)",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN('Calendar'[Date])",
              "VAR XMaxDate = MAX('Calendar'[Date])",
              "// Obtains overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX( VALUES('Calendar'[Date]), CALCULATE([CPU Time 50th Percentile]))",
              "VAR YMaxValue = MAXX( VALUES('Calendar'[Date]), CALCULATE([CPU Time 50th Percentile]))",
              "// Build table of X & Y coordinates and fit to 100 x 100 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('Calendar', 'Calendar'[Date]),",
              "        \"X\",INT(100 * DIVIDE('Calendar'[Date] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(100 * DIVIDE([CPU Time 50th Percentile] - YMinValue, YMaxValue - YMinValue)))",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 100 - [Y], \" \", 'Calendar'[Date])",
              "// Create circles for the min and max data points on the line",
              "VAR MaxSparkYValue = MAXX(SparklineTable, 100 - [Y])",
              "VAR MaxSparkXValue = MAXX( FILTER(SparklineTable, [Y] = MaxSparkYValue), [X])",
              "VAR MinSparkYValue = MINX(SparklineTable, 100 - [Y])",
              "VAR MinSparkXValue = MINX( FILTER(SparklineTable, [Y] = MinSparkYValue), [X])",
              "// Create circles for the first and last data points on the line",
              "VAR FirstSparkYValue = MINX( FILTER(SparklineTable, 'Calendar'[Date] = XMinDate), [Y])",
              "VAR FirstSparkXValue = MINX( FILTER(SparklineTable, 'Calendar'[Date] = XMinDate), [X])",
              "VAR LastSparkYValue = MAXX( FILTER(SparklineTable, 'Calendar'[Date] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX( FILTER(SparklineTable, 'Calendar'[Date] = XMaxDate), [X])",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='0 \" & ViewboxOffset & \" 100 120'>\" &",
              "    \"<polyline ",
              "        fill='\" & FillColor & \"' ",
              "        stroke='\" & LineColor & \"' ",
              "        stroke-width='\" & StrokeWidth & \"' ",
              "        stroke-linecap='round' ",
              "        stroke-linejoin='round' ",
              "        stroke-dasharray='\" & NumOfDashes & \"'",
              "        points='\" & Lines & ",
              "    \"'/>\" & ",
              "    //\"<circle cx='\"& FirstSparkXValue & \"' cy='\" & 100 - FirstSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & FirstDotColor & \"' />\" & // First sparkline circle",
              "    //\"<circle cx='\"& LastSparkXValue & \"' cy='\" & 100 - LastSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & LastDotColor & \"' />\" & // Last sparkline circle",
              "   // \"<circle cx='\"& MaxSparkXValue & \"' cy='\" & 100 - MaxSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & MaxDotColor & \"' />\" & // Max sparkline circle",
              "    //\"<circle cx='\"& MinSparkXValue & \"' cy='\" & 100 - MinSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & MinDotColor & \"' />\" & // Min sparkline circle",
              "    \"</svg>\"",
              "RETURN",
              "SVGImageURL --IF( HASONEVALUE('Calendar'[Date]), SVGImageURL)"
            ],
            "lineageTag": "1350c703-c646-46dd-83ec-daa6625ce96e"
          },
          {
            "name": "Total Executions Sparkline",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline",
            "expression": [
              "",
              "VAR LineColor = \"#363636\" // Line color",
              "VAR FillColor = \"#ffffff\" // Fill color",
              "VAR MaxDotColor = \"#649398\" // Max dot color",
              "VAR MinDotColor = \"#D9655D\" // Min dot color",
              "VAR FirstDotColor = \"#363636\" // First dot color",
              "VAR LastDotColor = \"#363636\" // Last dot color",
              "VAR NumOfDashes = 0 // Change this number to the number of dashes you'd like the line to be, 0 is a solid line",
              "VAR DataPointPoint = DISTINCTCOUNT('Calendar'[Date]) // Put \"date\" here, distinct count of x axis data points",
              "VAR StrokeWidth = // Dynamic line stroke width, decreases stroke width as data points increase",
              "    SWITCH( TRUE(), ",
              "    DataPointPoint > 24, 3, ",
              "    DataPointPoint > 12, 4, ",
              "    5)",
              "VAR CircleSize = // Dynamic circle size, decreases circle size as data points increase",
              "    SWITCH(TRUE(), ",
              "    DataPointPoint > 24, 8, ",
              "    DataPointPoint > 12, 9, ",
              "    10)",
              "VAR ViewboxOffset = // Viewbox Offset for circle size, matches circles to keep them visible as size changes",
              "    SWITCH(TRUE(), ",
              "    DataPointPoint > 24, -8, ",
              "    DataPointPoint > 12, -9, ",
              "    -10)",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN('Calendar'[Date])",
              "VAR XMaxDate = MAX('Calendar'[Date])",
              "// Obtains overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX( VALUES('Calendar'[Date]), CALCULATE([Operations]))",
              "VAR YMaxValue = MAXX( VALUES('Calendar'[Date]), CALCULATE([Operations]))",
              "// Build table of X & Y coordinates and fit to 100 x 100 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('Calendar', 'Calendar'[Date]),",
              "        \"X\",INT(100 * DIVIDE('Calendar'[Date] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(100 * DIVIDE([Operations] - YMinValue, YMaxValue - YMinValue)))",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 100 - [Y], \" \", 'Calendar'[Date])",
              "// Create circles for the min and max data points on the line",
              "VAR MaxSparkYValue = MAXX(SparklineTable, 100 - [Y])",
              "VAR MaxSparkXValue = MAXX( FILTER(SparklineTable, [Y] = MaxSparkYValue), [X])",
              "VAR MinSparkYValue = MINX(SparklineTable, 100 - [Y])",
              "VAR MinSparkXValue = MINX( FILTER(SparklineTable, [Y] = MinSparkYValue), [X])",
              "// Create circles for the first and last data points on the line",
              "VAR FirstSparkYValue = MINX( FILTER(SparklineTable, 'Calendar'[Date] = XMinDate), [Y])",
              "VAR FirstSparkXValue = MINX( FILTER(SparklineTable, 'Calendar'[Date] = XMinDate), [X])",
              "VAR LastSparkYValue = MAXX( FILTER(SparklineTable, 'Calendar'[Date] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX( FILTER(SparklineTable, 'Calendar'[Date] = XMaxDate), [X])",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='0 \" & ViewboxOffset & \" 100 120'>\" &",
              "    \"<polyline ",
              "        fill='\" & FillColor & \"' ",
              "        stroke='\" & LineColor & \"' ",
              "        stroke-width='\" & StrokeWidth & \"' ",
              "        stroke-linecap='round' ",
              "        stroke-linejoin='round' ",
              "        stroke-dasharray='\" & NumOfDashes & \"'",
              "        points='\" & Lines & ",
              "    \"'/>\" & ",
              "    //\"<circle cx='\"& FirstSparkXValue & \"' cy='\" & 100 - FirstSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & FirstDotColor & \"' />\" & // First sparkline circle",
              "    //\"<circle cx='\"& LastSparkXValue & \"' cy='\" & 100 - LastSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & LastDotColor & \"' />\" & // Last sparkline circle",
              "   // \"<circle cx='\"& MaxSparkXValue & \"' cy='\" & 100 - MaxSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & MaxDotColor & \"' />\" & // Max sparkline circle",
              "    //\"<circle cx='\"& MinSparkXValue & \"' cy='\" & 100 - MinSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & MinDotColor & \"' />\" & // Min sparkline circle",
              "    \"</svg>\"",
              "RETURN",
              "SVGImageURL --IF( HASONEVALUE('Calendar'[Date]), SVGImageURL)"
            ],
            "lineageTag": "ef754dd8-2d68-4ba0-81e0-bea46e1809c8"
          },
          {
            "name": "CPU Time P90 Sparkline",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline",
            "expression": [
              "",
              "VAR LineColor = \"#363636\" // Line color",
              "VAR FillColor = \"#ffffff\" // Fill color",
              "VAR MaxDotColor = \"#649398\" // Max dot color",
              "VAR MinDotColor = \"#D9655D\" // Min dot color",
              "VAR FirstDotColor = \"#363636\" // First dot color",
              "VAR LastDotColor = \"#363636\" // Last dot color",
              "VAR NumOfDashes = 0 // Change this number to the number of dashes you'd like the line to be, 0 is a solid line",
              "VAR DataPointPoint = DISTINCTCOUNT('Calendar'[Date]) // Put \"date\" here, distinct count of x axis data points",
              "VAR StrokeWidth = // Dynamic line stroke width, decreases stroke width as data points increase",
              "    SWITCH( TRUE(), ",
              "    DataPointPoint > 24, 3, ",
              "    DataPointPoint > 12, 4, ",
              "    5)",
              "VAR CircleSize = // Dynamic circle size, decreases circle size as data points increase",
              "    SWITCH(TRUE(), ",
              "    DataPointPoint > 24, 8, ",
              "    DataPointPoint > 12, 9, ",
              "    10)",
              "VAR ViewboxOffset = // Viewbox Offset for circle size, matches circles to keep them visible as size changes",
              "    SWITCH(TRUE(), ",
              "    DataPointPoint > 24, -8, ",
              "    DataPointPoint > 12, -9, ",
              "    -10)",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN('Calendar'[Date])",
              "VAR XMaxDate = MAX('Calendar'[Date])",
              "// Obtains overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX( VALUES('Calendar'[Date]), CALCULATE([CPU Time 90th Percentile]))",
              "VAR YMaxValue = MAXX( VALUES('Calendar'[Date]), CALCULATE([CPU Time 90th Percentile]))",
              "// Build table of X & Y coordinates and fit to 100 x 100 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('Calendar', 'Calendar'[Date]),",
              "        \"X\",INT(100 * DIVIDE('Calendar'[Date] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(100 * DIVIDE([CPU Time 90th Percentile] - YMinValue, YMaxValue - YMinValue)))",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 100 - [Y], \" \", 'Calendar'[Date])",
              "// Create circles for the min and max data points on the line",
              "VAR MaxSparkYValue = MAXX(SparklineTable, 100 - [Y])",
              "VAR MaxSparkXValue = MAXX( FILTER(SparklineTable, [Y] = MaxSparkYValue), [X])",
              "VAR MinSparkYValue = MINX(SparklineTable, 100 - [Y])",
              "VAR MinSparkXValue = MINX( FILTER(SparklineTable, [Y] = MinSparkYValue), [X])",
              "// Create circles for the first and last data points on the line",
              "VAR FirstSparkYValue = MINX( FILTER(SparklineTable, 'Calendar'[Date] = XMinDate), [Y])",
              "VAR FirstSparkXValue = MINX( FILTER(SparklineTable, 'Calendar'[Date] = XMinDate), [X])",
              "VAR LastSparkYValue = MAXX( FILTER(SparklineTable, 'Calendar'[Date] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX( FILTER(SparklineTable, 'Calendar'[Date] = XMaxDate), [X])",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='0 \" & ViewboxOffset & \" 100 120'>\" &",
              "    \"<polyline ",
              "        fill='\" & FillColor & \"' ",
              "        stroke='\" & LineColor & \"' ",
              "        stroke-width='\" & StrokeWidth & \"' ",
              "        stroke-linecap='round' ",
              "        stroke-linejoin='round' ",
              "        stroke-dasharray='\" & NumOfDashes & \"'",
              "        points='\" & Lines & ",
              "    \"'/>\" & ",
              "    //\"<circle cx='\"& FirstSparkXValue & \"' cy='\" & 100 - FirstSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & FirstDotColor & \"' />\" & // First sparkline circle",
              "    //\"<circle cx='\"& LastSparkXValue & \"' cy='\" & 100 - LastSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & LastDotColor & \"' />\" & // Last sparkline circle",
              "   // \"<circle cx='\"& MaxSparkXValue & \"' cy='\" & 100 - MaxSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & MaxDotColor & \"' />\" & // Max sparkline circle",
              "    //\"<circle cx='\"& MinSparkXValue & \"' cy='\" & 100 - MinSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & MinDotColor & \"' />\" & // Min sparkline circle",
              "    \"</svg>\"",
              "RETURN",
              "SVGImageURL --IF( HASONEVALUE('Calendar'[Date]), SVGImageURL)"
            ],
            "lineageTag": "84b683fa-7809-429d-8d60-be9c60278213"
          },
          {
            "name": "Duration P50 Sparkline",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline",
            "expression": [
              "",
              "VAR LineColor = \"#363636\" // Line color",
              "VAR FillColor = \"#ffffff\" // Fill color",
              "VAR MaxDotColor = \"#649398\" // Max dot color",
              "VAR MinDotColor = \"#D9655D\" // Min dot color",
              "VAR FirstDotColor = \"#363636\" // First dot color",
              "VAR LastDotColor = \"#363636\" // Last dot color",
              "VAR NumOfDashes = 0 // Change this number to the number of dashes you'd like the line to be, 0 is a solid line",
              "VAR DataPointPoint = DISTINCTCOUNT('Calendar'[Date]) // Put \"date\" here, distinct count of x axis data points",
              "VAR StrokeWidth = // Dynamic line stroke width, decreases stroke width as data points increase",
              "    SWITCH( TRUE(), ",
              "    DataPointPoint > 24, 3, ",
              "    DataPointPoint > 12, 4, ",
              "    5)",
              "VAR CircleSize = // Dynamic circle size, decreases circle size as data points increase",
              "    SWITCH(TRUE(), ",
              "    DataPointPoint > 24, 8, ",
              "    DataPointPoint > 12, 9, ",
              "    10)",
              "VAR ViewboxOffset = // Viewbox Offset for circle size, matches circles to keep them visible as size changes",
              "    SWITCH(TRUE(), ",
              "    DataPointPoint > 24, -8, ",
              "    DataPointPoint > 12, -9, ",
              "    -10)",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN('Calendar'[Date])",
              "VAR XMaxDate = MAX('Calendar'[Date])",
              "// Obtains overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX( VALUES('Calendar'[Date]), CALCULATE([Duration (ms) 50th Percentile]))",
              "VAR YMaxValue = MAXX( VALUES('Calendar'[Date]), CALCULATE([Duration (ms) 50th Percentile]))",
              "// Build table of X & Y coordinates and fit to 100 x 100 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('Calendar', 'Calendar'[Date]),",
              "        \"X\",INT(100 * DIVIDE('Calendar'[Date] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(100 * DIVIDE([Duration (ms) 50th Percentile] - YMinValue, YMaxValue - YMinValue)))",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 100 - [Y], \" \", 'Calendar'[Date])",
              "// Create circles for the min and max data points on the line",
              "VAR MaxSparkYValue = MAXX(SparklineTable, 100 - [Y])",
              "VAR MaxSparkXValue = MAXX( FILTER(SparklineTable, [Y] = MaxSparkYValue), [X])",
              "VAR MinSparkYValue = MINX(SparklineTable, 100 - [Y])",
              "VAR MinSparkXValue = MINX( FILTER(SparklineTable, [Y] = MinSparkYValue), [X])",
              "// Create circles for the first and last data points on the line",
              "VAR FirstSparkYValue = MINX( FILTER(SparklineTable, 'Calendar'[Date] = XMinDate), [Y])",
              "VAR FirstSparkXValue = MINX( FILTER(SparklineTable, 'Calendar'[Date] = XMinDate), [X])",
              "VAR LastSparkYValue = MAXX( FILTER(SparklineTable, 'Calendar'[Date] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX( FILTER(SparklineTable, 'Calendar'[Date] = XMaxDate), [X])",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='0 \" & ViewboxOffset & \" 100 120'>\" &",
              "    \"<polyline ",
              "        fill='\" & FillColor & \"' ",
              "        stroke='\" & LineColor & \"' ",
              "        stroke-width='\" & StrokeWidth & \"' ",
              "        stroke-linecap='round' ",
              "        stroke-linejoin='round' ",
              "        stroke-dasharray='\" & NumOfDashes & \"'",
              "        points='\" & Lines & ",
              "    \"'/>\" & ",
              "    //\"<circle cx='\"& FirstSparkXValue & \"' cy='\" & 100 - FirstSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & FirstDotColor & \"' />\" & // First sparkline circle",
              "    //\"<circle cx='\"& LastSparkXValue & \"' cy='\" & 100 - LastSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & LastDotColor & \"' />\" & // Last sparkline circle",
              "   // \"<circle cx='\"& MaxSparkXValue & \"' cy='\" & 100 - MaxSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & MaxDotColor & \"' />\" & // Max sparkline circle",
              "    //\"<circle cx='\"& MinSparkXValue & \"' cy='\" & 100 - MinSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & MinDotColor & \"' />\" & // Min sparkline circle",
              "    \"</svg>\"",
              "RETURN",
              "SVGImageURL --IF( HASONEVALUE('Calendar'[Date]), SVGImageURL)"
            ],
            "lineageTag": "744df686-24fc-4b29-b588-9acb915dabe8"
          },
          {
            "name": "Duration P90 Sparkline",
            "dataCategory": "ImageUrl",
            "displayFolder": "Sparkline",
            "expression": [
              "",
              "VAR LineColor = \"#363636\" // Line color",
              "VAR FillColor = \"#ffffff\" // Fill color",
              "VAR MaxDotColor = \"#649398\" // Max dot color",
              "VAR MinDotColor = \"#D9655D\" // Min dot color",
              "VAR FirstDotColor = \"#363636\" // First dot color",
              "VAR LastDotColor = \"#363636\" // Last dot color",
              "VAR NumOfDashes = 0 // Change this number to the number of dashes you'd like the line to be, 0 is a solid line",
              "VAR DataPointPoint = DISTINCTCOUNT('Calendar'[Date]) // Put \"date\" here, distinct count of x axis data points",
              "VAR StrokeWidth = // Dynamic line stroke width, decreases stroke width as data points increase",
              "    SWITCH( TRUE(), ",
              "    DataPointPoint > 24, 3, ",
              "    DataPointPoint > 12, 4, ",
              "    5)",
              "VAR CircleSize = // Dynamic circle size, decreases circle size as data points increase",
              "    SWITCH(TRUE(), ",
              "    DataPointPoint > 24, 8, ",
              "    DataPointPoint > 12, 9, ",
              "    10)",
              "VAR ViewboxOffset = // Viewbox Offset for circle size, matches circles to keep them visible as size changes",
              "    SWITCH(TRUE(), ",
              "    DataPointPoint > 24, -8, ",
              "    DataPointPoint > 12, -9, ",
              "    -10)",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN('Calendar'[Date])",
              "VAR XMaxDate = MAX('Calendar'[Date])",
              "// Obtains overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX( VALUES('Calendar'[Date]), CALCULATE([Duration (ms) 90th Percentile]))",
              "VAR YMaxValue = MAXX( VALUES('Calendar'[Date]), CALCULATE([Duration (ms) 90th Percentile]))",
              "// Build table of X & Y coordinates and fit to 100 x 100 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('Calendar', 'Calendar'[Date]),",
              "        \"X\",INT(100 * DIVIDE('Calendar'[Date] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(100 * DIVIDE([Duration (ms) 90th Percentile] - YMinValue, YMaxValue - YMinValue)))",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable, [X] & \",\" & 100 - [Y], \" \", 'Calendar'[Date])",
              "// Create circles for the min and max data points on the line",
              "VAR MaxSparkYValue = MAXX(SparklineTable, 100 - [Y])",
              "VAR MaxSparkXValue = MAXX( FILTER(SparklineTable, [Y] = MaxSparkYValue), [X])",
              "VAR MinSparkYValue = MINX(SparklineTable, 100 - [Y])",
              "VAR MinSparkXValue = MINX( FILTER(SparklineTable, [Y] = MinSparkYValue), [X])",
              "// Create circles for the first and last data points on the line",
              "VAR FirstSparkYValue = MINX( FILTER(SparklineTable, 'Calendar'[Date] = XMinDate), [Y])",
              "VAR FirstSparkXValue = MINX( FILTER(SparklineTable, 'Calendar'[Date] = XMinDate), [X])",
              "VAR LastSparkYValue = MAXX( FILTER(SparklineTable, 'Calendar'[Date] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX( FILTER(SparklineTable, 'Calendar'[Date] = XMaxDate), [X])",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='0 \" & ViewboxOffset & \" 100 120'>\" &",
              "    \"<polyline ",
              "        fill='\" & FillColor & \"' ",
              "        stroke='\" & LineColor & \"' ",
              "        stroke-width='\" & StrokeWidth & \"' ",
              "        stroke-linecap='round' ",
              "        stroke-linejoin='round' ",
              "        stroke-dasharray='\" & NumOfDashes & \"'",
              "        points='\" & Lines & ",
              "    \"'/>\" & ",
              "    //\"<circle cx='\"& FirstSparkXValue & \"' cy='\" & 100 - FirstSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & FirstDotColor & \"' />\" & // First sparkline circle",
              "    //\"<circle cx='\"& LastSparkXValue & \"' cy='\" & 100 - LastSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & LastDotColor & \"' />\" & // Last sparkline circle",
              "   // \"<circle cx='\"& MaxSparkXValue & \"' cy='\" & 100 - MaxSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & MaxDotColor & \"' />\" & // Max sparkline circle",
              "    //\"<circle cx='\"& MinSparkXValue & \"' cy='\" & 100 - MinSparkYValue & \"' r='\" & CircleSize & \"' fill='\" & MinDotColor & \"' />\" & // Min sparkline circle",
              "    \"</svg>\"",
              "RETURN",
              "SVGImageURL --IF( HASONEVALUE('Calendar'[Date]), SVGImageURL)"
            ],
            "lineageTag": "21727d4e-4a09-41b3-b828-5245ba49cd1a"
          },
          {
            "name": "CPU Time (ms) Total",
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "SWITCH( MIN(Scenario[ID] ),",
              "1, [CPU Time - Refresh],",
              "2, [CPU Time - Query],",
              "[CPU Time (ms)]",
              " ) //"
            ],
            "formatString": "#,0",
            "lineageTag": "d4e265ac-9a55-4695-b3af-3b2797d0c775"
          },
          {
            "name": "Duration - Refresh",
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "VAR OperationDuration =",
              "    CALCULATE (",
              "        [Duration (ms)],",
              "        Scenario[ID] = 1",
              "    )",
              "RETURN",
              "    OperationDuration"
            ],
            "formatString": "#,0",
            "lineageTag": "099f7a96-810e-46d6-b283-8f824fed0d87"
          },
          {
            "name": "Dataset Refresh Detail.Refresh Information",
            "displayFolder": "Titles",
            "expression": [
              "",
              "\"Dataset refresh rootActivityId: \"",
              "    & MIN ( Operation[XmlaRequestId] )"
            ],
            "lineageTag": "dd703faf-9d0d-461e-a730-6524945b338e"
          },
          {
            "name": "Dataset Refresh Detail.CPU Time",
            "displayFolder": "Titles",
            "expression": [
              "",
              "\"CPU time: \"",
              "    & FORMAT (",
              "        [CPU Time (ms) Total],",
              "        \"#,###\"",
              "    ) & \" ms\""
            ],
            "lineageTag": "77b21591-e9c4-492a-88c5-33bca758a606"
          },
          {
            "name": "Dataset Refresh Detail.Duration",
            "displayFolder": "Titles",
            "expression": [
              "",
              "VAR _duration = [Duration (ms)]",
              "RETURN",
              "    IF (",
              "        _duration > 0,",
              "        \"Duration: \"",
              "            & FORMAT (",
              "                [Duration (ms)],",
              "                \"#,###\"",
              "            ) & \" ms\",",
              "        \"Duration: 0 ms\"",
              "    )"
            ],
            "lineageTag": "d1640120-9548-4fab-857e-c547a1826d22"
          },
          {
            "name": "Dataset Refresh.Data Refresh Suboperations",
            "displayFolder": "Titles",
            "expression": [
              "",
              "\"Dataset refresh suboperations (\"",
              "    & FORMAT (",
              "        [Suboperations - Refresh (card)],",
              "        \"#,##0\"",
              "    ) & \")\""
            ],
            "lineageTag": "5b8def65-399c-49d4-ab52-f12d44412696"
          },
          {
            "name": "Capacity DCount",
            "displayFolder": "Count",
            "expression": [
              "",
              "DISTINCTCOUNT ( Operation[PremiumCapacityId] )"
            ],
            "formatString": "#,0",
            "lineageTag": "728cc434-3367-4fb6-b035-b3f9ed00ae3d"
          },
          {
            "name": "Query - success",
            "displayFolder": "Count",
            "expression": [
              "",
              "CALCULATE (",
              "    [Queries],",
              "    Operation[StatusCode] = 0",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "00d1dbea-bb7f-4aea-b676-28ec0061104f"
          },
          {
            "name": "Query - failure",
            "displayFolder": "Count",
            "expression": [
              "",
              "",
              "CALCULATE (",
              "    [Queries],",
              "    Operation[StatusCode] <> 0",
              ")",
              "",
              "// 0 = success, non-zero (usually negative) = failure"
            ],
            "formatString": "#,0",
            "lineageTag": "5e5d5c3a-348e-4d3f-8a3f-b9dc1b34c958"
          },
          {
            "name": "Query - success rate",
            "displayFolder": "Count",
            "expression": [
              "",
              "VAR successes = [Query - success]",
              "RETURN",
              "    DIVIDE (",
              "        successes,",
              "        successes + [Query - failure]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "bb7365aa-7b2a-4a56-b1fb-4e3f43972e7e"
          },
          {
            "name": "Query - failure rate",
            "displayFolder": "Count",
            "expression": [
              "",
              "VAR failiures = [Query - failure]",
              "RETURN",
              "    DIVIDE (",
              "        failiures,",
              "        [Query - success] + failiures",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "194a32d6-9487-43ce-9ea8-d4292627c065"
          },
          {
            "name": "Duration - Max",
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "MAX(Operation[Duration (ms)])"
            ],
            "formatString": "#,0",
            "lineageTag": "5aa8c59d-e2aa-4cfb-b43c-6b69c8820833"
          },
          {
            "name": "Suboperations - Query",
            "displayFolder": "Count",
            "expression": [
              "",
              "COUNTROWS ( 'Suboperation - Query' )"
            ],
            "formatString": "#,0",
            "lineageTag": "1786fc1c-f9bc-4d82-83cb-4af64396031b"
          },
          {
            "name": "Suboperations - Query (card)",
            "displayFolder": "Count",
            "expression": [
              "",
              "-- This measure is intended for card visuals only so any blanks will show a \"0\" instead of \"(Blank)\"",
              "VAR _return = [Suboperations - Query]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _return ),",
              "        0,",
              "        _return",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "dd90cca7-4b70-4b83-987a-f747483bf329"
          },
          {
            "name": "CPU Time (ms) Suboperation - Query",
            "displayFolder": "CPU Time - Suboperation",
            "expression": [
              "",
              "SUM ( 'Suboperation - Query'[CpuTimeMs] )"
            ],
            "formatString": "#,0",
            "lineageTag": "e8532c1f-7804-444c-a153-be139d4623ff"
          },
          {
            "name": "Duration - Suboperation - Query",
            "displayFolder": "Duration - Suboperation",
            "expression": [
              "",
              "SUM ( 'Suboperation - Query'[Duration (ms)] )"
            ],
            "formatString": "#,0",
            "lineageTag": "64e0ce89-2976-44ba-bb4c-7ce884e44625"
          },
          {
            "name": "Workspace_multiple",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              }
            ],
            "displayFolder": "Smart Narrative",
            "expression": [
              "",
              "VAR selectedrows =",
              "    COUNTROWS (",
              "        ALLSELECTED ( Operation[Workspace] )",
              "    )",
              "VAR noblankrows =",
              "    COUNTROWS (",
              "        ALLNOBLANKROW ( Operation[Workspace] )",
              "    )",
              "VAR allrows =",
              "    COUNTROWS (",
              "        ALL ( Operation[Workspace] )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISFILTERED ( Operation[Workspace] )",
              "            && HASONEFILTER ( Operation[Workspace] ),",
              "        SELECTEDVALUE ( Operation[Workspace] ),",
              "        IF (",
              "            OR (",
              "                selectedrows == noblankrows,",
              "                selectedrows == allrows",
              "            ),",
              "            \"All\",",
              "            IF (",
              "                COUNTA ( Operation[Workspace] ) > 1,",
              "                CONCATENATE (",
              "                    FIRSTNONBLANK (",
              "                        Operation[Workspace],",
              "                        ISFILTERED ( Operation[Workspace] )",
              "                    ),",
              "                    \" & more\"",
              "                ),",
              "                \"All\"",
              "            )",
              "        )",
              "    )"
            ],
            "lineageTag": "2aa1b96c-a932-4390-ba33-21365f7053b3"
          },
          {
            "name": "PremiumCapacity_multiple",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              }
            ],
            "displayFolder": "Smart Narrative",
            "expression": [
              "",
              "VAR selectedrows =",
              "    COUNTROWS (",
              "        ALLSELECTED ( Operation[PremiumCapacityId] )",
              "    )",
              "VAR noblankrows =",
              "    COUNTROWS (",
              "        ALLNOBLANKROW ( Operation[PremiumCapacityId] )",
              "    )",
              "VAR allrows =",
              "    COUNTROWS (",
              "        ALL ( Operation[PremiumCapacityId] )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISFILTERED ( Operation[PremiumCapacityId] )",
              "            && HASONEFILTER ( Operation[PremiumCapacityId] ),",
              "        SELECTEDVALUE ( Operation[PremiumCapacityId] ),",
              "        IF (",
              "            OR (",
              "                selectedrows == noblankrows,",
              "                selectedrows == allrows",
              "            ),",
              "            \"All\",",
              "            IF (",
              "                COUNTA ( Operation[PremiumCapacityId] ) > 1,",
              "                CONCATENATE (",
              "                    FIRSTNONBLANK (",
              "                        Operation[PremiumCapacityId],",
              "                        ISFILTERED ( Operation[PremiumCapacityId] )",
              "                    ),",
              "                    \" & more\"",
              "                ),",
              "                \"All\"",
              "            )",
              "        )",
              "    )"
            ],
            "lineageTag": "ca9b1315-7a9d-49a1-a825-5b9d8bcf3c50"
          },
          {
            "name": "DatasetMode_multiple",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              }
            ],
            "displayFolder": "Smart Narrative",
            "expression": [
              "",
              "VAR selectedrows =",
              "    COUNTROWS (",
              "        ALLSELECTED ( Operation[DatasetMode] )",
              "    )",
              "VAR noblankrows =",
              "    COUNTROWS (",
              "        ALLNOBLANKROW ( Operation[DatasetMode] )",
              "    )",
              "VAR allrows =",
              "    COUNTROWS (",
              "        ALL ( Operation[DatasetMode] )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISFILTERED ( Operation[DatasetMode] )",
              "            && HASONEFILTER ( Operation[DatasetMode] ),",
              "        SELECTEDVALUE ( Operation[DatasetMode] ),",
              "        IF (",
              "            OR (",
              "                selectedrows == noblankrows,",
              "                selectedrows == allrows",
              "            ),",
              "            \"All\",",
              "            IF (",
              "                COUNTA ( Operation[DatasetMode] ) > 1,",
              "                CONCATENATE (",
              "                    FIRSTNONBLANK (",
              "                        Operation[DatasetMode],",
              "                        ISFILTERED ( Operation[DatasetMode] )",
              "                    ),",
              "                    \" & more\"",
              "                ),",
              "                \"All\"",
              "            )",
              "        )",
              "    )"
            ],
            "lineageTag": "7d7f35f1-5760-422e-87e9-79948da5ab0a"
          },
          {
            "name": "ReportId_multiple",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              }
            ],
            "displayFolder": "Smart Narrative",
            "expression": [
              "",
              "VAR selectedrows =",
              "    COUNTROWS (",
              "        ALLSELECTED ( Operation[ReportId] )",
              "    )",
              "VAR noblankrows =",
              "    COUNTROWS (",
              "        ALLNOBLANKROW ( Operation[ReportId] )",
              "    )",
              "VAR allrows =",
              "    COUNTROWS (",
              "        ALL ( Operation[ReportId] )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISFILTERED ( Operation[ReportId] )",
              "            && HASONEFILTER ( Operation[ReportId] ),",
              "        SELECTEDVALUE ( Operation[ReportId] ),",
              "        IF (",
              "            OR (",
              "                selectedrows == noblankrows,",
              "                selectedrows == allrows",
              "            ),",
              "            \"All\",",
              "            IF (",
              "                COUNTA ( Operation[ReportId] ) > 1,",
              "                CONCATENATE (",
              "                    FIRSTNONBLANK (",
              "                        Operation[ReportId],",
              "                        ISFILTERED ( Operation[ReportId] )",
              "                    ),",
              "                    \" & more\"",
              "                ),",
              "                \"All\"",
              "            )",
              "        )",
              "    )"
            ],
            "lineageTag": "8be01d32-2d84-4e1e-a51b-58b693e1e449"
          },
          {
            "name": "User_multiple",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              }
            ],
            "displayFolder": "Smart Narrative",
            "expression": [
              "",
              "VAR selectedrows =",
              "    COUNTROWS (",
              "        ALLSELECTED ( Operation[Executing User] )",
              "    )",
              "VAR noblankrows =",
              "    COUNTROWS (",
              "        ALLNOBLANKROW (  Operation[Executing User])",
              "    )",
              "VAR allrows =",
              "    COUNTROWS (",
              "        ALL (  Operation[Executing User] )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISFILTERED (  Operation[Executing User] )",
              "            && HASONEFILTER (  Operation[Executing User] ),",
              "        SELECTEDVALUE ( Operation[Executing User]),",
              "        IF (",
              "            OR (",
              "                selectedrows == noblankrows,",
              "                selectedrows == allrows",
              "            ),",
              "            \"All\",",
              "            IF (",
              "                COUNTA (  Operation[Executing User] ) > 1,",
              "                CONCATENATE (",
              "                    FIRSTNONBLANK (",
              "                         Operation[Executing User],",
              "                        ISFILTERED (  Operation[Executing User] )",
              "                    ),",
              "                    \" & more\"",
              "                ),",
              "                \"All\"",
              "            )",
              "        )",
              "    )"
            ],
            "lineageTag": "bb528240-7a7c-468d-9a1e-f54a6056be27"
          },
          {
            "name": "Scenario_multiple",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "DisplayFolder"
              }
            ],
            "displayFolder": "Smart Narrative",
            "expression": [
              "",
              "VAR selectedrows =",
              "    COUNTROWS (",
              "        ALLSELECTED ( Operation[Scenario name] )",
              "    )",
              "VAR noblankrows =",
              "    COUNTROWS (",
              "        ALLNOBLANKROW ( Operation[Scenario name] )",
              "    )",
              "VAR allrows =",
              "    COUNTROWS (",
              "        ALL ( Operation[Scenario name] )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISFILTERED ( Operation[Scenario name] )",
              "            && HASONEFILTER ( Operation[Scenario name] ),",
              "        SELECTEDVALUE ( Operation[Scenario name] ),",
              "        IF (",
              "            OR (",
              "                selectedrows == noblankrows,",
              "                selectedrows == allrows",
              "            ),",
              "            \"All\",",
              "            IF (",
              "                COUNTA ( Operation[Scenario name] ) > 1,",
              "                CONCATENATE (",
              "                    FIRSTNONBLANK (",
              "                        Operation[Scenario name],",
              "                        ISFILTERED ( Operation[Scenario name] )",
              "                    ),",
              "                    \" & more\"",
              "                ),",
              "                \"All\"",
              "            )",
              "        )",
              "    )"
            ],
            "lineageTag": "b1726e48-df7c-4a92-b24d-405cbe7565e0"
          },
          {
            "name": "Object_multiple",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              }
            ],
            "displayFolder": "Smart Narrative",
            "expression": [
              "",
              "VAR selectedrows =",
              "    COUNTROWS (",
              "        ALLSELECTED ( 'Suboperation - Refresh'[ObjectTable + ObjectName] )",
              "    )",
              "VAR noblankrows =",
              "    COUNTROWS (",
              "        ALLNOBLANKROW ( 'Suboperation - Refresh'[ObjectTable + ObjectName] )",
              "    )",
              "VAR allrows =",
              "    COUNTROWS (",
              "        ALL ( 'Suboperation - Refresh'[ObjectTable + ObjectName] )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISFILTERED ( 'Suboperation - Refresh'[ObjectTable + ObjectName] )",
              "            && HASONEFILTER ( 'Suboperation - Refresh'[ObjectTable + ObjectName] ),",
              "        SELECTEDVALUE ( 'Suboperation - Refresh'[ObjectTable + ObjectName] ),",
              "        IF (",
              "            OR (",
              "                selectedrows == noblankrows,",
              "                selectedrows == allrows",
              "            ),",
              "            \"All\",",
              "            IF (",
              "                COUNTA ( 'Suboperation - Refresh'[ObjectTable + ObjectName] ) > 1,",
              "                CONCATENATE (",
              "                    FIRSTNONBLANK (",
              "                        'Suboperation - Refresh'[ObjectTable + ObjectName],",
              "                        ISFILTERED ( 'Suboperation - Refresh'[ObjectTable + ObjectName] )",
              "                    ),",
              "                    \" & more\"",
              "                ),",
              "                \"All\"",
              "            )",
              "        )",
              "    )"
            ],
            "lineageTag": "789f96fa-eb1e-4b6a-b82c-4cab21587813"
          },
          {
            "name": "Detail_multiple",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              }
            ],
            "displayFolder": "Smart Narrative",
            "expression": [
              "",
              "VAR selectedrows =",
              "    COUNTROWS (",
              "        ALLSELECTED ( 'Suboperation - Refresh'[Operation Detail] )",
              "    )",
              "VAR noblankrows =",
              "    COUNTROWS (",
              "        ALLNOBLANKROW ( 'Suboperation - Refresh'[Operation Detail] )",
              "    )",
              "VAR allrows =",
              "    COUNTROWS (",
              "        ALL ( 'Suboperation - Refresh'[Operation Detail] )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISFILTERED ( 'Suboperation - Refresh'[Operation Detail] )",
              "            && HASONEFILTER ( 'Suboperation - Refresh'[Operation Detail] ),",
              "        SELECTEDVALUE ( 'Suboperation - Refresh'[Operation Detail] ),",
              "        IF (",
              "            OR (",
              "                selectedrows == noblankrows,",
              "                selectedrows == allrows",
              "            ),",
              "            \"All\",",
              "            IF (",
              "                COUNTA ( 'Suboperation - Refresh'[Operation Detail] ) > 1,",
              "                CONCATENATE (",
              "                    FIRSTNONBLANK (",
              "                        'Suboperation - Refresh'[Operation Detail],",
              "                        ISFILTERED ( 'Suboperation - Refresh'[Operation Detail] )",
              "                    ),",
              "                    \" & more\"",
              "                ),",
              "                \"All\"",
              "            )",
              "        )",
              "    )"
            ],
            "lineageTag": "ff15b637-d107-40fd-8fbe-34326afdbfdd"
          },
          {
            "name": "Timeline Visualization Duration Per Column",
            "expression": [
              "",
              "VAR RangeStart =",
              "    CALCULATE (",
              "        FIRSTNONBLANK (",
              "            Operation[Start Date/Time],",
              "            TRUE ()",
              "        ),",
              "        ALLSELECTED ( Operation )",
              "    ) //CONVERT(MIN(Operation[Start Date/Time]), DOUBLE) * 1000",
              "VAR RangeEnd =",
              "    CALCULATE (",
              "        MAX ( Operation[End Date/Time] ),",
              "        ALLSELECTED ( Operation )",
              "    ) //CONVERT(MAX(Operation[End Date/Time]), DOUBLE) * 1000",
              "VAR _numberOfColumnsInMatrix =",
              "    CALCULATE (",
              "        COUNTROWS ( 'Timeline Visual Columns' ),",
              "        REMOVEFILTERS ()",
              "    ) // How many columns will the matrix visual have? ",
              "VAR TimeSliceSeconds =",
              "    DIVIDE (",
              "        DATEDIFF (",
              "            RangeStart,",
              "            RangeEnd,",
              "            SECOND",
              "        ),",
              "        _numberOfColumnsInMatrix",
              "    )",
              "VAR DurationType =",
              "    SWITCH (",
              "        TRUE (),",
              "        TimeSliceSeconds <= 60,",
              "            FORMAT (",
              "                TimeSliceSeconds,",
              "                \"#.## \" & \"Seconds\"",
              "            ),",
              "        TimeSliceSeconds <= 3600",
              "            && TimeSliceSeconds > 60,",
              "            FORMAT (",
              "                TimeSliceSeconds / 60,",
              "                \"#.## \" & \"Minutes\"",
              "            ),",
              "        TimeSliceSeconds <= 7200",
              "            && TimeSliceSeconds > 3600,",
              "            FORMAT (",
              "                TimeSliceSeconds / 60 / 60,",
              "                \"#.## \" & \"Hours\"",
              "            ),",
              "        TimeSliceSeconds > 7200,",
              "            FORMAT (",
              "                TimeSliceSeconds / 60 / 60 / 24,",
              "                \"#.## \" & \"Days\"",
              "            )",
              "    )",
              "RETURN",
              "    DurationType"
            ],
            "lineageTag": "6a1a1f6a-6251-4f8b-aa85-cf595aac80fc"
          },
          {
            "name": "Timeline Visualization Value",
            "expression": [
              "",
              "// This is the measure for the Value field of the timeline matrix. It takes the total duration (first start -> last end) in scope and divides it by the number of columns",
              "// in the matrix. That is the duration that each cell in the matrix represents. It then determies whether each cell should be painted (1 or 0) depending on whether the event's duration falls within the timeframe that the cell represents.",
              "VAR RangeStart =",
              "    CALCULATE (",
              "        FIRSTNONBLANK (",
              "            Operation[Start Date/Time],",
              "            TRUE ()",
              "        ),",
              "        ALLEXCEPT (",
              "            Operation,",
              "            Operation[Start Date]",
              "        )",
              "    )",
              "VAR RangeEnd =",
              "    CALCULATE (",
              "        MAX ( Operation[End Date/Time] ),",
              "        ALLEXCEPT (",
              "            Operation,",
              "            Operation[Start Date]",
              "        )",
              "    )",
              "VAR _numberOfColumnsInMatrix =",
              "    CALCULATE (",
              "        COUNTROWS ( 'Timeline Visual Columns' ),",
              "        REMOVEFILTERS ()",
              "    ) // How many columns will the matrix visual have? ",
              "VAR TimeSliceSeconds =",
              "    DIVIDE (",
              "        DATEDIFF (",
              "            RangeStart,",
              "            RangeEnd,",
              "            SECOND",
              "        ),",
              "        _numberOfColumnsInMatrix",
              "    )",
              "VAR CurrentSlice =",
              "    MAX ( 'Timeline Visual Columns'[Time Slice] )",
              "VAR CurrentColumnMin = RangeStart + ( CurrentSlice - 1 ) * TimeSliceSeconds / ( 60 * 60 * 24 )",
              "VAR CurrentColumnMax = RangeStart + CurrentSlice * TimeSliceSeconds / ( 60 * 60 * 24 )",
              "RETURN",
              "    IF (",
              "        AND (",
              "            MIN ( Operation[Start Date/Time] ) >= CurrentColumnMin,",
              "            MIN ( Operation[End Date/Time] ) <= CurrentColumnMax",
              "        ),",
              "        1,",
              "        0",
              "    )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "beba0ade-499e-4dc8-aa83-50233b16ef2a"
          },
          {
            "name": "Timeline Visualization Duration Per Col",
            "expression": [
              "",
              "VAR RangeStart =",
              "    CALCULATE (",
              "        FIRSTNONBLANK (",
              "            'Suboperation - Refresh'[Start Date/Time],",
              "            TRUE ()",
              "        ),",
              "        ALLSELECTED ( 'Suboperation - Refresh' )",
              "    ) //CONVERT(MIN('Suboperation - Refresh'[Start Date/Time]), DOUBLE) * 1000",
              "VAR RangeEnd =",
              "    CALCULATE (",
              "        MAX ( 'Suboperation - Refresh'[End Date/Time] ),",
              "        ALLSELECTED ( 'Suboperation - Refresh' )",
              "    ) //CONVERT(MAX('Suboperation - Refresh'[End Date/Time]), DOUBLE) * 1000",
              "VAR _numberOfColumnsInMatrix =",
              "    CALCULATE (",
              "        COUNTROWS ( 'Timeline Visual Columns' ),",
              "        REMOVEFILTERS ()",
              "    ) // How many columns will the matrix visual have? ",
              "VAR TimeSliceSeconds =",
              "    DIVIDE (",
              "        DATEDIFF (",
              "            RangeStart,",
              "            RangeEnd,",
              "            SECOND",
              "        ),",
              "        _numberOfColumnsInMatrix",
              "    )",
              "VAR DurationType =",
              "    SWITCH (",
              "        TRUE (),",
              "        TimeSliceSeconds <= 0,",
              "            FORMAT (",
              "                TimeSliceSeconds,",
              "                \"#.### \" & \"miliSeconds\"",
              "            ),",
              "        TimeSliceSeconds <= 60",
              "            && TimeSliceSeconds > 0,",
              "            FORMAT (",
              "                TimeSliceSeconds,",
              "                \"#.### \" & \"Seconds\"",
              "            ),",
              "        TimeSliceSeconds <= 3600",
              "            && TimeSliceSeconds > 60,",
              "            FORMAT (",
              "                TimeSliceSeconds / 60,",
              "                \"#.### \" & \"Minutes\"",
              "            ),",
              "        TimeSliceSeconds <= 7200",
              "            && TimeSliceSeconds > 3600,",
              "            FORMAT (",
              "                TimeSliceSeconds / 60 / 60,",
              "                \"#.### \" & \"Hours\"",
              "            ),",
              "        TimeSliceSeconds > 7200,",
              "            FORMAT (",
              "                TimeSliceSeconds / 60 / 60 / 24,",
              "                \"#.## \" & \"Days\"",
              "            )",
              "    )",
              "RETURN",
              "    DurationType"
            ],
            "lineageTag": "c02ef1f0-1c64-4c13-98a8-5bfcafdd2a7a"
          },
          {
            "name": "Timeline Visualization Val",
            "expression": [
              "",
              "// This is the measure for the Value field of the timeline matrix. It takes the total duration (first start -> last end) in scope and divides it by the number of columns",
              "// in the matrix. That is the duration that each cell in the matrix represents. It then determies whether each cell should be painted (1 or 0) depending on whether the event's duration falls within the timeframe that the cell represents.",
              "VAR RangeStart =",
              "    CALCULATE (",
              "        FIRSTNONBLANK (",
              "            'Suboperation - Refresh'[Start Date/Time],",
              "            TRUE ()",
              "        ),",
              "        ALLSELECTED ( 'Suboperation - Refresh' )",
              "    )",
              "VAR RangeEnd =",
              "    CALCULATE (",
              "        MAX ( 'Suboperation - Refresh'[End Date/Time] ),",
              "        ALLSELECTED ( 'Suboperation - Refresh' )",
              "    )",
              "VAR _numberOfColumnsInMatrix =",
              "    CALCULATE (",
              "        COUNTROWS ( 'Timeline Visual Columns' ),",
              "        REMOVEFILTERS ()",
              "    ) // How many columns will the matrix visual have? ",
              "VAR TimeSliceSeconds =",
              "    DIVIDE (",
              "        DATEDIFF (",
              "            RangeStart,",
              "            RangeEnd,",
              "            SECOND",
              "        ),",
              "        _numberOfColumnsInMatrix",
              "    )",
              "VAR CurrentSlice =",
              "    MAX ( 'Timeline Visual Columns'[Time Slice] )",
              "VAR CurrentColumnMin = RangeStart + ( CurrentSlice - 1 ) * TimeSliceSeconds / ( 60 * 60 * 24 )",
              "VAR CurrentColumnMax = RangeStart + CurrentSlice * TimeSliceSeconds / ( 60 * 60 * 24 )",
              "RETURN",
              "    IF (",
              "        AND (",
              "            MIN ( 'Suboperation - Refresh'[Start Date/Time] ) <= CurrentColumnMax,",
              "            MIN ( 'Suboperation - Refresh'[End Date/Time] ) >= CurrentColumnMin",
              "        ),",
              "        1,",
              "        0",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "5eab81ed-2e75-4300-b826-296c30fc3db5"
          },
          {
            "name": "DurationWithAgg",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              }
            ],
            "displayFolder": "Duration - Operation",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'Operation'[Duration (ms)] ),",
              "    'Operation'[IsAggregationUsed] == \"Yes\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4691cbef-9107-4c9b-aed4-49009bd267d6"
          },
          {
            "name": "DurationY",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( Operation[Duration (ms)] ),",
              "    Operation[IsAggregationUsed] = \"Yes\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1a0363d4-b699-494e-9996-25e00be6dc72"
          },
          {
            "name": "DurationN",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( Operation[Duration (ms)] ),",
              "    Operation[IsAggregationUsed] = \"No\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "9c6c54a8-b01e-473d-ac39-9f0a23f9e022"
          },
          {
            "name": "CPUTimeY",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( Operation[CPUTime (ms)] ),",
              "    Operation[IsAggregationUsed] = \"Yes\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "93457fc7-9ac2-46c4-8582-3fec1b94acf7"
          },
          {
            "name": "CPUTimeN",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( Operation[CPUTime (ms)] ),",
              "    Operation[IsAggregationUsed] = \"No\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "29ca706c-7fc0-47b8-8b4c-47d97c27f039"
          },
          {
            "name": "AggregationHit%",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR percentage= CALCULATE (",
              "                            COUNT ( Operation[XmlaRequestId] ),Operation[IsAggregationUsed] = \"Yes\")",
              "                / COUNT ( Operation[XmlaRequestId] )",
              "return",
              "IF(percentage>0,percentage,0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "21130961-c4e4-4e3d-8b47-c707923de958"
          },
          {
            "name": "CPUTimeWithAgg",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              }
            ],
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'Operation'[CPUTime (ms)] ),",
              "    Operation[IsAggregationUsed] = \"Yes\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f5a0eabb-d5cf-49c0-b46e-c7dd792ab61e"
          },
          {
            "name": "Gantt value",
            "expression": [
              "",
              "VAR MinCalendar = MIN('Calendar'[Date])",
              "VAR MaxCalendar = MAX('Calendar'[Date])+1",
              "RETURN",
              "IF( (",
              "MIN(Operation[Start Date/Time]) >= MinCalendar && MAX(Operation[Start Date/Time]) < MaxCalendar),[Timeline Visualization Value],BLANK())"
            ],
            "formatString": "0",
            "lineageTag": "22a4487b-9ff4-42c3-868b-2cb6b8b28c1c"
          },
          {
            "name": "Weekly active users",
            "displayFolder": "Count",
            "expression": [
              "",
              "CALCULATE([User count], DATESINPERIOD('Calendar'[Date], max('Calendar'[Date]), -30, DAY)) +0"
            ],
            "formatString": "0",
            "lineageTag": "332bd3f3-7175-4d31-9d9c-3f6a844a9ada"
          },
          {
            "name": "Gantt timeline refreshes",
            "expression": [
              "",
              "// This is the measure for the Value field of the timeline matrix. It takes the total duration (first start -> last end) in scope and divides it by the number of columns",
              "// in the matrix. That is the duration that each cell in the matrix represents. It then determies whether each cell should be painted (1 or 0) depending on whether the event's duration falls within the timeframe that the cell represents.",
              "VAR RangeStart =",
              "    CALCULATE (",
              "        FIRSTNONBLANK ( Operation[Start Date/Time], TRUE () ),",
              "        ALLEXCEPT ( Operation, Operation[Start Date] )",
              "    )",
              "VAR RangeEnd =",
              "    CALCULATE (",
              "        MAX ( Operation[End Date/Time] ),",
              "        ALLEXCEPT ( Operation, Operation[Start Date] )",
              "    )",
              "VAR _numberOfColumnsInMatrix =100",
              "    //CALCULATE ( COUNTROWS ( 'Timeline Visual Columns' ), REMOVEFILTERS () ) // How many columns will the matrix visual have? ",
              "VAR TimeSliceSeconds =",
              "    DIVIDE ( DATEDIFF ( RangeStart, RangeEnd, SECOND ), _numberOfColumnsInMatrix )",
              "VAR CurrentSlice =",
              "    MAX ( 'Timeline Visual Columns'[Time Slice] )",
              "VAR CurrentColumnMin = RangeStart + ( CurrentSlice - 1 ) * TimeSliceSeconds / (86400 )",
              "VAR CurrentColumnMax = RangeStart + CurrentSlice * TimeSliceSeconds / ( 86400 )",
              "VAR Table1 =",
              "    CALCULATE (",
              "        COUNTROWS ( Operation ),",
              "        Operation[Start Date/Time] <= CurrentColumnMax,",
              "        Operation[End Date/Time] >= CurrentColumnMin",
              "    )",
              "RETURN",
              "    IF ( ISBLANK ( Table1 ), 0, Table1 )"
            ],
            "formatString": "0",
            "lineageTag": "ba52c0be-7d45-430e-aa81-c63cdb9178e2"
          },
          {
            "name": "Date Interval",
            "expression": [
              "",
              "FORMAT (",
              "    CALCULATE (",
              "        INT (",
              "            DATEDIFF (",
              "                MIN ( 'Calendar'[Date (no year)] ),",
              "                'Report Measures'[Date Mid Interval],",
              "                DAY",
              "            ) / 2",
              "        )",
              "            + MIN ( 'Calendar'[Date (no year)] )",
              "    ),",
              "    \"dd mmm\"",
              ")"
            ],
            "lineageTag": "f603397a-a3cc-4596-adf8-2af8755bb263"
          },
          {
            "name": "Date Mid Interval",
            "expression": [
              "",
              "FORMAT (",
              "    CALCULATE (",
              "        DATEDIFF (",
              "            MIN ( 'Calendar'[Date (no year)] ),",
              "            MAX ( 'Calendar'[Date (no year)] ),",
              "            DAY",
              "        ) / 2",
              "            + MIN ( 'Calendar'[Date (no year)] )",
              "    ),",
              "    \"dd mmm\"",
              ")"
            ],
            "lineageTag": "2faa4162-d78e-44c6-acee-c33163713b96"
          },
          {
            "name": "Date Interval 3",
            "expression": [
              "",
              "FORMAT (",
              "    CALCULATE (",
              "        INT (",
              "            DATEDIFF (",
              "                'Report Measures'[Date Mid Interval],",
              "                MAX ( 'Calendar'[Date (no year)] ),",
              "                DAY",
              "            ) / 2",
              "        ) + 'Report Measures'[Date Mid Interval]",
              "    ),",
              "    \"dd mmm\"",
              ")"
            ],
            "lineageTag": "44e9217f-33f4-47f6-bce1-899ecd9956e1"
          },
          {
            "name": "Duration (minutes)",
            "expression": "INT(DIVIDE([Duration (ms)], 60000))",
            "formatString": "0",
            "lineageTag": "9c84ecb8-b0e8-432c-92d9-d28a21dc3ce5"
          },
          {
            "name": "Gantt timeline refreshes detail",
            "expression": [
              "",
              "// This is the measure for the Value field of the timeline matrix. It takes the total duration (first start -> last end) in scope and divides it by the number of columns",
              "// in the matrix. That is the duration that each cell in the matrix represents. It then determies whether each cell should be painted (1 or 0) depending on whether the event's duration falls within the timeframe that the cell represents.",
              "VAR RangeStart =",
              "    CALCULATE (",
              "        FIRSTNONBLANK ( 'Suboperation - Refresh'[Start Date/Time], TRUE () ),",
              "        // ALLSELECTED ( 'Suboperation - Refresh' )",
              "        ALLEXCEPT( 'Suboperation - Refresh', 'Suboperation - Refresh'[Start Date], 'Suboperation - Refresh'[XmlaRequestId],Operation[XmlaRequestId])",
              "    )",
              "VAR RangeEnd =",
              "    CALCULATE (",
              "        MAX ( 'Suboperation - Refresh'[End Date/Time] ),",
              "        // ALLSELECTED ( 'Suboperation - Refresh' )",
              "        ALLEXCEPT( 'Suboperation - Refresh', 'Suboperation - Refresh'[Start Date], 'Suboperation - Refresh'[XmlaRequestId],Operation[XmlaRequestId])",
              "    )",
              "VAR _numberOfColumnsInMatrix =100",
              "    //CALCULATE ( COUNTROWS ( 'Timeline Visual Columns' ), REMOVEFILTERS () ) // How many columns will the matrix visual have? ",
              "VAR TimeSliceSeconds =",
              "    DIVIDE ( DATEDIFF ( RangeStart, RangeEnd, SECOND ), _numberOfColumnsInMatrix )",
              "VAR CurrentSlice =",
              "    MAX ( 'Timeline Visual Columns'[Time Slice] )",
              "VAR CurrentColumnMin = RangeStart + ( CurrentSlice - 1 ) * TimeSliceSeconds / ( 86400 )",
              "VAR CurrentColumnMax = RangeStart + CurrentSlice * TimeSliceSeconds / ( 86400)",
              "VAR Table1 =",
              "    CALCULATE (",
              "        COUNTROWS ( 'Suboperation - Refresh' ),",
              "        'Suboperation - Refresh'[Start Date/Time] <= CurrentColumnMax,",
              "        'Suboperation - Refresh'[End Date/Time] >= CurrentColumnMin",
              "    )",
              "RETURN",
              "    IF ( ISBLANK ( Table1 ), BLANK(), Table1 )"
            ],
            "formatString": "0",
            "lineageTag": "8dc99a9a-4936-4c6a-b0d5-c62906351289"
          },
          {
            "name": "Avg CPU Time - Query",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CPU Time - Operation",
            "expression": [
              "",
              "// For DAX QueryEnds, CPU Time is calculated by adding the CPU Time of all VertiPaqSEQueryEnd suboperations to the CPU Time of the QueryEnd operation.",
              "// For DirectQuery queries, CPU Time is simply the QueryEnd CPU Time.",
              "VAR QueryEndSum =",
              "    CALCULATE (",
              "        AVERAGE( 'Operation'[CPUTime (ms)] ),",
              "        'Operation'[Operation] = \"QueryEnd\"",
              "    )",
              "VAR isDQ =",
              "    CALCULATE (",
              "        COUNTROWS (",
              "            VALUES ( 'Suboperation - Refresh'[Operation Detail] )",
              "        ),",
              "        'Suboperation - Refresh'[Operation Detail] = \"VertiPaqSEQueryEnd\"",
              "    )",
              "VAR CPUTimeSE = ",
              "// Storage Engine",
              "// https://github.com/DaxStudio/DaxStudio/blob/3cf6ef12dae03dcd06369e4248774068359fee7b/src/DaxStudio.UI/ViewModels/ServerTimesViewModel.cs#L287",
              "CALCULATE(",
              "        AVERAGE( 'Suboperation - Query'[CpuTimeMs] ),",
              "        'Suboperation - Query'[Operation] IN ({\"VertiPaqSEQueryEnd\", \"DirectQueryEnd\"})",
              ")",
              "RETURN",
              "    IF (",
              "        isDQ,",
              "        QueryEndSum,",
              "        QueryEndSum + CPUTimeSE",
              "    )",
              ""
            ],
            "lineageTag": "faba84f4-5e20-496e-94a3-56ce80a2842a"
          },
          {
            "name": "Query Detail. Queries",
            "expression": [
              "",
              "\"Query details (\"",
              "    & FORMAT (",
              "        [Queries],",
              "        \"#,##0\"",
              "    ) & \")\""
            ],
            "lineageTag": "1b86f2c6-3206-489a-83bf-6b784656756e"
          },
          {
            "name": "CPU Time (s) Total",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Count",
            "expression": "DIVIDE([CPU Time (ms) Total],1000)",
            "formatString": "0.00",
            "lineageTag": "b474226f-543f-4dbf-b7e9-c1f9511839e0"
          },
          {
            "name": "Refresh - failure",
            "displayFolder": "Count",
            "expression": [
              "",
              "CALCULATE (",
              "    [Refreshes],",
              "    Operation[StatusCode] <> 0",
              ")",
              "",
              "// 0 = success, non-zero (usually negative) = failure"
            ],
            "formatString": "0",
            "lineageTag": "9978c8f2-f117-4cb9-903e-091593d6f47a"
          },
          {
            "name": "Refresh - success",
            "displayFolder": "Count",
            "expression": [
              "",
              "CALCULATE (",
              "    [Refreshes],",
              "    Operation[StatusCode] = 0",
              ")",
              "// 0 = success, non-zero (usually negative) = failure"
            ],
            "formatString": "0",
            "lineageTag": "84e36d09-2790-43df-a3fb-0cc5cc4ef931"
          },
          {
            "name": "Refresh - failure rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Count",
            "expression": [
              "",
              "VAR failiures = [Refresh - failure]",
              "RETURN",
              "    DIVIDE (",
              "        failiures,",
              "        [Refresh - success] + failiures",
              "    )"
            ],
            "lineageTag": "6b10e6cc-dc57-4db6-bc26-39dfb8040f35"
          },
          {
            "name": "Query failure(card)",
            "displayFolder": "Count",
            "expression": "[Query - failure]+0",
            "formatString": "0",
            "lineageTag": "cd9a6f10-a8fb-41b7-8c91-ed034b53256c"
          },
          {
            "name": "Reason",
            "expression": "CALCULATE(MIN(Operation[EventText]),Operation[Operation]=\"Error\",ALL(Operation[EventText]))",
            "lineageTag": "a76e9308-62b1-4a57-a731-9b0d8811c60e"
          },
          {
            "name": "Refresh failure(card)",
            "displayFolder": "Count",
            "expression": "[Refresh - failure]+0",
            "formatString": "0",
            "lineageTag": "ce8f428f-861f-4b67-aeb4-8ac39b43f530"
          },
          {
            "name": "Total Error",
            "displayFolder": "Count",
            "expression": "CALCULATE(COUNTROWS(Operation),Operation[Status] == \"Failed\",Operation[Operation]<>\"Error\")",
            "formatString": "0",
            "lineageTag": "29bb23ec-bc86-4144-b2d1-0d9f1ead16a1"
          },
          {
            "name": "Total query duration",
            "expression": "[Queries] * [Duration (ms)]",
            "formatString": "0",
            "lineageTag": "caada502-fb6c-4cfc-912a-6966edf3f9f9"
          },
          {
            "name": "User count (card)",
            "expression": [
              "",
              "DISTINCTCOUNT (Operation[Executing User] )+0"
            ],
            "formatString": "0",
            "lineageTag": "d2f10707-f6c7-47b2-9743-c67e01b186d1"
          },
          {
            "name": "TopN_ReportTitle",
            "expression": "\"Top \" & SELECTEDVALUE ( 'Top N Selector'[SelectorSort] ) & \" reports with high CPU usage\"",
            "lineageTag": "0a71a689-ad01-45c6-bc0e-1f0a9f91e515"
          },
          {
            "name": "TopN_UserTitle",
            "expression": "\"Top \" & SELECTEDVALUE ( 'Top N Selector'[SelectorSort] ) & \" users with high CPU usage\"",
            "lineageTag": "f07b0271-4e8a-4cb6-a963-99e65659ddc0"
          },
          {
            "name": "TopN_OperationsTitle",
            "expression": "\"Top \" & SELECTEDVALUE ( 'Top N Selector'[SelectorSort] ) & \" users by operation\"",
            "lineageTag": "22c4231f-cf80-43b1-b2fe-97d01c73db99"
          },
          {
            "name": "TopN_QueriesTitle",
            "expression": "\"Top \" & SELECTEDVALUE ( 'Top N Selector'[SelectorSort] ) & \" users by query execution\"",
            "lineageTag": "51a05d17-9e9b-47c6-b1a6-4b9dcb5e9839"
          },
          {
            "name": "Dataset_multiple",
            "expression": [
              "",
              "VAR selectedrows =",
              "    COUNTROWS (",
              "        ALLSELECTED ( Operation[Dataset] )",
              "    )",
              "VAR noblankrows =",
              "    COUNTROWS (",
              "        ALLNOBLANKROW ( Operation[Dataset] )",
              "    )",
              "VAR allrows =",
              "    COUNTROWS (",
              "        ALL ( Operation[Dataset] )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISFILTERED ( Operation[Dataset] )",
              "            && HASONEFILTER ( Operation[Dataset] ),",
              "        SELECTEDVALUE ( Operation[Dataset] ),",
              "        IF (",
              "            OR (",
              "                selectedrows == noblankrows,",
              "                selectedrows == allrows",
              "            ),",
              "            \"All\",",
              "            IF (",
              "                COUNTA ( Operation[Dataset] ) > 1,",
              "                CONCATENATE (",
              "                    FIRSTNONBLANK (",
              "                        Operation[Dataset],",
              "                        ISFILTERED ( Operation[Dataset] )",
              "                    ),",
              "                    \" & more\"",
              "                ),",
              "                \"All\"",
              "            )",
              "        )",
              "    )"
            ],
            "lineageTag": "b6d4d458-95c3-4ea0-9c1c-97c854e249af"
          }
        ],
        "partitions": [
          {
            "name": "Report Measures-740adfb2-5ab6-4f52-a806-24f38d21026f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Time",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Time (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "h:nn:ss AM/PM",
            "lineageTag": "f82b9cf4-910c-4625-af89-220634b4a3af",
            "sourceColumn": "Time (s)",
            "summarizeBy": "none"
          },
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60785a4d-fb5f-4804-aabe-f061c3deffbb",
            "sourceColumn": "Hour",
            "summarizeBy": "none"
          },
          {
            "name": "Time (m)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "h:nn AM/PM",
            "lineageTag": "0eb032d4-a1df-44ec-bade-7a44adc6578f",
            "sourceColumn": "Time (m)",
            "summarizeBy": "none"
          },
          {
            "name": "Minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03756e26-c78d-4bb8-b552-956a831896fd",
            "sourceColumn": "Minute",
            "summarizeBy": "none"
          },
          {
            "name": "Second",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "6fb21226-ed13-46d1-b419-1c7b4c6ceea6",
            "sourceColumn": "Second",
            "summarizeBy": "none"
          },
          {
            "name": "AM/PM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c47a6717-facb-4df3-86bc-12631cf9ce20",
            "sourceColumn": "AM/PM",
            "summarizeBy": "none"
          },
          {
            "name": "Hour Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2052e761-55e3-4e2e-b772-e775f1221332",
            "sourceColumn": "Hour Label",
            "summarizeBy": "none"
          },
          {
            "name": "Minute Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24a38bbe-9805-48c3-bc91-1785e8f0ba87",
            "sourceColumn": "Minute Label",
            "summarizeBy": "none"
          },
          {
            "name": "Second Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05b8bb79-7b69-4800-a9be-aeabb3e42451",
            "sourceColumn": "Second Label",
            "summarizeBy": "none"
          },
          {
            "name": "Hour Bin 12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "31f73f8b-f276-43bf-87c1-532f3a0aae01",
            "sourceColumn": "Hour Bin 12",
            "summarizeBy": "none"
          },
          {
            "name": "Hour Bin 8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f140ba7-27aa-4d06-ac8a-1860118d4289",
            "sourceColumn": "Hour Bin 8",
            "summarizeBy": "none"
          },
          {
            "name": "Hour Bin 6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a42c87dc-defd-4e97-8042-0b15ed143cf8",
            "sourceColumn": "Hour Bin 6",
            "summarizeBy": "none"
          },
          {
            "name": "Hour Bin 4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2b71f178-4ef9-4504-8599-95ad660aff66",
            "sourceColumn": "Hour Bin 4",
            "summarizeBy": "none"
          },
          {
            "name": "Hour Bin 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8b52303-dbae-4bc2-8af9-4986f0023f20",
            "sourceColumn": "Hour Bin 3",
            "summarizeBy": "none"
          },
          {
            "name": "Hour Bin 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7164fe95-a8e3-4945-ac41-ce598ef6a67c",
            "sourceColumn": "Hour Bin 2",
            "summarizeBy": "none"
          },
          {
            "name": "Minute Bin 30",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "37b36a4f-5420-4972-a38d-2f5ce8258a88",
            "sourceColumn": "Minute Bin 30",
            "summarizeBy": "none"
          },
          {
            "name": "Minute Bin 15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "92956cbc-4df6-4d71-b722-0fa5c555dd24",
            "sourceColumn": "Minute Bin 15",
            "summarizeBy": "none"
          },
          {
            "name": "Minute Bin 10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "9033d940-faa4-4738-b884-825e82206422",
            "sourceColumn": "Minute Bin 10",
            "summarizeBy": "none"
          },
          {
            "name": "Time (h)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "11308555-28f1-48e7-aad8-f7e8a3a86ed4",
            "sourceColumn": "Time (h)",
            "summarizeBy": "none"
          },
          {
            "name": "Hour(AM/PM)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "'Time'[Time (h)]"
            ],
            "formatString": "h:nn AM/PM",
            "isDataTypeInferred": true,
            "lineageTag": "61ddb53f-9f34-47a7-8a35-19efbbf29061",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "1be44b05-4b13-4b9b-9a06-5a032cc27a71",
        "partitions": [
          {
            "name": "Time-48902f46-1ec0-4676-9fae-2fc7c0c13030",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = List.Times(#time(0,0,0),24*60*60,#duration(0,0,0,1)),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Time\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Time\", type time}}),",
                "    #\"Added Time (h)\" = Table.AddColumn(#\"Changed Type\", \"Time (h)\", each #time(Time.Hour([Time]),0 ,0) as time),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Time (h)\",{{\"Time (h)\", type time}}),",
                "    #\"Added Time (m)\" = Table.AddColumn(#\"Changed Type2\", \"Time (m)\", each #time(Time.Hour([Time]),Time.Minute([Time]),0) as time),",
                "    #\"Changed Type Time (m)\" = Table.TransformColumnTypes(#\"Added Time (m)\",{{\"Time (m)\", type time}}),",
                "    #\"Inserted Hour\" = Table.AddColumn(#\"Changed Type Time (m)\", \"Hour\", each Time.Hour([Time]), Int64.Type),",
                "    #\"Inserted Minute\" = Table.AddColumn(#\"Inserted Hour\", \"Minute\", each Time.Minute([Time]), Int64.Type),",
                "    #\"Inserted Second\" = Table.AddColumn(#\"Inserted Minute\", \"Second\", each Time.Second([Time]), type number),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Inserted Second\", \"AM/PM\", each if [Hour] < 12 then \"AM\" else \"PM\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"AM/PM\", type text}}),",
                "    #\"Inserted Prefix\" = Table.AddColumn(#\"Changed Type1\", \"Prefix\", each \"0\" & Text.From([Hour], \"en-NZ\"), type text),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Prefix\",{{\"Prefix\", \"Hour Label\"}}),",
                "    #\"Extracted Last Characters\" = Table.TransformColumns(#\"Renamed Columns2\", {{\"Hour Label\", each Text.End(_, 2), type text}}),",
                "    #\"Inserted Prefix1\" = Table.AddColumn(#\"Extracted Last Characters\", \"Prefix\", each \"0\" & Text.From([Minute], \"en-NZ\"), type text),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Inserted Prefix1\",{{\"Prefix\", \"Minute Label\"}}),",
                "    #\"Extracted Last Characters1\" = Table.TransformColumns(#\"Renamed Columns3\", {{\"Minute Label\", each Text.End(_, 2), type text}}),",
                "    #\"Inserted Prefix2\" = Table.AddColumn(#\"Extracted Last Characters1\", \"Prefix\", each \"0\" & Text.From([Second], \"en-NZ\"), type text),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Inserted Prefix2\",{{\"Prefix\", \"Second Label\"}}),",
                "    #\"Extracted Last Characters2\" = Table.TransformColumns(#\"Renamed Columns4\", {{\"Second Label\", each Text.End(_, 2), type text}}),",
                "    #\"Inserted Modulo\" = Table.AddColumn(#\"Extracted Last Characters2\", \"Modulo\", each Number.Mod([Hour], 12), type number),",
                "    #\"Renamed Columns6\" = Table.RenameColumns(#\"Inserted Modulo\",{{\"Modulo\", \"Hour Bin 12\"}}),",
                "    #\"Inserted Integer-Division\" = Table.AddColumn(#\"Renamed Columns6\", \"Integer-Division\", each Number.IntegerDivide([Hour], 8), Int64.Type),",
                "    #\"Renamed Columns7\" = Table.RenameColumns(#\"Inserted Integer-Division\",{{\"Integer-Division\", \"Hour Bin 8\"}}),",
                "    #\"Inserted Integer-Division1\" = Table.AddColumn(#\"Renamed Columns7\", \"Integer-Division\", each Number.IntegerDivide([Hour], 6), Int64.Type),",
                "    #\"Renamed Columns8\" = Table.RenameColumns(#\"Inserted Integer-Division1\",{{\"Integer-Division\", \"Hour Bin 6\"}}),",
                "    #\"Inserted Integer-Division2\" = Table.AddColumn(#\"Renamed Columns8\", \"Integer-Division\", each Number.IntegerDivide([Hour], 4), Int64.Type),",
                "    #\"Renamed Columns9\" = Table.RenameColumns(#\"Inserted Integer-Division2\",{{\"Integer-Division\", \"Hour Bin 4\"}}),",
                "    #\"Inserted Integer-Division3\" = Table.AddColumn(#\"Renamed Columns9\", \"Integer-Division\", each Number.IntegerDivide([Hour], 3), Int64.Type),",
                "    #\"Renamed Columns10\" = Table.RenameColumns(#\"Inserted Integer-Division3\",{{\"Integer-Division\", \"Hour Bin 3\"}}),",
                "    #\"Inserted Integer-Division4\" = Table.AddColumn(#\"Renamed Columns10\", \"Integer-Division\", each Number.IntegerDivide([Hour], 2), Int64.Type),",
                "    #\"Renamed Columns11\" = Table.RenameColumns(#\"Inserted Integer-Division4\",{{\"Integer-Division\", \"Hour Bin 2\"}}),",
                "    #\"Inserted Integer-Division5\" = Table.AddColumn(#\"Renamed Columns11\", \"Integer-Division\", each Number.IntegerDivide([Minute], 30), Int64.Type),",
                "    #\"Multiplied Column\" = Table.TransformColumns(#\"Inserted Integer-Division5\", {{\"Integer-Division\", each _ * 30, type number}}),",
                "    #\"Renamed Columns12\" = Table.RenameColumns(#\"Multiplied Column\",{{\"Integer-Division\", \"Minute Bin 30\"}}),",
                "    #\"Inserted Integer-Division6\" = Table.AddColumn(#\"Renamed Columns12\", \"Integer-Division\", each Number.IntegerDivide([Minute], 15), Int64.Type),",
                "    #\"Multiplied Column1\" = Table.TransformColumns(#\"Inserted Integer-Division6\", {{\"Integer-Division\", each _ * 15, type number}}),",
                "    #\"Renamed Columns13\" = Table.RenameColumns(#\"Multiplied Column1\",{{\"Integer-Division\", \"Minute Bin 15\"}}),",
                "    #\"Inserted Integer-Division7\" = Table.AddColumn(#\"Renamed Columns13\", \"Integer-Division\", each Number.IntegerDivide([Minute], 10), Int64.Type),",
                "    #\"Multiplied Column2\" = Table.TransformColumns(#\"Inserted Integer-Division7\", {{\"Integer-Division\", each _ * 10, type number}}),",
                "    #\"Renamed Columns14\" = Table.RenameColumns(#\"Multiplied Column2\",{{\"Integer-Division\", \"Minute Bin 10\"}, {\"Time\", \"Time (s)\"}})",
                "in",
                "    #\"Renamed Columns14\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "User",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3621620e91c64be4a02cd2b234637fdc"
          }
        ],
        "columns": [
          {
            "name": "Executing User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2220ad8d-dde9-4b13-b298-311d2e5ea1a3",
            "sourceColumn": "Operation[Executing User]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5112cf55-3173-40ba-b07c-7291acc5066a",
        "partitions": [
          {
            "name": "User-ec5eb1cf-3346-400b-9efb-4d33f7a39e2d",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DISTINCT('Operation'[Executing User])"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Operation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ApplicationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a797c85-ddbf-45b4-ac76-9caa4ca4d505",
            "sourceColumn": "ApplicationName",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b3df891-875c-4c2f-8082-1f78a95ed9c2",
            "sourceColumn": "DatasetId",
            "summarizeBy": "none"
          },
          {
            "name": "Executing User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "040c1db4-1fa3-4589-820c-2e4cdb2e54ee",
            "sourceColumn": "Executing User",
            "summarizeBy": "none"
          },
          {
            "name": "Operation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19dcc753-121a-47ac-905a-a56e24f6e397",
            "sourceColumn": "Operation",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f42be657-6381-45f2-bbed-697a067ad0fe",
            "sourceColumn": "PremiumCapacityId",
            "summarizeBy": "none"
          },
          {
            "name": "SourceSystem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f40d973d-2db5-4f42-842f-4dda0b1ba31b",
            "sourceColumn": "SourceSystem",
            "summarizeBy": "none"
          },
          {
            "name": "TenantId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b3e8e0d-77a0-41a4-a77e-5a61f7be5cd9",
            "sourceColumn": "TenantId",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e3c2cb3-10d3-4e72-9987-ab5721be3ffc",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "621e10c7-95b3-411b-bd3a-04e4b4ebf236",
            "sourceColumn": "User",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05463c7c-f90f-4b9b-954b-b350701dd8fe",
            "sourceColumn": "WorkspaceId",
            "summarizeBy": "none"
          },
          {
            "name": "ResourceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0216ca1a-a75c-4626-b729-bfc64bd2e404",
            "sourceColumn": "ResourceId",
            "summarizeBy": "none"
          },
          {
            "name": "SubscriptionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65eb1a89-ecc3-4153-ba67-76177297aa40",
            "sourceColumn": "SubscriptionId",
            "summarizeBy": "none"
          },
          {
            "name": "Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "b31efda4-cf7a-4f77-98f6-a745b5cde729",
            "sourceColumn": "Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "TextDataHash",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90f14270-f22f-4d42-a98b-579e547ddf7c",
            "sourceColumn": "TextDataHash",
            "summarizeBy": "none"
          },
          {
            "name": "ReportId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd86f6c1-a843-45bc-9ac5-fb446cfb761c",
            "sourceColumn": "ReportId",
            "summarizeBy": "none"
          },
          {
            "name": "Scenario ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _operationName = 'Operation'[Operation]",
              "VAR _RAID = 'Operation'[XmlaRequestId]",
              "VAR _hasSubEvent =",
              "    FILTER (",
              "        'Suboperation - Refresh',",
              "        'Suboperation - Refresh'[XmlaRequestId] = _RAID",
              "    )",
              "RETURN",
              "    SWITCH (",
              "        TRUE (),",
              "        AND (",
              "            _operationName = \"CommandEnd\",",
              "            IFERROR (",
              "                SEARCH (",
              "                    \"<Refresh xmlns=\",",
              "                    Operation[EventText]",
              "                ),",
              "                -1",
              "            ) > 0",
              "        ), 1,",
              "        // Refresh",
              "        _operationName = \"QueryEnd\", 2,",
              "        _operationName = \"Error\", 3,",
              "        _operationName = \"DiscoverEnd\", 4,",
              "        _operationName = \"SessionInitialize\", 5,",
              "        _operationName = \"Deadlock\", 6,",
              "        0",
              "    )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fc0d4da8-5121-4ba1-9f78-2d66a0d5c4f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "End Date/Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy hh:nn:ss AM/PM",
            "lineageTag": "48a22bb1-16f4-4fb0-9476-e8adf37b8e1e",
            "sourceColumn": "End Date/Time",
            "summarizeBy": "none"
          },
          {
            "name": "Start Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "3118844a-3c45-420a-92c2-78efaa165987",
            "sourceColumn": "Start Time",
            "summarizeBy": "none"
          },
          {
            "name": "Duration (ms)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "80c83465-65f6-43e8-8a84-c0e201b39b9c",
            "sourceColumn": "Duration (ms)",
            "summarizeBy": "sum"
          },
          {
            "name": "Start Date/Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy hh:nn:ss AM/PM",
            "lineageTag": "125ed4a8-b4c4-4bc3-9776-4b980667b684",
            "sourceColumn": "Start Date/Time",
            "summarizeBy": "none"
          },
          {
            "name": "CPUTime (calculated)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "[CPU Time (ms) Total]"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "3f24a401-5937-4476-b136-213e57b59ca9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Query Duration Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR CurrentDuration = Operation[Duration (ms)]",
              "VAR FilterSegment =",
              "    FILTER (",
              "        'Query Duration Segment',",
              "        AND (",
              "            'Query Duration Segment'[Min] <= CurrentDuration,",
              "            'Query Duration Segment'[Max] > CurrentDuration",
              "        )",
              "    )",
              "VAR Result =",
              "    CALCULATE (",
              "        DISTINCT ( 'Query Duration Segment'[Query Duration Segment Key] ),",
              "        FilterSegment",
              "    )",
              "RETURN",
              "    Result"
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0c3b8d8b-b366-4bf2-b044-c1859fe2654a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "EventText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "320ce942-5a33-41bf-9fbf-2af2ea496f98",
            "sourceColumn": "EventText",
            "summarizeBy": "none"
          },
          {
            "name": "Operation Detail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b5b568f-ee46-4019-b060-e4c8bad46bf6",
            "sourceColumn": "Operation Detail",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40276180-ea2b-48a5-b658-813491b59517",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "StatusCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "3224277b-02be-457d-8e65-8f86348493b3",
            "sourceColumn": "StatusCode",
            "summarizeBy": "count"
          },
          {
            "name": "XmlaSessionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f4b0ec5-9f01-4a51-bfed-7a96b110070f",
            "sourceColumn": "XmlaSessionId",
            "summarizeBy": "none"
          },
          {
            "name": "CPUTime (ms)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "6e06e1f7-e1fd-4159-8518-9e575b75128d",
            "sourceColumn": "CPUTime (ms)",
            "summarizeBy": "sum"
          },
          {
            "name": "Workspace",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb64634f-5e54-4b1d-8575-7a928609247a",
            "sourceColumn": "Workspace",
            "summarizeBy": "none"
          },
          {
            "name": "ArtifactKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07dbd8c6-d961-42c4-964d-ca508ae1a9c2",
            "sourceColumn": "ArtifactKind",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d41d7593-ceb7-439b-81e4-ba538ad8c869",
            "sourceColumn": "DatasetMode",
            "summarizeBy": "none"
          },
          {
            "name": "Dataset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0039f371-e951-4774-b7de-bf89cf17ed78",
            "sourceColumn": "Dataset",
            "summarizeBy": "none"
          },
          {
            "name": "Query Suboperation Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c12a280-5084-4753-8c36-27b06baf4b1a",
            "sourceColumn": "Query Suboperation Key",
            "summarizeBy": "none"
          },
          {
            "name": "Refresh Suboperation Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e31e3a47-4359-4d4e-ab6d-15cc954a79c1",
            "sourceColumn": "Refresh Suboperation Key",
            "summarizeBy": "none"
          },
          {
            "name": "XmlaRequestId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13ee311f-f95c-4224-9add-cb3097d6e2d6",
            "sourceColumn": "XmlaRequestId",
            "summarizeBy": "none"
          },
          {
            "name": "End Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "Operation[End Date/Time]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "d40a71ef-6b47-46f0-b95e-5b217225c69e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Start_Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "Operation[Start Time]"
            ],
            "formatString": "hh:nn AM/PM",
            "isDataTypeInferred": true,
            "lineageTag": "f24b86d5-2ef8-4b4c-b0cc-197817760cb9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Operation StartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT (",
              "    Operation[Start Date/Time],",
              "    \"dd-mmm-yyyy\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4770555f-8b99-4a88-9be9-98fb1a5fcf4f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Agg Suboperation Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb62d29c-f1c3-4ece-944d-d3f706fb9992",
            "sourceColumn": "Agg Suboperation Key",
            "summarizeBy": "none"
          },
          {
            "name": "IsAggregationUsed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    CONTAINS (",
              "        'Suboperation - Aggregations',",
              "        'Suboperation - Aggregations'[XmlaRequestId], Operation[Agg Suboperation Key],",
              "        'Suboperation - Aggregations'[AggregationStatus], \"matchFound\"",
              "    ),",
              "    \"Yes\",",
              "    \"No\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "80822c50-06cc-4ac9-af13-1287a48884e6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "IsAggregationUsed(1/0)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IF (",
              "    CONTAINS (",
              "        'Suboperation - Aggregations',",
              "        'Suboperation - Aggregations'[XmlaRequestId], Operation[Agg Suboperation Key],",
              "        'Suboperation - Aggregations'[AggregationStatus], \"matchFound\"",
              "    ),",
              "    1,",
              "    0",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0cc94610-5bfe-4505-a67d-4924bede3a70",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Scenario name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(Operation[Scenario ID],",
              "0,\"Unknown\",",
              "1,\"Refresh completed\",",
              "2,\"Query completed\",",
              "3,\"Error reported\",",
              "4,\"Discover completed\",",
              "5,\"User session started\",",
              "6,\"Deadlock occurred\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7fc52ca6-6c8c-4d6e-b192-f00ea0635d35",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "DatasetId Hierarchy",
            "levels": [
              {
                "name": "DatasetId",
                "column": "DatasetId",
                "lineageTag": "34c6c56d-e628-4b26-ae67-b26c6f2af9ff",
                "ordinal": 0
              },
              {
                "name": "Dataset",
                "column": "Dataset",
                "lineageTag": "98019e49-3bd7-463f-ae48-1e32843403cf",
                "ordinal": 1
              }
            ],
            "lineageTag": "b23151c6-fe0a-4c32-87a4-e8da4f671d31"
          }
        ],
        "lineageTag": "91e1fd72-ac8c-4c99-8a32-d596158d09a1",
        "partitions": [
          {
            "name": "Operation-f50c4154-bb43-459b-b0cf-1cdfcb8316be",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = OperationExceptRefresh_stage,",
                "    #\"Merged Queries\" = Table.NestedJoin(Source, {\"XmlaRequestId\"}, RefreshOperations, {\"XmlaRequestId\"}, \"Suboperation\", JoinKind.LeftAnti),",
                "    #\"Appended Query\" = Table.Combine({#\"Merged Queries\", RefreshOperations}),",
                "",
                "    //#\"Renamed Columns\" = Table.RenameColumns(AnalyticsQuery,{{\"DurationMs\", \"Duration (ms)\"}}),",
                "    #\"Added Start DateTime (UTC offset)\" = Table.AddColumn(#\"Appended Query\", \"Start DateTime\", each[StartTime] + #duration(0,Number.RoundDown(#\"UTC Offset Hours\"),Number.RoundDown(60 * Number.Mod(#\"UTC Offset Hours\", 1)),0),type datetime),",
                "    #\"Inserted StartDate\" = Table.AddColumn(#\"Added Start DateTime (UTC offset)\", \"Start Date\", each DateTime.Date([Start DateTime]), type date),",
                "    #\"Inserted Time\" = Table.AddColumn(#\"Inserted StartDate\", \"Start Time (s)\", each DateTime.Time([Start DateTime]), type time),",
                "    #\"Removed Original StartTime\" = Table.RemoveColumns(#\"Inserted Time\",{\"StartTime\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Original StartTime\", \"EndTime\", each [Start DateTime] + #duration(0, 0, 0, [#\"Duration (ms)\"] / 1000)),",
                "",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"CpuTimeMs\", Int64.Type}, {\"Duration (ms)\", Int64.Type}, {\"EndTime\", type datetimezone}, {\"TextDataHash\", Int64.Type}, {\"Start DateTime\", type datetimezone}, {\"Start Date\", type date}, {\"Start Time (s)\", type time}}),",
                "    #\"Renamed to Start Date/Time\" = Table.RenameColumns(#\"Changed Type1\",{{\"Start DateTime\", \"Start Date/Time\"}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Renamed to Start Date/Time\",{{\"CpuTimeMs\", \"CPUTime (ms)\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"TextDataHash\", type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type2\"),",
                "",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Removed Duplicates\",{{\"StatusCode\", type number}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type3\",{{\"EndTime\", \"End Date/Time\"}, {\"WorkspaceName\", \"Workspace\"}, {\"OperationName\", \"Operation\"}, {\"OperationDetailName\", \"Operation Detail\"}, {\"Start Time (s)\", \"Start Time\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns1\",{\"Suboperation\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Columns\", \"Index\", 0, 1, Int64.Type),",
                "    #\"Add QuerySuboperationKey\" = Table.AddColumn(#\"Added Index\", \"Query Suboperation Key\", each if [QuerySubeventKey] = \"\" or [QuerySubeventKey] = null then [Index] else [QuerySubeventKey]),",
                "    #\"Add RefreshSuboperationKey\" = Table.AddColumn(#\"Add QuerySuboperationKey\", \"Refresh Suboperation Key\", each if [RefreshSubeventKey] = null then [Index] else [RefreshSubeventKey]),",
                "    #\"Add AggSuboperationKey\" = Table.AddColumn(#\"Add RefreshSuboperationKey\", \"Agg Suboperation Key\", each if [QuerySubeventKey] = \"\" or [QuerySubeventKey] = null then [Index] else [QuerySubeventKey]),",
                "",
                "    #\"Remove Columns\" = Table.RemoveColumns(#\"Add AggSuboperationKey\",{\"QuerySubeventKey\", \"RefreshSubeventKey\", \"Index\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Remove Columns\",{{\"ExecutingUser\", \"Executing User\"}})",
                "",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Suboperation - Refresh",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Duration (ms)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b307e1c-919a-4e7f-84da-fc62e8c2495c",
            "sourceColumn": "Duration (ms)",
            "summarizeBy": "sum"
          },
          {
            "name": "ExecutingUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "353d6777-a640-459d-98e9-3aea67851cc9",
            "sourceColumn": "ExecutingUser",
            "summarizeBy": "none"
          },
          {
            "name": "Operation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "368f7606-2438-403e-ba91-ae915fa65798",
            "sourceColumn": "Operation",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34d52e08-2e39-4c53-9571-d93e05eda102",
            "sourceColumn": "PremiumCapacityId",
            "summarizeBy": "none"
          },
          {
            "name": "TenantId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "250615ca-75e9-4c25-ad91-5690840fe4fd",
            "sourceColumn": "TenantId",
            "summarizeBy": "none"
          },
          {
            "name": "TextDataHash",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89a089e9-6575-4f31-9b72-dd503cda4574",
            "sourceColumn": "TextDataHash",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87b601cd-f584-4457-824d-575e08341bac",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8026b7ee-9413-4c7a-a674-d498bfc1f44b",
            "sourceColumn": "User",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aca85496-00a0-41b5-82f2-5da432ec9943",
            "sourceColumn": "WorkspaceId",
            "summarizeBy": "none"
          },
          {
            "name": "ResourceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90c6b7fc-f20c-4d2e-806e-c6bc9c478312",
            "sourceColumn": "ResourceId",
            "summarizeBy": "none"
          },
          {
            "name": "SubscriptionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90a7e5dc-8405-46a0-897c-cac373f6819b",
            "sourceColumn": "SubscriptionId",
            "summarizeBy": "none"
          },
          {
            "name": "Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "0aebdefd-f6a7-4c5a-8650-35fe80ebd72a",
            "sourceColumn": "Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Start Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "4e86eec4-6072-4cd3-a4d3-e7043b613a48",
            "sourceColumn": "Start Time",
            "summarizeBy": "none"
          },
          {
            "name": "Start Date/Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy hh:nn:ss AM/PM",
            "lineageTag": "9fcdcd1b-8ed3-457e-8ed5-c1d864873f56",
            "sourceColumn": "Start Date/Time",
            "summarizeBy": "none"
          },
          {
            "name": "ObjectTable + ObjectName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "'Suboperation - Refresh'[Object Parent Name] & \" - \" & 'Suboperation - Refresh'[Object]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4cedc084-129f-4879-9a82-2df32f444a22",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ApplicationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80f89d0e-4361-4df9-9cfa-eb268abb18b0",
            "sourceColumn": "ApplicationName",
            "summarizeBy": "none"
          },
          {
            "name": "CpuTimeMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "31d9be39-f0e8-4ebe-8665-cb86a5438c37",
            "sourceColumn": "CpuTimeMs",
            "summarizeBy": "sum"
          },
          {
            "name": "EventText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5916dd39-8460-4119-be8a-7247fa806512",
            "sourceColumn": "EventText",
            "summarizeBy": "none"
          },
          {
            "name": "End Date/Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy hh:nn:ss AM/PM",
            "lineageTag": "fbfcac0d-4181-4696-a734-d71ac0dacfb0",
            "sourceColumn": "End Date/Time",
            "summarizeBy": "none"
          },
          {
            "name": "Operation Detail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0307f4b-469b-44ab-a7c3-a62cd6a64c58",
            "sourceColumn": "Operation Detail",
            "summarizeBy": "none"
          },
          {
            "name": "SourceSystem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2be98913-f9c2-47de-ab3b-d2eeb75aa27e",
            "sourceColumn": "SourceSystem",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f5737fa-3eee-437f-8849-31e4be35dd48",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "StatusCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8eb10b67-c9d4-401b-be44-ddb1e3e3c14b",
            "sourceColumn": "StatusCode",
            "summarizeBy": "none"
          },
          {
            "name": "XmlaRequestId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b27df79c-0ac7-4c7b-8305-0967b05fbb37",
            "sourceColumn": "XmlaRequestId",
            "summarizeBy": "none"
          },
          {
            "name": "XmlaSessionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91aa613d-c310-434e-8b66-d21e8f89b904",
            "sourceColumn": "XmlaSessionId",
            "summarizeBy": "none"
          },
          {
            "name": "XmlaObjectPath",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f11ab72c-3688-4257-b091-417c4f757d05",
            "sourceColumn": "XmlaObjectPath",
            "summarizeBy": "none"
          },
          {
            "name": "Object",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "565e0bf1-f88b-4658-a4d5-1c718115832a",
            "sourceColumn": "Object",
            "summarizeBy": "none"
          },
          {
            "name": "Object Parent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d981ca7-e815-4d19-b616-fa306a3b3960",
            "sourceColumn": "Object Parent Name",
            "summarizeBy": "none"
          },
          {
            "name": "Workspace",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31e72ace-1a32-404e-b6ce-392684e2fb36",
            "sourceColumn": "Workspace",
            "summarizeBy": "none"
          },
          {
            "name": "ArtifactKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "647ebc37-742e-489e-843d-e94585c536b7",
            "sourceColumn": "ArtifactKind",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fa3f401-e2f7-4503-a06c-c49e135daea4",
            "sourceColumn": "DatasetMode",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9f9cdf7-8497-4cf2-a80f-5a3d1534a476",
            "sourceColumn": "DatasetId",
            "summarizeBy": "none"
          },
          {
            "name": "Dataset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "060bdea7-c95c-46e2-b922-2fee55f5ddf9",
            "sourceColumn": "Dataset",
            "summarizeBy": "none"
          },
          {
            "name": "Microsecond",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ccfbd4d2-4f21-4fb8-b581-7d529796eac5",
            "sourceColumn": "Microsecond",
            "summarizeBy": "sum"
          },
          {
            "name": "End Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": "'Suboperation - Refresh'[End Date/Time]",
            "formatString": "Long Time",
            "isDataTypeInferred": true,
            "lineageTag": "9660c937-2492-42c9-a73e-9d69b6e1a49a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "0a46aa30-01a0-4eb7-a69e-1e074906154b",
        "partitions": [
          {
            "name": "Suboperation - Refresh-cd1ef9b4-26c1-4560-8bd7-2b66f96909f3",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.Combine({RefreshSuboperations, RelatedRefreshOperationsForSubOpTable}),",
                "    LastDot = Table.AddColumn(Source, \"LastDot\", each Text.PositionOf([XmlaObjectPath], \".\", Occurrence.Last)),",
                "    #\"Len(xmlObject)\" = Table.AddColumn(LastDot, \"xmlObjectLength\", each Text.Length([XmlaObjectPath])),",
                "    ObjectName = Table.AddColumn(#\"Len(xmlObject)\", \"Object Name\", each Text.End([XmlaObjectPath], [xmlObjectLength] - ([LastDot]+1))),",
                "    #\"Remainder before last dot\" = Table.AddColumn(ObjectName, \"Remainder\", each Text.BeforeDelimiter([XmlaObjectPath], \".\", {0, RelativePosition.FromEnd})),",
                "    #\"2nd LastDot\" = Table.AddColumn(#\"Remainder before last dot\", \"2nd Last Dot\", each Text.PositionOf([Remainder], \".\", Occurrence.Last)),",
                "    #\"2nd Len\" = Table.AddColumn(#\"2nd LastDot\", \"2nd Len(xmlObject)\", each Text.Length([Remainder])),",
                "    #\"Added Custom\" = Table.AddColumn(#\"2nd Len\", \"Object Parent Name\", each Text.End([Remainder], [#\"2nd Len(xmlObject)\"] - ([2nd Last Dot]+1))),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\",{\"LastDot\", \"xmlObjectLength\", \"Remainder\", \"2nd Last Dot\", \"2nd Len(xmlObject)\"}),",
                "    ",
                "    #\"Added Start DateTime (UTC offset)\" = Table.AddColumn(#\"Removed Columns\", \"Start DateTime\", each[TimeGenerated] + #duration(0,Number.RoundDown(#\"UTC Offset Hours\"),Number.RoundDown(60 * Number.Mod(#\"UTC Offset Hours\", 1)),0),type datetime),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Added Start DateTime (UTC offset)\", \"Start Date\", each DateTime.Date([Start DateTime]), type date),",
                "    #\"Inserted Time\" = Table.AddColumn(#\"Inserted Date\", \"Start Time (s)\", each DateTime.Time([Start DateTime]), type time),",
                "   //#\"Renamed Columns\" = Table.RenameColumns(#\"Start Time (s)\",{{\"DurationMs\", \"Duration (ms)\"}}),",
                "    #\"Added End Date/Time\" = Table.AddColumn(#\"Inserted Time\", \"EndTime\", each [Start DateTime] + #duration(0, 0, 0, [#\"Duration (ms)\"] / 1000)),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added End Date/Time\",{{\"Start Date\", type date}, {\"Start DateTime\", type datetimezone}, {\"EndTime\", type datetimezone}}),",
                "    #\"Removed StartTime, TimeGenerated\" = Table.RemoveColumns(#\"Changed Type\",{\"TimeGenerated\", \"StartTime\"}),",
                "    ",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed StartTime, TimeGenerated\",{{\"CpuTimeMs\", Int64.Type}, {\"Duration (ms)\", Int64.Type}, {\"Start DateTime\", type datetimezone}, {\"Start Date\", type date}, {\"Start Time (s)\", type time}, {\"EndTime\", type datetimezone}, {\"TextDataHash\", type text}}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Changed Type1\"),",
                "",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates1\",{{\"EndTime\", \"End Date/Time\"}, {\"Object Name\", \"Object\"}, {\"OperationName\", \"Operation\"}, {\"OperationDetailName\", \"Operation Detail\"}, {\"Start DateTime\", \"Start Date/Time\"}, {\"WorkspaceName\", \"Workspace\"}, {\"Start Time (s)\", \"Start Time\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Scenario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "39a67267-e3ad-438a-8fdc-aec003c70670",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Scenario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb997841-b056-4c61-8d97-92879eb58fc4",
            "sourceColumn": "Scenario",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b9b1c4c-7007-45d8-b8bf-ef16ae14a480",
            "sourceColumn": "Sort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3c725c55-0d60-4e92-b834-c3a24545ef07",
        "partitions": [
          {
            "name": "Scenario-f1538f01-4f99-48f0-8b30-64d06f1697fa",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"Vc09DsIwDIbhq0SeO6S/J4ADgMQUdahSI6qWuLJbELfHMSzdXun5ZIcAHgq4pTnRO2mV3kNfBCi1r3hnlIeL9FwX3HDMblppXXbkz8Eqs0brNEmkF/KBa+M2vxMlQZGJkpNt4N+gsUGtdWYmdowr/ak16vJpHMaF4uwoxp3ZtIO+/wI=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Scenario = _t, Sort = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ID\", Int64.Type}, {\"Scenario\", type text}, {\"Sort\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Query Duration Segment",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "329a2c2e-4a05-44d7-b7ff-c71b3bcf686c",
            "sortByColumn": "Query Duration Segment Key",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fa878882-70d1-48b5-a9f3-02409890a3c3",
            "sourceColumn": "Min",
            "summarizeBy": "none"
          },
          {
            "name": "Max",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59b64642-4bf7-49dc-9b7a-5fcbf789d313",
            "sourceColumn": "Max",
            "summarizeBy": "none"
          },
          {
            "name": "Query Duration Segment Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "202fcddb-139d-4967-93fd-da7845d4743b",
            "sourceColumn": "Query Duration Segment Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8a57a8e1-9245-4166-8216-2dbaf3f7b255",
        "partitions": [
          {
            "name": "Query Duration Segment-8ed21b8c-7cff-431a-9ada-a994d7b31e72",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"PY89DoAwCEavYtiMHaj4dwFPUTsZRyfj/aUf4EIK3+OFlkJMiaSV42WWU/h+tMlUU7F55lZLC1Knzf302o8ALBMjkKVOAhF3uMQtpgEwhcMlZmkKxHPsh8AMuALA8u+HwO/AFUDW3wHJPuQxvnopou+Nav0A\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Min = _t, Max = _t, Legend = _t, #\"Query Duration Segment Key\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Min\", Int64.Type}, {\"Max\", Int64.Type}, {\"Legend\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Legend\", \"Segment\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Refresh Duration Segment",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3a2f40c8-7137-47dc-9b72-c4bc9666f557",
            "sourceColumn": "Min",
            "summarizeBy": "sum"
          },
          {
            "name": "Max",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f75dc9a0-5ca2-4226-b74d-f5c3b82fb0c7",
            "sourceColumn": "Max",
            "summarizeBy": "sum"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e9bffe5-8ba6-4b0d-9779-d440c39cf1aa",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Segment Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14ab16c5-42c8-4be3-922d-8b3deb3a9709",
            "sourceColumn": "Segment Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "98f3c0e3-3750-4e61-8f67-2529f26fd49f",
        "partitions": [
          {
            "name": "Refresh Duration Segment-a1fb4674-73bb-40b1-94fe-fa19d1a26c08",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"Tc8xDsMgDIXhqyBvVT342QHlAj0FZaoqZWHs/WscBcL0pP8TiFpJiMlkHB/vn4h9cvcJalxXKdeouXOC9IdvDTMT9okccLJTWagVbd1lg+EYajvfm02xGA5OJVQOdWub6WTFGTRcCXeLeD2h1w+/rnzv1Nof\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Min = _t, Max = _t, Legend = _t, #\"Segment Key\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Min\", Int64.Type}, {\"Max\", Int64.Type}, {\"Legend\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Legend\", \"Segment\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Suboperation - Query",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ApplicationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27b49925-8de2-4b44-9da1-c6dea58aa8e1",
            "sourceColumn": "ApplicationName",
            "summarizeBy": "none"
          },
          {
            "name": "CpuTimeMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3cca5b2-02c4-4d1e-affd-024c4ae4d63e",
            "sourceColumn": "CpuTimeMs",
            "summarizeBy": "sum"
          },
          {
            "name": "DatasetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4a44b95-2722-49b2-97c5-49401f2d44db",
            "sourceColumn": "DatasetId",
            "summarizeBy": "none"
          },
          {
            "name": "Dataset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d13e448d-510c-401f-ab72-47a15850a1a4",
            "sourceColumn": "Dataset",
            "summarizeBy": "none"
          },
          {
            "name": "ArtifactKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acba530f-c53c-4804-875f-55593df85794",
            "sourceColumn": "ArtifactKind",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4f9f850-1772-44cb-89eb-f12a620525c8",
            "sourceColumn": "DatasetMode",
            "summarizeBy": "none"
          },
          {
            "name": "Duration (ms)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b34cce8f-6ef6-4eae-9da8-2117a56337e7",
            "sourceColumn": "Duration (ms)",
            "summarizeBy": "sum"
          },
          {
            "name": "EventText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9c6eaab-c234-40e7-965d-8591a5e4f7a5",
            "sourceColumn": "EventText",
            "summarizeBy": "none"
          },
          {
            "name": "ExecutingUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04ccddf2-6016-4758-a3a9-cb533e8b5d45",
            "sourceColumn": "ExecutingUser",
            "summarizeBy": "none"
          },
          {
            "name": "Operation Detail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20703c7d-81b6-43f6-9b88-176012ae1cd6",
            "sourceColumn": "Operation Detail",
            "summarizeBy": "none"
          },
          {
            "name": "Operation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ce4b603-d557-465a-88c0-74278227b2df",
            "sourceColumn": "Operation",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd654e91-a651-4d35-ae38-00ded9b1adde",
            "sourceColumn": "PremiumCapacityId",
            "summarizeBy": "none"
          },
          {
            "name": "SourceSystem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24f63433-455c-413b-9277-4446c2600044",
            "sourceColumn": "SourceSystem",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea2b68a7-f1ed-4be9-a674-1cf7d50e5b71",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "StatusCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86fc5826-8108-469d-b5c0-8933c079b7f6",
            "sourceColumn": "StatusCode",
            "summarizeBy": "none"
          },
          {
            "name": "TenantId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61ac1573-1cb1-48d5-9cf5-73bb61ca5b75",
            "sourceColumn": "TenantId",
            "summarizeBy": "none"
          },
          {
            "name": "TextDataHash",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31afae6f-9a9d-45bf-aaf0-fbd04e2bd82b",
            "sourceColumn": "TextDataHash",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "343b9feb-acdc-477b-81f2-59ffbb7bf179",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfdedfb9-3786-41b3-a778-5bd21594116f",
            "sourceColumn": "User",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "219dcca6-7868-4ae7-a694-29520254e533",
            "sourceColumn": "WorkspaceId",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2145eb8-1dc5-4238-8746-fca88d5596a8",
            "sourceColumn": "WorkspaceName",
            "summarizeBy": "none"
          },
          {
            "name": "XmlaRequestId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c046699d-1538-44a6-a864-9feb8185ca07",
            "sourceColumn": "XmlaRequestId",
            "summarizeBy": "none"
          },
          {
            "name": "XmlaSessionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e3a5c76-272f-4f3d-af9f-495831741997",
            "sourceColumn": "XmlaSessionId",
            "summarizeBy": "none"
          },
          {
            "name": "XmlaObjectPath",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f20e2ef8-5dee-496b-84b4-5f1c18364669",
            "sourceColumn": "XmlaObjectPath",
            "summarizeBy": "none"
          },
          {
            "name": "ResourceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87a0fea4-a8fa-4c8f-9d04-c00cefbc2dfd",
            "sourceColumn": "ResourceId",
            "summarizeBy": "none"
          },
          {
            "name": "SubscriptionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3069584a-90bb-4978-8d03-c44bbb7d1379",
            "sourceColumn": "SubscriptionId",
            "summarizeBy": "none"
          },
          {
            "name": "Start Date/Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy hh:nn:ss AM/PM",
            "lineageTag": "0f4ad009-1f53-46bb-b990-205b61375e47",
            "sourceColumn": "Start Date/Time",
            "summarizeBy": "none"
          },
          {
            "name": "Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "949929f6-384b-4de3-81df-d5378eb8c903",
            "sourceColumn": "Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Start Time (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "4ff9c81c-9d42-48f1-ab6b-6f9e95669fd0",
            "sourceColumn": "Start Time (s)",
            "summarizeBy": "none"
          },
          {
            "name": "EndTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b5e4cba1-ef9d-49b7-b25f-bc4c6033d5ee",
            "sourceColumn": "EndTime",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b30684f7-5eca-4be9-9562-ec24dea79b36",
        "partitions": [
          {
            "name": "Suboperation - Query-5659c75a-1b51-4285-9120-1b9f9f37b382",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    StartValue = (#\"Days Ago To Start\") - 1,",
                "    Source = List.Generate(() => StartValue, each _ > #\"Days Ago To Finish\"-1, each _ - 1),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Converted to Table\", \"Hours\", each List.Generate(() => 24-(#\"Pagination Hours\"), each _> -1, each _ -#\"Pagination Hours\")),",
                "    #\"Expanded Custom\" = Table.ExpandListColumn(#\"Added Custom3\", \"Hours\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Custom\",{{\"Column1\", \"Ago\"}}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Renamed Columns\", \"GetLogAnalytics_AS\", each fnGetQuerySuboperations([Ago], [Ago],[Hours],#\"Pagination Hours\", #\"Log Analytics Table\",  #\"UTC Offset Hours\")),",
                "    #\"Expanded GetLogAnalytics_AS1\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"GetLogAnalytics_AS\", {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"Dataset\", \"ArtifactKind\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Type\", \"User\", \"PowerBIWorkspaceId\", \"PowerBIWorkspaceName\", \"XmlaRequestId\", \"XmlaSessionId\", \"XmlaObjectPath\", \"ResourceId\", \"SubscriptionId\", \"StartTime\", \"TimeGenerated\"}, {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"Dataset\", \"ArtifactKind\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Type\", \"User\", \"WorkspaceId\", \"WorkspaceName\", \"XmlaRequestId\", \"XmlaSessionId\", \"XmlaObjectPath\", \"ResourceId\", \"SubscriptionId\", \"StartTime\", \"TimeGenerated\"}), ",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded GetLogAnalytics_AS1\",{\"Ago\", \"Hours\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    ",
                "    #\"Added Start DateTime (UTC offset)\" = Table.AddColumn(#\"Removed Blank Rows\", \"Start DateTime\", each[TimeGenerated] + #duration(0,Number.RoundDown(#\"UTC Offset Hours\"),Number.RoundDown(60 * Number.Mod(#\"UTC Offset Hours\", 1)),0),type datetime),",
                "    //#\"Added Start DateTime (UTC offset)\" = Table.AddColumn(#\"AnalyticsQuery\", \"Start DateTime\", each [TimeGenerated] + #duration(0, #\"UTC Offset\",0,0)),",
                "    #\"Inserted StartDate\" = Table.AddColumn(#\"Added Start DateTime (UTC offset)\", \"Start Date\", each DateTime.Date([Start DateTime]), type date),",
                "    #\"Start Time (s)\" = Table.AddColumn(#\"Inserted StartDate\", \"Start Time (s)\", each DateTime.Time([Start DateTime]), type time),",
                "    //#\"Inserted StartDate\" = Table.AddColumn(#\"Added Start DateTime (UTC offset)\", \"Start Date\", each Text.BeforeDelimiter(Text.From([Start DateTime], \"en-us\"), \" \") as text),",
                "    //#\"Start Time (s)\" = Table.AddColumn(#\"Inserted StartDate\", \"Start Time (s)\", each Text.BetweenDelimiters(Text.From([Start DateTime], \"en-US\"), \" \", \" \", 0, 1), type time),    ",
                "    //#\"Renamed Columns\" = Table.RenameColumns(#\"Start Time (s)\",{{\"DurationMs\", \"Duration (ms)\"}}),",
                "    #\"Added End Date/Time\" = Table.AddColumn(#\"Start Time (s)\", \"EndTime\", each [Start DateTime] + #duration(0, 0, 0, [#\"Duration (ms)\"] / 1000)),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added End Date/Time\",{{\"Start Date\", type date}, {\"Start DateTime\", type datetimezone}, {\"EndTime\", type datetimezone}}),",
                "    #\"Removed StartTime, TimeGenerated\" = Table.RemoveColumns(#\"Changed Type\",{\"TimeGenerated\", \"StartTime\"}),",
                "",
                "    ",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed StartTime, TimeGenerated\",{{\"CpuTimeMs\", Int64.Type}, {\"Duration (ms)\", Int64.Type}, {\"Start DateTime\", type datetimezone}, {\"Start Date\", type date}, {\"Start Time (s)\", type time}, {\"EndTime\", type datetimezone}, {\"TextDataHash\", type text}}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Changed Type1\"),",
                "",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Duplicates1\",{{\"Start DateTime\", \"Start Date/Time\"}, {\"OperationDetailName\", \"Operation Detail\"}, {\"OperationName\", \"Operation\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "StartTime",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "38222e14-1b19-4a35-bd7d-41c5c2a97036",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          },
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5494251a-3789-42b3-b340-f0df42b816fb",
            "sourceColumn": "Hour",
            "summarizeBy": "sum"
          },
          {
            "name": "Minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b14e66b8-85ed-49fd-8e6b-a5557f633899",
            "sourceColumn": "Minute",
            "summarizeBy": "sum"
          },
          {
            "name": "Second",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "e82f80d5-184d-4794-9bf8-d580a297c1d5",
            "sourceColumn": "Second",
            "summarizeBy": "sum"
          },
          {
            "name": "AM/PM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "493e5acc-5ef1-445a-ace9-8fe1d7399461",
            "sourceColumn": "AM/PM",
            "summarizeBy": "none"
          },
          {
            "name": "Hour Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ead907f8-bc50-4bda-8af7-82b219713c81",
            "sourceColumn": "Hour Label",
            "summarizeBy": "none"
          },
          {
            "name": "Minute Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f46e1793-4551-468f-8cb6-58f64526d554",
            "sourceColumn": "Minute Label",
            "summarizeBy": "none"
          },
          {
            "name": "Second Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c938f5e3-d028-48d8-8dc0-f35de08f8947",
            "sourceColumn": "Second Label",
            "summarizeBy": "none"
          },
          {
            "name": "Time (h)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "fe5a0099-9347-4817-8e28-afc701f212fa",
            "sourceColumn": "Time (h)",
            "summarizeBy": "none"
          },
          {
            "name": "Time (m)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "51d647c2-4ba6-4699-b1e4-a3bbb9b6f574",
            "sourceColumn": "Time (m)",
            "summarizeBy": "none"
          },
          {
            "name": "Hour(AM/PM)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "h:nn AM/PM",
            "lineageTag": "de2beeac-9fb8-43d0-99d3-fe5503cfd980",
            "sourceColumn": "Hour(AM/PM)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4b57054e-68b0-4b3c-9083-ec40aafd9219",
        "partitions": [
          {
            "name": "StartTime-76ba2200-5f9e-48d2-9190-0f4c91e0c8f5",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = List.Times(#time(0,0,0),24*60*60,#duration(0,0,0,1)),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Time\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Time\", type time}}),",
                "    #\"Added Time (h)\" = Table.AddColumn(#\"Changed Type\", \"Time (h)\", each #time(Time.Hour([Time]),0 ,0) as time),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Time (h)\",{{\"Time (h)\", type time}}),",
                "    #\"Added Time (m)\" = Table.AddColumn(#\"Changed Type2\", \"Time (m)\", each #time(Time.Hour([Time]),Time.Minute([Time]),0) as time),",
                "    #\"Changed Type Time (m)\" = Table.TransformColumnTypes(#\"Added Time (m)\",{{\"Time (m)\", type time}}),",
                "    #\"Inserted Hour\" = Table.AddColumn(#\"Changed Type Time (m)\", \"Hour\", each Time.Hour([Time]), Int64.Type),",
                "    #\"Inserted Minute\" = Table.AddColumn(#\"Inserted Hour\", \"Minute\", each Time.Minute([Time]), Int64.Type),",
                "    #\"Inserted Second\" = Table.AddColumn(#\"Inserted Minute\", \"Second\", each Time.Second([Time]), type number),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Inserted Second\", \"AM/PM\", each if [Hour] < 12 then \"AM\" else \"PM\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"AM/PM\", type text}}),",
                "    #\"Inserted Prefix\" = Table.AddColumn(#\"Changed Type1\", \"Prefix\", each \"0\" & Text.From([Hour], \"en-NZ\"), type text),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Prefix\",{{\"Prefix\", \"Hour Label\"}}),",
                "    #\"Extracted Last Characters\" = Table.TransformColumns(#\"Renamed Columns2\", {{\"Hour Label\", each Text.End(_, 2), type text}}),",
                "    #\"Inserted Prefix1\" = Table.AddColumn(#\"Extracted Last Characters\", \"Prefix\", each \"0\" & Text.From([Minute], \"en-NZ\"), type text),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Inserted Prefix1\",{{\"Prefix\", \"Minute Label\"}}),",
                "    #\"Extracted Last Characters1\" = Table.TransformColumns(#\"Renamed Columns3\", {{\"Minute Label\", each Text.End(_, 2), type text}}),",
                "    #\"Inserted Prefix2\" = Table.AddColumn(#\"Extracted Last Characters1\", \"Prefix\", each \"0\" & Text.From([Second], \"en-NZ\"), type text),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Inserted Prefix2\",{{\"Prefix\", \"Second Label\"}}),",
                "    #\"Extracted Last Characters2\" = Table.TransformColumns(#\"Renamed Columns4\", {{\"Second Label\", each Text.End(_, 2), type text}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Extracted Last Characters2\", \"Time (h)\", \"Time (h) - Copy\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column\",{{\"Time (h) - Copy\", \"Hour(AM/PM)\"}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Hour(AM/PM)\", type time}})",
                "in",
                "    #\"Changed Type3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "EndTime",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "8a0b5031-53f5-4dda-86d7-a5b60376192d",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          },
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b4fcd52d-f86b-4109-8971-df2d9feb2a0c",
            "sourceColumn": "Hour",
            "summarizeBy": "sum"
          },
          {
            "name": "Minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab049d2d-4480-4d1a-bc6a-62f92089805c",
            "sourceColumn": "Minute",
            "summarizeBy": "sum"
          },
          {
            "name": "AM/PM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b44bb0f-8f8a-465b-8cdc-2b7c130c45a1",
            "sourceColumn": "AM/PM",
            "summarizeBy": "none"
          },
          {
            "name": "Time (h)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "9c742960-304f-4838-9c0c-55f6c0b761e5",
            "sourceColumn": "Time (h)",
            "summarizeBy": "none"
          },
          {
            "name": "Time (m)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "e57dc6e7-72b0-4a0d-b8e2-c4c3ad5d4d5a",
            "sourceColumn": "Time (m)",
            "summarizeBy": "none"
          },
          {
            "name": "Second",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "f873db87-02bf-47e1-8e98-ef048fc2f111",
            "sourceColumn": "Second",
            "summarizeBy": "sum"
          },
          {
            "name": "Hour Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a8dea80-8a4c-4bdf-8bf9-f5ef7d9d19f2",
            "sourceColumn": "Hour Label",
            "summarizeBy": "none"
          },
          {
            "name": "Minute Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9df2c2e3-0daf-4aa2-86d6-45800f9eb8a1",
            "sourceColumn": "Minute Label",
            "summarizeBy": "none"
          },
          {
            "name": "Second Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07fc409d-9a4c-4fdf-8ba6-0c6e91fbc568",
            "sourceColumn": "Second Label",
            "summarizeBy": "none"
          },
          {
            "name": "Hour(AM/PM)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "h:nn AM/PM",
            "lineageTag": "49ddca95-a979-46bc-bd4c-96e3d99bd022",
            "sourceColumn": "Hour(AM/PM)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5c2f07a8-da1e-424f-a345-1a2f3a6cd25d",
        "partitions": [
          {
            "name": "EndTime-54cc40b2-0d8e-4f0c-8989-84bdc7297838",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = List.Times(#time(0,0,0),24*60*60,#duration(0,0,0,1)),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Time\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Time\", type time}}),",
                "    #\"Added Time (h)\" = Table.AddColumn(#\"Changed Type\", \"Time (h)\", each #time(Time.Hour([Time]),0 ,0) as time),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Time (h)\",{{\"Time (h)\", type time}}),",
                "    #\"Added Time (m)\" = Table.AddColumn(#\"Changed Type2\", \"Time (m)\", each #time(Time.Hour([Time]),Time.Minute([Time]),0) as time),",
                "    #\"Changed Type Time (m)\" = Table.TransformColumnTypes(#\"Added Time (m)\",{{\"Time (m)\", type time}}),",
                "    #\"Inserted Hour\" = Table.AddColumn(#\"Changed Type Time (m)\", \"Hour\", each Time.Hour([Time]), Int64.Type),",
                "    #\"Inserted Minute\" = Table.AddColumn(#\"Inserted Hour\", \"Minute\", each Time.Minute([Time]), Int64.Type),",
                "    #\"Inserted Second\" = Table.AddColumn(#\"Inserted Minute\", \"Second\", each Time.Second([Time]), type number),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Inserted Second\", \"AM/PM\", each if [Hour] < 12 then \"AM\" else \"PM\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"AM/PM\", type text}}),",
                "    #\"Inserted Prefix\" = Table.AddColumn(#\"Changed Type1\", \"Prefix\", each \"0\" & Text.From([Hour], \"en-NZ\"), type text),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Prefix\",{{\"Prefix\", \"Hour Label\"}}),",
                "    #\"Extracted Last Characters\" = Table.TransformColumns(#\"Renamed Columns2\", {{\"Hour Label\", each Text.End(_, 2), type text}}),",
                "    #\"Inserted Prefix1\" = Table.AddColumn(#\"Extracted Last Characters\", \"Prefix\", each \"0\" & Text.From([Minute], \"en-NZ\"), type text),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Inserted Prefix1\",{{\"Prefix\", \"Minute Label\"}}),",
                "    #\"Extracted Last Characters1\" = Table.TransformColumns(#\"Renamed Columns3\", {{\"Minute Label\", each Text.End(_, 2), type text}}),",
                "    #\"Inserted Prefix2\" = Table.AddColumn(#\"Extracted Last Characters1\", \"Prefix\", each \"0\" & Text.From([Second], \"en-NZ\"), type text),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Inserted Prefix2\",{{\"Prefix\", \"Second Label\"}}),",
                "    #\"Extracted Last Characters2\" = Table.TransformColumns(#\"Renamed Columns4\", {{\"Second Label\", each Text.End(_, 2), type text}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Extracted Last Characters2\", \"Time (h)\", \"Time (h) - Copy\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column\",{{\"Time (h) - Copy\", \"Hour(AM/PM)\"}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Hour(AM/PM)\", type time}})",
                "in",
                "    #\"Changed Type3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Top N Selector",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "72af1c9b44cb491a98170c13173596de"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5b0a9731-a116-4ae5-945d-6f5d7589ddf9",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SelectorSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "16ff4de2-4345-402c-b617-2634cd92ef03",
            "sourceColumn": "[SelectorSort]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Selector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    'Top N Selector'[SelectorSort] = 0,",
              "    \"All\",",
              "    \"Top \"",
              "        & FORMAT (",
              "            'Top N Selector'[SelectorSort],",
              "            \"\"",
              "        )",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2b3d856a-3959-42a0-8b5e-1f8812b346bd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "c56ddd26-af48-401e-8e4c-537d306e5942",
        "measures": [
          {
            "name": "Rank_By_Duration",
            "expression": [
              "",
              "IF (",
              "    ISINSCOPE ( Operation[EventText] ),",
              "    INT (",
              "        RANKX (",
              "            CALCULATETABLE (",
              "                GROUPBY (",
              "                    Operation,",
              "                    Operation[EventText],",
              "                    Operation[ReportId],",
              "                    Operation[Dataset],",
              "                    Operation[Workspace],",
              "                    Operation[PremiumCapacityId]",
              "                ),",
              "                ALLSELECTED (",
              "                    Operation[EventText],",
              "                    Operation[ReportId],",
              "                    Operation[Dataset],",
              "                    Operation[Workspace],",
              "                    Operation[PremiumCapacityId]",
              "                )",
              "            ),",
              "            CALCULATE (",
              "                PERCENTILE.INC (",
              "                    Operation[Duration (ms)],",
              "                    .5",
              "                )",
              "            )",
              "        )",
              "            <= MAX ( 'Top N Selector'[Value] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "a846066c-59e0-47cf-a0ea-1b5b7a81e58d"
          },
          {
            "name": "Rank_By_CPU%",
            "expression": [
              "",
              "IF (",
              "    ISINSCOPE ( Operation[EventText] ),",
              "    INT (",
              "        RANKX (",
              "            CALCULATETABLE (",
              "                GROUPBY (",
              "                    Operation,",
              "                    Operation[EventText],",
              "                    Operation[ReportId],",
              "                    Operation[Dataset],",
              "                    Operation[Workspace],",
              "                    Operation[PremiumCapacityId]",
              "                ),",
              "                ALLSELECTED (",
              "                    Operation[EventText],",
              "                    Operation[ReportId],",
              "                    Operation[Dataset],",
              "                    Operation[Workspace],",
              "                    Operation[PremiumCapacityId]",
              "                )",
              "            ),",
              "            CALCULATE (",
              "                DIVIDE (",
              "                    [CPU Time Std Dev],",
              "                    [CPU Time Mean]",
              "                )",
              "            )",
              "        )",
              "            <= MAX ( 'Top N Selector'[Value] )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "9d7ba982-cb6b-41ef-bde6-0e1ea5d402b2"
          },
          {
            "name": "Title_by CPU%",
            "expression": [
              "",
              "\"Top \"",
              "    & SELECTEDVALUE ( 'Top N Selector'[SelectorSort] ) & \" queries by CPU variability\""
            ],
            "lineageTag": "b729353e-978a-4bbf-8df8-76dac7414460"
          },
          {
            "name": "Title_by Duration",
            "expression": [
              "",
              "\"Top \"",
              "    & SELECTEDVALUE ( 'Top N Selector'[SelectorSort] ) & \" queries by duration P50\""
            ],
            "lineageTag": "860c2713-d337-404b-8050-4c828025aac1"
          },
          {
            "name": "Rank_By_CPU time",
            "expression": [
              "",
              "IF (",
              "    ISINSCOPE ( Operation[Workspace] ),",
              "    INT (",
              "        RANKX (",
              "            CALCULATETABLE (",
              "                GROUPBY (",
              "                    Operation,",
              "                    Operation[ReportId],",
              "                    Operation[Workspace],",
              "                    Operation[PremiumCapacityId]",
              "                ),",
              "                ALLSELECTED (",
              "                    Operation[ReportId],",
              "                    Operation[Workspace],",
              "                    Operation[PremiumCapacityId]",
              "                )",
              "            ),",
              "            CALCULATE (",
              "                SWITCH (",
              "                    MIN ( Scenario[ID] ),",
              "                    1, [CPU Time - Refresh],",
              "                    2, [CPU Time - Query],",
              "                    [CPU Time (ms)]",
              "                )",
              "            )",
              "        )",
              "            <= MAX ( 'Top N Selector'[Value] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ea744942-1409-48e0-95c1-340ed4e1c5f1"
          },
          {
            "name": "Rank_Reports_By_CPUTime",
            "expression": [
              "",
              "IF (",
              "    ISINSCOPE ( Operation[ReportId] ),",
              "    INT (",
              "        RANKX (",
              "            CALCULATETABLE (",
              "                GROUPBY (",
              "                    Operation,",
              "                    Operation[ReportId]",
              "                ),",
              "                ALLSELECTED ( Operation[ReportId] )",
              "            ),",
              "            CALCULATE (",
              "                SUM ( Operation[CPUTime (ms)] )",
              "            )",
              "        )",
              "            <= MAX ( 'Top N Selector'[Value] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "be9b4acb-ad83-487f-897c-b09f3ce1479e"
          },
          {
            "name": "Rank_User_By_CPUTime",
            "expression": [
              "",
              "IF (",
              "    ISINSCOPE (  User[Executing User]),",
              "    INT (",
              "        RANKX (",
              "            CALCULATETABLE (",
              "                GROUPBY (",
              "                    User,",
              "                     User[Executing User]",
              "                ),",
              "                ALLSELECTED (  User[Executing User] )",
              "            ),",
              "            CALCULATE (",
              "                SUM ( Operation[CPUTime (ms)] )",
              "            )",
              "        )",
              "            <= MAX ( 'Top N Selector'[Value] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "58badb84-5d08-4c6e-a6c5-50011651be43"
          },
          {
            "name": "Rank_User_By_Queries",
            "expression": [
              "IF (",
              "    ISINSCOPE (  User[Executing User]),",
              "    INT (",
              "        RANKX (",
              "            CALCULATETABLE (",
              "                GROUPBY (",
              "                    User,",
              "                     User[Executing User]",
              "                ),",
              "                ALLSELECTED (  User[Executing User] )",
              "            ),",
              "            CALCULATE (",
              "                [Queries]",
              "            )",
              "        )",
              "            <= MAX ( 'Top N Selector'[Value] )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d4d7b45a-eb50-4d2a-a535-5dd2be474b8b"
          },
          {
            "name": "Rank_User_By_Operations",
            "expression": [
              "",
              "IF (",
              "    ISINSCOPE (  User[Executing User]),",
              "    INT (",
              "        RANKX (",
              "            CALCULATETABLE (",
              "                GROUPBY (",
              "                    User,",
              "                     User[Executing User]",
              "                ),",
              "                ALLSELECTED (  User[Executing User] )",
              "            ),",
              "            CALCULATE (",
              "                [Operations]",
              "            )",
              "        )",
              "            <= MAX ( 'Top N Selector'[Value] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "106265b9-76a8-4df5-b5b7-837f485bf672"
          }
        ],
        "partitions": [
          {
            "name": "Top N Selector-715fc1fb-eb7f-4a3d-8804-03d220962517",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS (",
                "    GENERATESERIES (",
                "        1,",
                "        25,",
                "        1",
                "    ),",
                "    \"SelectorSort\",",
                "        SWITCH (",
                "            TRUE (),",
                "            [Value] <= 5, 5,",
                "            [Value] <= 10, 10,",
                "            [Value] <= 15, 15,",
                "            [Value] <= 20, 20,",
                "            [Value] <= 25, 25,",
                "            [Value]",
                "        )",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "EndDateTable",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "dc21ad6678994667b94b9a40b4a849dc"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "725208e6-7094-4448-9afb-5b874cde0387",
            "sourceColumn": "Calendar[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "UNIXEndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "EndDateTable[Date]"
            ],
            "lineageTag": "a12f1f45-f0f9-40d7-8d97-c1e5adc3600b",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "ecc208e4-9b0e-44db-932a-70279f19c144",
        "partitions": [
          {
            "name": "EndDateTable-6db9a522-d5e2-4428-a2f3-5ee0a3f9cd25",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DISTINCT ( 'Calendar'[Date] )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "StartDateTable",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "440df2ef9ec44458a9513ef4e9c97385"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "975f956c-d6b1-4651-854e-7e5d93a90bc9",
            "sourceColumn": "Calendar[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "UNIXStartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "StartDateTable[Date]"
            ],
            "lineageTag": "9376b968-1f6a-48c5-8e48-88b26d52f2d2",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "8613e5c4-af3d-452b-9ba5-6dd55bf60449",
        "measures": [
          {
            "name": "Filter error details time range",
            "expression": [
              "",
              "VAR StartFilter =",
              "    /*CALCULATE ( MIN ( StartDateTable[Date] ), ALLSELECTED ( StartDateTable ) ) +*/",
              "    CALCULATE (",
              "        MIN ( 'StartTime'[Time] ),",
              "        ALLSELECTED ( StartTime )",
              "    )",
              "VAR EndFilter =",
              "    /*CALCULATE ( MAX ( EndDateTable[Date] ), ALLSELECTED ( EndDateTable ) )+ */",
              "    CALCULATE (",
              "        MAX ( EndTime[Time] ),",
              "        ALLSELECTED ( EndTime )",
              "    )",
              "VAR Start_cal =",
              "    /*CALCULATE(MIN('Calendar'[Date]))+*/",
              "    CALCULATE (",
              "        MIN ( 'Time'[Time (s)] )",
              "    )",
              "VAR end_cal =",
              "    /*CALCULATE(MAX('Calendar'[Date]))+*/",
              "    CALCULATE (",
              "        MAX ( 'Time'[Time (s)] )",
              "    )",
              "RETURN",
              "    IF (",
              "        Start_cal >= StartFilter",
              "            && end_cal <= EndFilter,",
              "        1,",
              "        2",
              "    )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "8dcd16eb-6592-4a2a-a692-966633ca66a3"
          },
          {
            "name": "Text  error details time range",
            "expression": [
              "",
              "VAR Start_Range =",
              "    CALCULATE (",
              "        MIN ( StartTime[Time] ),",
              "        ALLSELECTED ( StartTime )",
              "    )",
              "VAR End_Range =",
              "    CALCULATE (",
              "        MAX ( EndTime[Time] ),",
              "        ALLSELECTED ( EndTime )",
              "    )",
              "VAR current_date =",
              "    SELECTEDVALUE ( 'Calendar'[Date] )",
              "RETURN",
              "    //\"Selected Range: \" &",
              "    current_date & \" \" & Start_Range & \" - \" & End_Range"
            ],
            "lineageTag": "07a6fee8-15e4-409e-ba32-e586f7a04041"
          },
          {
            "name": "Filter error details time range(operation)",
            "expression": [
              "",
              "VAR StartFilter =",
              "    /*CALCULATE ( MIN ( StartDateTable[Date] ), ALLSELECTED ( StartDateTable ) ) +*/",
              "    CALCULATE (",
              "        FORMAT (",
              "            MIN ( 'StartTime'[Time] ),",
              "            \"hh:mm:ss\"",
              "        ),",
              "        ALLSELECTED ( StartTime )",
              "    )",
              "VAR EndFilter =",
              "    /*CALCULATE ( MAX ( EndDateTable[Date] ), ALLSELECTED ( EndDateTable ) )+ */",
              "    CALCULATE (",
              "        FORMAT (",
              "            MAX ( EndTime[Time] ),",
              "            \"hh:mm:ss\"",
              "        ),",
              "        ALLSELECTED ( EndTime )",
              "    )",
              "VAR Start_cal =",
              "    /*CALCULATE(MIN('Calendar'[Date]))+*/",
              "    CALCULATE (",
              "        MIN ( 'Time'[Time (s)] )",
              "    )",
              "VAR end_cal =",
              "    /*CALCULATE(MAX('Calendar'[Date]))+*/",
              "    CALCULATE (",
              "        MAX ( 'Time'[Time (s)] )",
              "    )",
              "RETURN",
              "    IF (",
              "        CALCULATE (",
              "            FORMAT (",
              "                MIN ( Operation[Start Time] ),",
              "                \"hh:mm:ss\"",
              "            )",
              "        ) >= StartFilter",
              "            && CALCULATE (",
              "                FORMAT (",
              "                    MAX ( Operation[End Time] ),",
              "                    \"hh:mm:ss\"",
              "                )",
              "            ) <= EndFilter,",
              "        1,",
              "        2",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "1d4b9aa7-dd2d-42cb-9c9a-31a3c4aa625e"
          }
        ],
        "partitions": [
          {
            "name": "StartDateTable-c7fec288-3dce-4b8c-b8a9-02b91c5a9d72",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DISTINCT ( 'Calendar'[Date] )",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parent page",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ParentPage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "400d846e-d114-47a2-b2d6-697c3096b1dc",
            "sourceColumn": "ParentPage",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0ea6d98b-b6d3-4e68-ba8b-c63fbccc6560",
        "measures": [
          {
            "name": "Navigation path",
            "expression": [
              "",
              "IF (",
              "    HASONEVALUE ( 'Parent page'[ParentPage] )",
              "        && HASONEVALUE ( 'Child page'[Secondary page] )",
              "        && HASONEVALUE ( 'Current page'[Current page] ),",
              "    CONCATENATE (",
              "        \" | \",",
              "        CONCATENATE (",
              "            SELECTEDVALUE ( 'Parent page'[ParentPage] ),",
              "            CONCATENATE (",
              "                \" | \",",
              "                CONCATENATE (",
              "                    SELECTEDVALUE ( 'Child page'[Secondary page] ),",
              "                    CONCATENATE (",
              "                        \" | \",",
              "                        SELECTEDVALUE ( 'Current page'[Current page] )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    ),",
              "    IF (",
              "        HASONEVALUE ( 'Parent page'[ParentPage] )",
              "            && HASONEVALUE ( 'Child page'[Secondary page] ),",
              "        CONCATENATE (",
              "            \" | \",",
              "            CONCATENATE (",
              "                SELECTEDVALUE ( 'Parent page'[ParentPage] ),",
              "                CONCATENATE (",
              "                    \" | \",",
              "                    SELECTEDVALUE ( 'Child page'[Secondary page] )",
              "                )",
              "            )",
              "        ),",
              "        IF (",
              "            HASONEVALUE ( 'Parent page'[ParentPage] ),",
              "            CONCATENATE (",
              "                \" | \",",
              "                CONCATENATE (",
              "                    SELECTEDVALUE ( 'Parent page'[ParentPage] ),",
              "                    CONCATENATE (",
              "                        \" | \",",
              "                        SELECTEDVALUE ( 'Current page'[Current page] )",
              "                    )",
              "                )",
              "            ),",
              "            CONCATENATE (",
              "                \" | \",",
              "                SELECTEDVALUE ( 'Current page'[Current page] )",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "8647b220-743e-45fe-932e-cc24926e3408"
          }
        ],
        "partitions": [
          {
            "name": "Parent page-d0764d60-ac89-44a9-b126-860b4081b033",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"VcpLCoAwDEXRrZSOXYYuQFAcFAehRA3SKi9RcPeKn4Gzy+GG4BvOlM3plhLh8H0RfLdg1pUi/7TKo2R2FE12scdKMnLgAawT602tMr5JXqs3xuHUyERN4oMVsODK/gQ=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ParentPage = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ParentPage\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Errors\",\"Error summary\",Replacer.ReplaceText,{\"ParentPage\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Child page",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Secondary page",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f831388d-9e5a-4dc3-821b-be1b8b38d165",
            "sourceColumn": "Secondary page",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "72772379-1404-4f74-849d-78b01d9372df",
        "partitions": [
          {
            "name": "Child page-f41ed37e-291c-415f-a78c-554e4e236afd",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"ZcoxCoAwDEDRq4TOHsMewMGpdAga24C0kkShtxeKiOD6/g/B+ZK4EOBifLE1WMmQd3VxCG5EQyUDoU1I89N6mk6S9ofMalVal1lJvocXqQIHJno13g==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Secondary page\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Secondary page\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Error page detail\",\"Error details\",Replacer.ReplaceText,{\"Secondary page\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Current page",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Current page",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de51263c-8e9e-484f-908e-7d9fc4b0e497",
            "sourceColumn": "Current page",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "317c4b30-0e3d-409e-b641-9a2b0b2c5cdc",
        "measures": [
          {
            "name": "Selected page",
            "expression": [
              "",
              "SELECTEDVALUE('Current page'[Current page])"
            ],
            "lineageTag": "bbd1bf37-eaa0-4f37-af26-1e585f2a5508"
          },
          {
            "name": "Drill through button text",
            "expression": [
              "",
              "VAR Selection = [Selected page]",
              "VAR Filtered =",
              "    ISFILTERED ( Operation[ReportId] )",
              "VAR Result =",
              "    IF (",
              "        Filtered",
              "            = TRUE (),",
              "        \"Drillthrough to \" & Selection,",
              "        \"Make a filter selection\"",
              "    )",
              "RETURN",
              "    Result"
            ],
            "lineageTag": "0a985b29-d0c7-43eb-a648-d1b317848fce"
          },
          {
            "name": "Drillthrough tooltip",
            "expression": [
              "",
              "\"Click to drillthrough to the \"",
              "    & SELECTEDVALUE ( 'Current page'[Current page] ) & \" page\""
            ],
            "lineageTag": "92d91d28-1712-4f28-be0a-46be6c77b459"
          },
          {
            "name": "Drill through button text 2",
            "expression": [
              "",
              "VAR Selection = [Selected page]",
              "VAR Filtered =",
              "    ISFILTERED ( User[User] )",
              "VAR Result =",
              "    IF (",
              "        Filtered",
              "            = TRUE (),",
              "        \"Drillthrough to \" & Selection,",
              "        \"Make a filter selection\"",
              "    )",
              "RETURN",
              "    Result"
            ],
            "lineageTag": "d24ed271-638f-433c-9498-189ac29d857f"
          }
        ],
        "partitions": [
          {
            "name": "Current page-54f895c2-3a22-44b8-ab08-aa3463e5ff77",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"bY7BCsIwEER/JeTsZ9gPEBQPoYclju2iTcruVujfK2laKnp9M8ybEPwZiZI5nYaBZPbtIfhrloeOFPFFm9RxgqNo/GJb2JGMnOAu0B5a0EUha4krO02Q2amRsRrHBTYiWfTftLvBiJ+6KRS2Wmq2m/0B/UeS6+nyZtcoUjdSh422bw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Current page\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Current page\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Engine activity\",\"Engine activities\",Replacer.ReplaceText,{\"Current page\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "GetWorkspaceId",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "columns": [
          {
            "name": "GetWorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00f4c338-284d-44c0-a7b0-e3b812cb9064",
            "sourceColumn": "GetWorkspaceId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "473fead7-0937-48b2-84e9-ab835d69e9d6",
        "partitions": [
          {
            "name": "GetWorkspaceId-b7122174-a50d-43be-bf20-9af20d47bc5e",
            "mode": "import",
            "queryGroup": "Helper queries",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Log Analytics WorkspaceId\"",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Timeline Visual Columns",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ba6316388c1a45c28310cde3f0ff390a"
          }
        ],
        "columns": [
          {
            "name": "Time Slice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "a7c8870b-3430-4318-a97e-20cf5d65ee41",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "e0224b76-20af-4515-9afa-41bafd215e80",
        "partitions": [
          {
            "name": "Timeline Visual Columns-621bb46c-fb2d-4a44-b9c4-a41c08f9dd93",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1, 100, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Suboperation - Aggregations",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ApplicationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e03f0f7-b362-4394-8675-6db362c2c8d8",
            "sourceColumn": "ApplicationName",
            "summarizeBy": "none"
          },
          {
            "name": "CpuTimeMs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6193a6d6-709b-4b48-a9ec-db9d044aa829",
            "sourceColumn": "CpuTimeMs",
            "summarizeBy": "sum"
          },
          {
            "name": "DatasetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47384917-ec4d-4acf-a5cd-a114faea3e9e",
            "sourceColumn": "DatasetId",
            "summarizeBy": "none"
          },
          {
            "name": "Dataset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a1200b2-1f64-4e2a-b316-52216814daf8",
            "sourceColumn": "Dataset",
            "summarizeBy": "none"
          },
          {
            "name": "ArtifactKind",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5648016e-89fc-4ea2-a4e2-a505ed833953",
            "sourceColumn": "ArtifactKind",
            "summarizeBy": "none"
          },
          {
            "name": "DatasetMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39ca5cab-b268-4a7e-96a6-ebc2597907db",
            "sourceColumn": "DatasetMode",
            "summarizeBy": "none"
          },
          {
            "name": "Duration (ms)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e08588c1-32c5-4586-a127-dd05adac6592",
            "sourceColumn": "Duration (ms)",
            "summarizeBy": "sum"
          },
          {
            "name": "EventText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35375b87-3f5e-4885-b818-7ebabccf7083",
            "sourceColumn": "EventText",
            "summarizeBy": "none"
          },
          {
            "name": "ExecutingUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4c5f5b2-e268-493c-9a10-c531950a0fbd",
            "sourceColumn": "ExecutingUser",
            "summarizeBy": "none"
          },
          {
            "name": "Operation Detail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1207e242-275f-4090-9585-255129054ba4",
            "sourceColumn": "Operation Detail",
            "summarizeBy": "none"
          },
          {
            "name": "Operation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a046aba-4a15-4406-864c-c661cabf90e2",
            "sourceColumn": "Operation",
            "summarizeBy": "none"
          },
          {
            "name": "PremiumCapacityId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6fff00e-ba0f-48da-865e-3a3b181c7b23",
            "sourceColumn": "PremiumCapacityId",
            "summarizeBy": "none"
          },
          {
            "name": "SourceSystem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c619e4be-3cf8-45e2-9990-2db6ab9f7120",
            "sourceColumn": "SourceSystem",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17596a09-a682-44bc-ac58-bf62ebc78d10",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "StatusCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "413c7a8f-8fcf-47d3-bb9d-0296669ce08e",
            "sourceColumn": "StatusCode",
            "summarizeBy": "none"
          },
          {
            "name": "TenantId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68adf520-2b19-4294-8f3c-093d4511adab",
            "sourceColumn": "TenantId",
            "summarizeBy": "none"
          },
          {
            "name": "TextDataHash",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4ba2d4c-cd88-4147-a8e6-78ed435de86f",
            "sourceColumn": "TextDataHash",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9aebf31b-0cf9-4a1a-b27a-dd3fb8ce2af3",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2164cf56-4213-4bb3-a4ae-a643e321ff3d",
            "sourceColumn": "User",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d1c2295-90de-4273-a396-dc7613e420db",
            "sourceColumn": "WorkspaceId",
            "summarizeBy": "none"
          },
          {
            "name": "WorkspaceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8f1d93d-692a-4f7d-ae2e-b572bbf88cbe",
            "sourceColumn": "WorkspaceName",
            "summarizeBy": "none"
          },
          {
            "name": "XmlaRequestId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c2b71f2-2de2-4b80-9d0a-514169c8b8ca",
            "sourceColumn": "XmlaRequestId",
            "summarizeBy": "none"
          },
          {
            "name": "XmlaSessionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0675b2c-fcfe-4c38-a059-605cd5f5b927",
            "sourceColumn": "XmlaSessionId",
            "summarizeBy": "none"
          },
          {
            "name": "XmlaObjectPath",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccaadf7c-ba24-44d7-aad6-b19e5a35a567",
            "sourceColumn": "XmlaObjectPath",
            "summarizeBy": "none"
          },
          {
            "name": "ResourceId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c46a4cf3-d43c-4836-a42a-e7f4cf79f431",
            "sourceColumn": "ResourceId",
            "summarizeBy": "none"
          },
          {
            "name": "SubscriptionId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78d72ef2-d0fe-4cab-97fa-c3e7760f1105",
            "sourceColumn": "SubscriptionId",
            "summarizeBy": "none"
          },
          {
            "name": "Start Date/Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy hh:nn:ss AM/PM",
            "lineageTag": "82486146-adb5-4a21-acf4-433fbddb1cd1",
            "sourceColumn": "Start Date/Time",
            "summarizeBy": "none"
          },
          {
            "name": "Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy",
            "lineageTag": "41e25308-a936-4978-a9c0-9fa7e586bb6d",
            "sourceColumn": "Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Start Time (s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "158b4b87-b7b4-4b81-b6eb-824971911cc2",
            "sourceColumn": "Start Time (s)",
            "summarizeBy": "none"
          },
          {
            "name": "EndTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ded676d6-f8b8-4a38-9b09-8ee61588c7ee",
            "sourceColumn": "EndTime",
            "summarizeBy": "none"
          },
          {
            "name": "AggregationStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "223f9897-03a9-4e73-af19-28c610c46cac",
            "sourceColumn": "AggregationStatus",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "45fe2879-ebec-46ef-94f8-4e2688743df4",
        "partitions": [
          {
            "name": "Suboperation - Aggregations-68dd487a-4cd8-4ec7-b93b-f86cf2b9c6bc",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    StartValue = (#\"Days Ago To Start\") - 1,",
                "    Source = List.Generate(() => StartValue, each _ > #\"Days Ago To Finish\"-1, each _ - 1),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Converted to Table\", \"Hours\", each List.Generate(() => 24-(#\"Pagination Hours\"), each _> -1, each _ -#\"Pagination Hours\")),",
                "    #\"Expanded Custom\" = Table.ExpandListColumn(#\"Added Custom3\", \"Hours\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Custom\",{{\"Column1\", \"Ago\"}}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Renamed Columns\", \"GetLogAnalytics_AS\", each fnGetAggSuboperations([Ago], [Ago], [Hours],#\"Pagination Hours\", #\"Log Analytics Table\",  #\"UTC Offset Hours\")),",
                "    #\"Expanded GetLogAnalytics_AS1\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"GetLogAnalytics_AS\", {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"Dataset\", \"ArtifactKind\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Type\", \"User\", \"PowerBIWorkspaceId\", \"PowerBIWorkspaceName\", \"XmlaRequestId\", \"XmlaSessionId\", \"XmlaObjectPath\", \"ResourceId\", \"SubscriptionId\", \"Start DateTime\", \"Start Date\", \"Start Time (s)\", \"EndTime\"}, {\"ApplicationName\", \"CpuTimeMs\", \"DatasetId\", \"Dataset\", \"ArtifactKind\", \"DatasetMode\", \"Duration (ms)\", \"EventText\", \"ExecutingUser\", \"OperationDetailName\", \"OperationName\", \"PremiumCapacityId\", \"SourceSystem\", \"Status\", \"StatusCode\", \"TenantId\", \"TextDataHash\", \"Type\", \"User\", \"WorkspaceId\", \"WorkspaceName\", \"XmlaRequestId\", \"XmlaSessionId\", \"XmlaObjectPath\", \"ResourceId\", \"SubscriptionId\", \"Start DateTime\", \"Start Date\", \"Start Time (s)\", \"EndTime\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded GetLogAnalytics_AS1\",{\"Ago\", \"Hours\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Blank Rows\",{{\"CpuTimeMs\", Int64.Type}, {\"Duration (ms)\", Int64.Type}, {\"Start DateTime\", type datetimezone}, {\"Start Date\", type date}, {\"Start Time (s)\", type time}, {\"EndTime\", type datetimezone}, {\"TextDataHash\", type text}}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Changed Type\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Duplicates1\",{{\"Start DateTime\", \"Start Date/Time\"}, {\"OperationDetailName\", \"Operation Detail\"}, {\"OperationName\", \"Operation\"}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Renamed Columns1\", \"EventText\", \"EventText - Copy\"),",
                "    #\"Parsed JSON\" = Table.TransformColumns(#\"Duplicated Column\",{{\"EventText - Copy\", Json.Document}}),",
                "    #\"Added AggregationStatus\" = Table.ExpandRecordColumn(#\"Parsed JSON\", \"EventText - Copy\", {\"matchingResult\"}, {\"AggregationStatus\"})",
                "in",
                "    #\"Added AggregationStatus\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Last Refresh",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Last Refresh",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd-mmm-yyyy hh:nn:ss AM/PM",
            "lineageTag": "fb936ac8-b343-4002-bfd4-6873ba29127a",
            "sourceColumn": "Last Refresh",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1400ac1e-d9c6-4ff0-8ecb-bd4e6a657adb",
        "partitions": [
          {
            "name": "Last Refresh-2857d915-1eed-4d0c-89ff-18c05914f47d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DateTime.LocalNow() ",
                ",",
                "    #\"Converted to Table\" = #table(1, {{Source}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Last Refresh\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Last Refresh\", type text}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"Last Refresh\", type datetime}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}