table Command
	lineageTag: 4d38904d-2fa7-4d91-a6c2-865c8f3a3ef8

	measure 'Command Count' = COUNTROWS(Command)
		formatString: #,0
		lineageTag: 010772a6-8717-4a55-b589-1ab81b2d36f1

		changedProperty = FormatString

	measure 'Request Duration (s)' = AVERAGE(Command[DurationMs])/1000
		formatString: #,0
		lineageTag: 574495b6-c805-4964-b145-85630a4378bb

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Request Count' = CALCULATE( DISTINCTCOUNT(Command[RequestID]), KEEPFILTERS(Command[RequestID]<>""))
		formatString: #,0
		lineageTag: 4651bade-cfbe-46ad-873f-bba4f8f065a6

		changedProperty = FormatString

	measure 'Commit Phase1 (s)' = SUM(Command[Phase1CommitMs])/1000
		formatString: #,0
		lineageTag: 26b20bb4-ba50-4827-abb3-ab64eeef1fb6

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Commit Phase2 (s)' = SUM(Command[Phase2CommitMs])/1000
		formatString: #,0
		lineageTag: ab7422dd-4fda-4a2b-925a-5401daf2e32d

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Refreshed DB' = CALCULATE( [Artifact], Command)
		formatString: #,0
		lineageTag: 2b5784c5-0fd1-42d2-bdd0-75447455d400

		changedProperty = FormatString

	measure 'Failed Request' = [Request Count] - CALCULATE([Request Count],Command[StatusCode]=0)
		formatString: #,0
		lineageTag: 88812c52-28e2-41f8-9245-9e56d2691deb

		changedProperty = FormatString

	measure 'Request Start' = CALCULATE( MIN(ExecutionMetrics[timeStart]), Command)
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 4303e207-651b-4bdb-99c7-f791f3434251

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Request End' = CALCULATE( MAX(ExecutionMetrics[timeEnd]), Command)
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 6860e3ff-9269-4665-a1a0-f92ec33c8d58

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Status Code' = SELECTEDVALUE(Command[StatusCode])
		formatString: 0
		lineageTag: ab2ffbdf-b498-4aad-ab4b-31ffb336a11b

	measure 'Request with SequencePoint Count' = CALCULATE([Request Count],Command[SequencePointCount]>0)
		formatString: #,0
		lineageTag: f7e23300-4431-4ee7-8bdc-1ec6bedc0273

		changedProperty = FormatString

	measure 'Command with SequencePoint' = CALCULATE([Command Count],Command[SequencePointCount]>0)
		formatString: #,0
		lineageTag: 53dbc2bd-db26-4ea8-87e6-8d292280817f

		changedProperty = FormatString

	measure 'Command CPU (s)' = SUM(Command[CpuTimeMs])/1000
		formatString: #,0
		lineageTag: a39a5865-e263-485d-9195-fa437db5b88b

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Failed Command' = CALCULATE([Command Count],Command[StatusCode]<0)
		formatString: #,0
		lineageTag: 410f5fa2-6543-49d8-9af2-76ab3732f8f7

		changedProperty = FormatString

	measure 'Failed Command %' = DIVIDE([Failed Command], [Command Count])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 93fa9dcc-6c8a-43a5-9b6e-30b04cd39b15

	measure 'SequencePoint Duration' = SUM(Command[SequencePointMs])/1000
		formatString: #,0
		lineageTag: 8af47ad6-835f-4028-9546-9fc9502e2173

	column XmlaRequestId
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: dd2c6305-491c-443c-99a9-11977c039b34
		summarizeBy: none
		sourceColumn: XmlaRequestId

		annotation SummarizationSetBy = Automatic

	column LogAnalyticsCategory
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 003e9708-6372-4ab1-8a1f-0d3c55001b0c
		summarizeBy: none
		sourceColumn: LogAnalyticsCategory

		annotation SummarizationSetBy = Automatic

	column OperationName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 244578fc-75cb-40f3-b974-4bebe9260ad1
		summarizeBy: none
		sourceColumn: OperationName

		annotation SummarizationSetBy = Automatic

	column OperationDetailName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 64235d06-8ee3-4dfe-beea-9fd8f416f11b
		summarizeBy: none
		sourceColumn: OperationDetailName

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: ae7ce1f2-82a1-4707-87ec-142c85dd26aa
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 087bff59-6e7c-453e-9526-d3c41dec34c7
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column StatusCode
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 844a0c20-e8fa-4248-882b-f820aa815a26
		summarizeBy: none
		sourceColumn: StatusCode

		annotation SummarizationSetBy = User

	column RequestID
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 18d7d935-4d16-451d-bbd5-df27f7a58c6c
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column DurationMs
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 7dfcfe1b-75c7-4031-93b4-27fde96d4958
		summarizeBy: none
		sourceColumn: DurationMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CpuTimeMs
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 64a68820-d738-49f5-933a-e4b17f35a11f
		summarizeBy: none
		sourceColumn: CpuTimeMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EventText
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: ecbe7e6d-fdbc-47d9-97fa-5b174b9d4162
		summarizeBy: none
		sourceColumn: EventText

		annotation SummarizationSetBy = Automatic

	column SequencePointCount
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 04ebe4db-e562-489f-b9d1-c951f79087dc
		summarizeBy: none
		sourceColumn: SequencePointCount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SequencePointEnd
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: 534ab9cd-09c4-4b67-949f-cc426b68e927
		summarizeBy: none
		sourceColumn: SequencePointEnd

		annotation SummarizationSetBy = Automatic

	column SequencePointMs
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 7330273c-f73c-4e88-9d27-caf52b372373
		summarizeBy: none
		sourceColumn: SequencePointMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Phase1CommitMs
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: fb7ffa1d-f1f5-411a-b1ce-8ba5e2b8993f
		summarizeBy: none
		sourceColumn: Phase1CommitMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Phase2CommitMs
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 15dff85a-a06c-4cd0-8eb3-59b95f5b41fc
		summarizeBy: none
		sourceColumn: Phase2CommitMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CommandHash
		dataType: string
		lineageTag: 4b1aee53-b605-477c-97e2-ba1d59daa090
		summarizeBy: none
		sourceColumn: CommandHash

		annotation SummarizationSetBy = Automatic

	column RequestApp
		dataType: string
		lineageTag: 9a4bdb5f-f96d-412b-b2ab-2cd6051091f6
		summarizeBy: none
		sourceColumn: RequestApp

		annotation SummarizationSetBy = Automatic

	partition Command-95ff1285-90fb-474a-8454-a52c75863af0 = m
		mode: import
		source = ```
				let AnalyticsQuery =
				let Source = Json.Document(Web.Contents("https://api.loganalytics.io/v1/workspaces/" & #"Azure Log Analytics Workspace Id" & "/query", 
				[Query=[#"query"="
				set notruncation;
				set ClientRequestIdPrefix='BYOLA Command';
				let RangeStartTime = ago(" & Number.ToText(#"Days Ago To Start") & "d);
				let RangeEndTime = ago(" & Number.ToText(#"Days Ago To Finish") & "d);
				let dbid = '"& _ArtifactId &"';
				let wkspid = '"& _WorkspaceId &"';
				let window = PowerBIDatasetsWorkspace
				| extend TimeGenerated=TimeGenerated+"& Number.ToText(#"UTC Offset Hours") &"h 
				| where TimeGenerated >=RangeStartTime-7h and TimeGenerated <RangeEndTime+15m
				| where ArtifactId has dbid and PowerBIWorkspaceId has wkspid
				;
				let cmd= window | where OperationName == 'ExecutionMetrics' or OperationDetailName == 'TabularSequencePoint'
				| extend e=EventText
				| where OperationDetailName == 'TabularSequencePoint' or e has '\""commandType\"": 2' and e !has 'discoverType' and ArtifactId !='' or e has_any ('refreshParallelism', '\""queryDialect\"": 4', '\""commandType\"": 67', '\""commandType\"": 68')
				| summarize by XmlaRequestId;
				cmd
				| join kind=leftouter window on XmlaRequestId | where OperationDetailName !='ExtAuth' and OperationName !='ExecutionMetrics'
				| summarize arg_max(timeEnd=TimeGenerated, DurationMs, CpuTimeMs, Level, Status, StatusCode, OperationName, LogAnalyticsCategory, OperationDetailName)
				, arg_min(timeStart=TimeGenerated, EventText, XmlaProperties)
				, SequencePointCount=dcountif(CorrelationId,OperationDetailName == 'TabularSequencePoint')
				, SequencePointEnd=maxif(TimeGenerated,OperationDetailName == 'TabularSequencePoint')
				, SequencePointMs=maxif(DurationMs,OperationDetailName == 'TabularSequencePoint')
				, Phase1CommitMs=maxif(DurationMs,OperationDetailName == 'TabularCommit' and EventText has ' 1 ')
				, Phase2CommitMs=maxif(DurationMs,OperationDetailName == 'TabularCommit' and EventText has ' 2 ')
				by XmlaRequestId
				| where timeEnd >=RangeStartTime //and timeEnd <RangeEndTime //uncomment this for incremental refresh
				| extend CommandHash=hash_md5(EventText)
				| parse XmlaProperties with * '<DbpropMsmdRequestID>' RequestID '</DbpropMsmdRequestID>' *
				| parse kind=regex flags=Ui XmlaProperties with '(.?)[a-zA-Z]*<SspropInitAppName>' RequestApp '<' *
				| extend RequestApp=case(RequestApp startswith 'PowerBI - Model Change Tracker', 'Power BI - Model Change Tracker'
				, RequestApp startswith 'Power BI Desktop', 'Power BI Desktop', RequestApp startswith 'DAX Studio', 'DAX Studio'
				, RequestApp startswith 'Deployment Utility', 'Deployment Utility', RequestApp startswith 'PowerBI - ExploreService', 'PowerBI - ExploreService'
				, RequestApp startswith 'Microsoft SQL Server Management Studio', 'Microsoft SQL Server Management Studio', RequestApp startswith 'Tabular', 'TabularEditor'
				, RequestApp startswith 'PowerBI - NaturalLanguageService', 'PowerBI - NaturalLanguageService'
				, RequestApp startswith 'SQL Server Profiler', 'SQL Server Profiler', RequestApp)
				| project-away XmlaProperties, timeStart, timeEnd
				",#"x-ms-app"="OmsAnalyticsPBI",#"prefer"="ai.response-thinning=true"],Timeout=#duration(0,0,4,0)])),
				TypeMap = #table(
				{ "AnalyticsTypes", "Type" }, 
				{ 
				{ "string",   Text.Type },
				{ "int",      Int32.Type },
				{ "long",     Int64.Type },
				{ "real",     Double.Type },
				{ "timespan", Duration.Type },
				{ "datetime", DateTimeZone.Type },
				{ "bool",     Logical.Type },
				{ "guid",     Text.Type },
				{ "dynamic",  Text.Type }
				}),
				DataTable = Source[tables]{0},
				Columns = Table.FromRecords(DataTable[columns]),
				ColumnsWithType = Table.Join(Columns, {"type"}, TypeMap , {"AnalyticsTypes"}),
				Rows = Table.FromRows(DataTable[rows], Columns[name]), 
				Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))
				in
				Table
				in AnalyticsQuery
				```

	annotation PBI_ResultType = Table

