table ExecutionMetrics
	lineageTag: 388b868c-ddfb-49a5-bcd6-8cc2a18f5aa1

	measure 'Execution From' = MIN(ExecutionMetrics[timeStart])
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 17bda252-d234-4849-bf9b-39f71a4d3526

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Execution To' = MAX(ExecutionMetrics[timeEnd])
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 8b53f8eb-7c4c-4904-aa8d-4320ae64c33b

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Refresh Mashup CPU (s)' = CALCULATE(SUM(ExecutionMetrics[mEngineCpuTimeMs])/1000, VALUES(Command[XmlaRequestId]))
		formatString: #,0
		displayFolder: Refresh (Write)
		lineageTag: 5096257d-d517-445a-a673-3d24dcb031ca

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Refresh Mashup Peak Memory (MB)' = CALCULATE( SUM(ExecutionMetrics[mEnginePeakMemoryKB])/1024, VALUES(Command[XmlaRequestId]))
		formatString: #,0
		displayFolder: Refresh (Write)
		lineageTag: 31da23da-1677-4849-b123-62edb2903bd9

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Refresh Peak Memory (MB)' = CALCULATE( SUM(ExecutionMetrics[approximatePeakMemConsumptionKB])/1024, VALUES(Command[XmlaRequestId]))
		formatString: #,0
		displayFolder: Refresh (Write)
		lineageTag: 2ba95a84-4e7e-4aaa-a1a7-1b018efd8602

	measure 'Query Peak Memory (MB)' = CALCULATE( SUM(ExecutionMetrics[approximatePeakMemConsumptionKB])/1024, VALUES(Query[XmlaRequestId]))
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: a2e803a0-740c-4943-8bfb-3892c82361c0

	measure 'XmlaRequestId Cnt' = COUNTROWS(ExecutionMetrics)
		formatString: #,0
		lineageTag: 0dfe542a-1246-491b-a185-c65af0506863

	measure 'Capacity Throttling (s)' = CALCULATE( SUM(ExecutionMetrics[capacityThrottlingMs])/1000, VALUES(Query[XmlaRequestId]))
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: 30862653-6699-46a2-b4a8-b0eb829f0e54

	measure 'Event Count' = SUM(ExecutionMetrics[LogCnt])
		formatString: #,0
		lineageTag: 27f2d05f-c7b5-494b-973a-44505d3ef4cc

	measure 'Total CPU (s)' = SUM(ExecutionMetrics[totalCpuTimeMs])/1000
		formatString: #,0
		lineageTag: 6ab7b1df-9504-4072-8dec-f2d6a1b2ddbc

	measure Capacities = DISTINCTCOUNT(ExecutionMetrics[PremiumCapacityId])
		formatString: #,0
		lineageTag: dd1a652b-2508-405a-9934-26aff7a3261d

	measure 'Direct Query Count' = SUM(ExecutionMetrics[directQueryRequestCount])
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: b9fb39e2-047d-416f-b26f-60b0b3506402

	measure 'Capacity Throttling Count' = CALCULATE([XmlaRequestId Cnt],ExecutionMetrics[capacityThrottlingMs]>0)
		formatString: #,0
		lineageTag: 62068258-8cf2-4d78-984a-5ef4eacca967

	measure 'Total Rows' = SUM(ExecutionMetrics[vertipaqTotalRows])
		formatString: #,0
		displayFolder: Refresh (Write)
		lineageTag: 76cf8bb0-58dd-4b64-9178-6a6be088bb5a

	measure 'Cmd Peak Mem (MB)' = CALCULATE( MAX(ExecutionMetrics[approximatePeakMemConsumptionKB])/1024, Command)
		formatString: #,0
		displayFolder: Refresh (Write)
		lineageTag: fbf19b1c-8c3b-4566-a25c-d16cae179cc3

	measure 'Qry Peak Mem (MB)' = CALCULATE( MAX(ExecutionMetrics[approximatePeakMemConsumptionKB])/1024, Query)
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: 920d9d79-eb55-4558-ab53-4763cc4b6f61

	measure 'Failed Requests' = CALCULATE([XmlaRequestId Cnt], ExecutionMetrics[opStatus]="Failed")
		formatString: #,0
		lineageTag: d530a49d-4123-40ff-865e-ae3a6d1f59af

	measure 'Failed XmlaRequestId %' = DIVIDE([Failed Requests],[XmlaRequestId Cnt])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c1e1ba84-1561-4b43-92f0-a1f30900de4d

	measure 'Data Source Throttling Count' = CALCULATE([XmlaRequestId Cnt],ExecutionMetrics[datasourceConnectionThrottleTimeMs]>0)
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: bfe7946c-3aaa-49f7-ae00-f3f25a5ea545

	measure 'Direct Query Connection Time (ms)' = SUM(ExecutionMetrics[directQueryConnectionTimeMs])
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: bcc532d7-5e38-4a71-90fb-1e5e51f1a09b

	measure 'Direct Query Iteration Time (ms)' = SUM(ExecutionMetrics[directQueryIterationTimeMs])
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: ffa1ed7b-f322-4f90-859d-3de79799a1f8

	measure 'Direct Query Total Rows' = SUM(ExecutionMetrics[directQueryTotalRows])
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: fec9e331-66aa-47e0-85fa-86df22cd0c63

	measure 'Direct Query Total Time (ms)' = SUM(ExecutionMetrics[directQueryTotalTimeMs])
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: fe0e9e35-138f-4146-b22c-b2000943fcd6

	measure 'Query Processing CPU (ms)' = SUM(ExecutionMetrics[queryProcessingCpuTimeMs])
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: bc25238a-dfff-44ad-950d-aca060215250

	measure 'Query Result Rows' = CALCULATE( SUM(ExecutionMetrics[queryResultRows]), VALUES(Query[XmlaRequestId]))
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: ce2b6c9a-50b9-426a-a960-adb1007a6ec3

	measure 'Data Source Throttling (ms)' = SUM(ExecutionMetrics[datasourceConnectionThrottleTimeMs])
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: 527056d6-0cb1-4807-a7a7-711fc147227a

	column XmlaRequestId
		dataType: string
		lineageTag: 1d577937-024a-4996-a5c0-14c75b851ffb
		summarizeBy: none
		sourceColumn: XmlaRequestId

		annotation SummarizationSetBy = Automatic

	column ArtifactId
		dataType: string
		isHidden
		lineageTag: 562d7749-ad74-4df9-a0f0-32f8169c2a7f
		summarizeBy: none
		sourceColumn: ArtifactId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ArtifactName
		dataType: string
		isHidden
		lineageTag: 55abd14e-38bd-4b5b-b985-2bb4c322df68
		summarizeBy: none
		sourceColumn: ArtifactName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column operationType
		dataType: string
		lineageTag: ed3b14ee-fbcf-45c4-a53a-0bee7a07397b
		summarizeBy: none
		sourceColumn: operationType

		annotation SummarizationSetBy = Automatic

	column opStatus
		dataType: string
		lineageTag: 55033b9e-76ec-493a-83b9-2e6c513c45e9
		summarizeBy: none
		sourceColumn: opStatus

		annotation SummarizationSetBy = Automatic

	column approximatePeakMemConsumptionKB
		dataType: int64
		formatString: 0
		displayFolder: General
		lineageTag: 088d9a75-16b4-4122-b7e1-3c4682971cbe
		summarizeBy: sum
		sourceColumn: approximatePeakMemConsumptionKB

		annotation SummarizationSetBy = Automatic

	column commandType
		dataType: int64
		formatString: 0
		displayFolder: General
		lineageTag: b70ad66f-7ca3-40dc-af77-d7a973eb9115
		summarizeBy: none
		sourceColumn: commandType

		annotation SummarizationSetBy = User

	column directQueryExecutionTimeMs
		dataType: int64
		formatString: 0
		displayFolder: General
		lineageTag: 94053004-7ff7-4d02-acfe-a9b6ab0365e1
		summarizeBy: sum
		sourceColumn: directQueryExecutionTimeMs

		annotation SummarizationSetBy = Automatic

	column discoverType
		dataType: int64
		formatString: 0
		displayFolder: General
		lineageTag: 917cc3e4-927e-43d7-9e79-d38bacac5116
		summarizeBy: none
		sourceColumn: discoverType

		annotation SummarizationSetBy = User

	column durationMs
		dataType: int64
		formatString: 0
		displayFolder: General
		lineageTag: 4c03d3a8-5932-43c3-8b5a-ccd88a2be1e7
		summarizeBy: sum
		sourceColumn: durationMs

		annotation SummarizationSetBy = Automatic

	column errorCount
		dataType: int64
		formatString: 0
		displayFolder: General
		lineageTag: dfe4ff2e-048d-49ad-94ba-3e06001c3256
		summarizeBy: sum
		sourceColumn: errorCount

		annotation SummarizationSetBy = Automatic

	column executionDelayMs
		dataType: int64
		formatString: #,0
		displayFolder: General
		lineageTag: 5f56d70f-6451-4094-8681-94bde788ec31
		summarizeBy: none
		sourceColumn: executionDelayMs

		annotation SummarizationSetBy = User

	column intendedUsage
		dataType: string
		displayFolder: General
		lineageTag: 498f9568-e71c-426d-b1b2-b10fab12f29c
		summarizeBy: none
		sourceColumn: intendedUsage

		annotation SummarizationSetBy = Automatic

	column mEngineCpuTimeMs
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Refresh (Write)
		lineageTag: 9ec26384-52d8-4690-b26e-7239cfc8790d
		summarizeBy: sum
		sourceColumn: mEngineCpuTimeMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column mEnginePeakMemoryKB
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Refresh (Write)
		lineageTag: c79102c6-7f3b-4623-89cc-5a2edca7f76b
		summarizeBy: sum
		sourceColumn: mEnginePeakMemoryKB

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column qsoReplicaVersion
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		displayFolder: General
		lineageTag: 786c6c53-34ee-417c-8b35-813ce078e6a5
		summarizeBy: none
		sourceColumn: qsoReplicaVersion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column queryDialect
		dataType: int64
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: 278ad91c-c21e-4cf8-a104-bdc1aabd2369
		summarizeBy: none
		sourceColumn: queryDialect

		annotation SummarizationSetBy = User

	column queryProcessingCpuTimeMs
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: 22878225-45a0-42de-b4f8-dc87c0ca098e
		summarizeBy: sum
		sourceColumn: queryProcessingCpuTimeMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column queryResultRows
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: 8e9aeee5-0f35-4f09-87b1-a34118cacde1
		summarizeBy: sum
		sourceColumn: queryResultRows

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column refreshParallelism
		dataType: int64
		formatString: 0
		displayFolder: Refresh (Write)
		lineageTag: 23999bda-41b8-4351-8914-0c4db6b8700e
		summarizeBy: none
		sourceColumn: refreshParallelism

		annotation SummarizationSetBy = User

	column tabularConnectionTimeoutMs
		dataType: int64
		formatString: 0
		displayFolder: General
		lineageTag: 024c07f2-dfa7-477f-be01-3ee1821e5d1f
		summarizeBy: sum
		sourceColumn: tabularConnectionTimeoutMs

		annotation SummarizationSetBy = Automatic

	column timeEnd
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		displayFolder: General
		lineageTag: e76d9c13-0eb1-4d82-a12a-a2388564ac39
		summarizeBy: none
		sourceColumn: timeEnd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column timeStart
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		displayFolder: General
		lineageTag: 999d7d41-6462-4f77-b358-49528b2003e4
		summarizeBy: none
		sourceColumn: timeStart

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column totalCpuTimeMs
		dataType: int64
		formatString: 0
		displayFolder: General
		lineageTag: 682e42af-86f4-4c77-9426-e12e20aac84b
		summarizeBy: sum
		sourceColumn: totalCpuTimeMs

		annotation SummarizationSetBy = Automatic

	column vertipaqJobCpuTimeMs
		dataType: int64
		formatString: 0
		displayFolder: General
		lineageTag: 548be257-b84b-4305-829c-a14e3652a81e
		summarizeBy: sum
		sourceColumn: vertipaqJobCpuTimeMs

		annotation SummarizationSetBy = Automatic

	column vertipaqTotalRows
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Refresh (Write)
		lineageTag: e360842d-610d-41fd-91fb-d41e1184291b
		summarizeBy: sum
		sourceColumn: vertipaqTotalRows

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dimDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 6ebe9f3a-bc11-446e-b89d-84fe44544a9c
		summarizeBy: none
		sourceColumn: dimDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PowerBIWorkspaceId
		dataType: string
		isHidden
		lineageTag: 20782388-cf64-43a5-83f9-d0e02cfcf14f
		summarizeBy: none
		sourceColumn: PowerBIWorkspaceId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PremiumCapacityId
		dataType: string
		lineageTag: 142e02d1-0b10-4c3b-8f60-bdd047b179c9
		summarizeBy: none
		sourceColumn: PremiumCapacityId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column User
		dataType: string
		lineageTag: 63341e65-8600-4eaa-96bb-29ea0cccbe98
		summarizeBy: none
		sourceColumn: User

		annotation SummarizationSetBy = Automatic

	column ExecutingUser
		dataType: string
		lineageTag: f329e7b5-02f3-465f-9896-b966de5ac032
		summarizeBy: none
		sourceColumn: ExecutingUser

		annotation SummarizationSetBy = Automatic

	column effectiveClaims
		dataType: string
		lineageTag: b6d44429-eab0-4f83-b82e-7350ef1f0cb5
		summarizeBy: none
		sourceColumn: effectiveClaims

		annotation SummarizationSetBy = Automatic

	column datasourceConnectionThrottleTimeMs
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: 38653a63-fbcd-44e2-8a3d-19d908f35220
		summarizeBy: sum
		sourceColumn: datasourceConnectionThrottleTimeMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column directQueryConnectionTimeMs
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: 0095902f-3552-4b3e-b53f-0183808189bb
		summarizeBy: sum
		sourceColumn: directQueryConnectionTimeMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column directQueryIterationTimeMs
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: e3154183-4adb-4f8a-8e73-26b0c40ac6b6
		summarizeBy: sum
		sourceColumn: directQueryIterationTimeMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column directQueryRequestCount
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: 9c5fe078-705c-4ffe-ac25-1a02439223ac
		summarizeBy: sum
		sourceColumn: directQueryRequestCount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column directQueryTimeoutMs
		dataType: int64
		formatString: #,0
		displayFolder: Query (Read)
		lineageTag: c944e7d6-d05f-4be1-acb0-3ddef082dda2
		summarizeBy: none
		sourceColumn: directQueryTimeoutMs

		annotation SummarizationSetBy = User

	column directQueryTotalRows
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: eb194a9a-d549-4f00-b1be-b29e9d848ff8
		summarizeBy: sum
		sourceColumn: directQueryTotalRows

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column directQueryTotalTimeMs
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Query (Read)
		lineageTag: 7a90f684-2826-4e09-a23a-8c06e2ab10b0
		summarizeBy: sum
		sourceColumn: directQueryTotalTimeMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PowerBIWorkspaceName
		dataType: string
		isHidden
		lineageTag: ef7fdba3-6cff-4166-b25a-394b8f709ca7
		summarizeBy: none
		sourceColumn: PowerBIWorkspaceName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StatusCode
		dataType: int64
		formatString: 0
		lineageTag: 17f0739a-d47b-46c6-8c35-c2078f6ba67a
		summarizeBy: none
		sourceColumn: StatusCode

		annotation SummarizationSetBy = User

	column ErrorMessage
		dataType: string
		lineageTag: 1531a322-5723-476e-b8d2-8941920c262d
		summarizeBy: none
		sourceColumn: ErrorMessage

		annotation SummarizationSetBy = Automatic

	column LogCnt
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 94ec36c4-f181-4cdf-b9d0-2a826e10d599
		summarizeBy: sum
		sourceColumn: LogCnt

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ApplicationName
		dataType: string
		lineageTag: 3e5cde74-e758-4135-8ff3-137ed84aa1b7
		summarizeBy: none
		sourceColumn: ApplicationName

		annotation SummarizationSetBy = Automatic

	column capacityThrottlingMs
		dataType: int64
		formatString: 0
		lineageTag: d62f167f-b2bc-4e9e-94a2-1b6de2a869d4
		summarizeBy: sum
		sourceColumn: capacityThrottlingMs

		annotation SummarizationSetBy = Automatic

	partition ExecutionMetrics = m
		mode: import
		source = ```
				let AnalyticsQuery =
				let Source = Json.Document(Web.Contents("https://api.loganalytics.io/v1/workspaces/" & #"Azure Log Analytics Workspace Id" & "/query", 
				[Query=[#"query"="
				set notruncation;
				set ClientRequestIdPrefix='BYOLA ExecutionMetrics';
				let FileTimeToDateTime = (fileTime: long) { unixtime_nanoseconds_todatetime((fileTime - 116444736000000000) * 100) };
				let RangeStartTime = ago(" & Number.ToText(#"Days Ago To Start") & "d);
				let RangeEndTime = ago(" & Number.ToText(#"Days Ago To Finish") & "d);
				let dbid = '"& _ArtifactId &"';
				let wkspid = '"& _WorkspaceId &"';
				let ConvertIntendedUsage = (enum: int) { case(enum == 0, 'Default', enum == 1, 'Scheduled', enum == 2, 'Interactive', enum == 3, 'Service', 'NA') };
				let window = PowerBIDatasetsWorkspace
				| extend TimeGenerated=TimeGenerated+"& Number.ToText(#"UTC Offset Hours") &"h 
				| where TimeGenerated >=RangeStartTime-7h and TimeGenerated <RangeEndTime+15m 
				| where PowerBIWorkspaceId has wkspid
				| extend effectiveClaims=coalesce(Identity.effectiveClaims.upn, customData=Identity.effectiveClaims.customData)
				;
				let ExecutionMetrics = window | where OperationName == 'ExecutionMetrics'
				| summarize arg_max(TimeGenerated, ArtifactId, ArtifactName, PowerBIWorkspaceId, PowerBIWorkspaceName, PremiumCapacityId, User, ExecutingUser, effectiveClaims, CorrelationId, e=EventText, ApplicationName) by XmlaRequestId
				;
				let NoExecutionMetrics = window | where ArtifactId !=''
				| where OperationName startswith 'ProgressReport' and OperationDetailName != 'ParallelSession' or OperationName startswith 'Command' or OperationName startswith 'Query'
				| summarize arg_min(timeStart=TimeGenerated, ArtifactId, ArtifactName, PowerBIWorkspaceId, PowerBIWorkspaceName, PremiumCapacityId, User, ExecutingUser, effectiveClaims, ApplicationName), arg_max(timeEnd=TimeGenerated, opStatus=Status) by XmlaRequestId
				| join kind=leftanti (ExecutionMetrics | summarize by XmlaRequestId) on XmlaRequestId
				;
				ExecutionMetrics
				| extend operationType=
				    iif(
				    e has '\""commandType\"": 56',
				    'Cancel'  //No ArtifactId, get from the last engine trace
				    ,
				    iif(
				        e has '\""commandType\"": 67',
				        'Backup'  //No ArtifactId, get from the last engine trace
				    ,
				        iif(
				            e has '\""commandType\"": 68',
				            'Restore' 
				    ,
				            iif(
				                e has '\""commandType\"": 2' and e !has 'discoverType' or e has 'refreshParallelism' or e has '\""queryDialect\"": 4',
				                'Refresh (Write)'
				    ,
				                iff(
				                    e has 'queryDialect' and e !has 'intendedUsage',
				                    'Query (Read)'
				    ,
				                    iif(
				                        e has 'queryDialect' and e has '\""intendedUsage\"": 3',
				                        'Data Loss Prevention Scan'
				    ,
				                        iif(
				                            e has 'queryDialect' and e has '\""intendedUsage\"": 1' or e has '\""commandType\"": 54',
				                            'Transaction'
				    ,
				                            iif(
				                                e has 'discoverType',
				                                'Discover' //30 DiscoverProperties 31 DiscoverSchemaRowsets 35 DiscoverXmlMetadata 74 DISCOVER_CSDL_METADATA 79 TabularSchemaTables 80 TabularSchemaColumns 82 TabularSchemaPartitions 84 TabularSchemaMeasures 110 TabularSchemaRoles 111 TabularSchemaRoleMemberships 112 TabularSchemaTablePermissions 117 TabularSchemaExpressions 125 TabularSchemaRefreshPolicies
				    ,
				                                iif(
				                                    e has 'qsoReplicaVersion' or e has 'errorCount',
				                                    'Image Load'
				    ,
				                                    iif(
				                                        e has '\""commandType\"": 44',
				                                        'ExtAuth'
				    ,
				                                        'Unknown'
				                                    )
				                                )
				                            )
				                        )
				                    )
				                )
				            )
				        )
				    )
				)
				| extend opStatus=iif(e has 'errorCount', 'Failed', 'Succeeded')
				| join kind=leftouter (window | where OperationName != 'ExecutionMetrics' and OperationDetailName != 'ExtAuth'
				    | summarize arg_max(TimeGenerated, ArtifactId) by XmlaRequestId)
				    on XmlaRequestId
				| extend ArtifactId=coalesce(ArtifactId, ArtifactId1)
				| where ArtifactId != '' and ArtifactId has dbid
				| join kind=leftouter (window | where OperationDetailName == 'Error'
				    | summarize arg_max(TimeGenerated, StatusCode, ErrorMessage=EventText) by XmlaRequestId, CorrelationId)
				    on XmlaRequestId, CorrelationId
				| extend e=parse_json(e) 
				| project ArtifactId, ArtifactName, PowerBIWorkspaceId, PremiumCapacityId, PowerBIWorkspaceName, operationType, opStatus, XmlaRequestId, StatusCode, ErrorMessage, User, ExecutingUser, effectiveClaims, ApplicationName
				//, e| evaluate bag_unpack(e) //columns updated dynamically when refreshing in the PBI Desktop.
				, timeStart=todatetime(e.timeStart), timeEnd=todatetime(e.timeEnd), durationMs=toint(e.durationMs), totalCpuTimeMs=toint(e.totalCpuTimeMs), approximatePeakMemConsumptionKB=toint(e.approximatePeakMemConsumptionKB), executionDelayMs=toint(e.executionDelayMs), vertipaqJobCpuTimeMs=toint(e.vertipaqJobCpuTimeMs), commandType=toint(e.commandType), errorCount=toint(e.errorCount), intendedUsage=toint(e.intendedUsage), discoverType=toint(e.discoverType), refreshParallelism=toint(e.refreshParallelism), vertipaqTotalRows =toint(e.vertipaqTotalRows), mEngineCpuTimeMs=toint(e.mEngineCpuTimeMs), mEnginePeakMemoryKB =toint(e.mEnginePeakMemoryKB), tabularConnectionTimeoutMs=toint(e.tabularConnectionTimeoutMs), qsoReplicaVersion=e.qsoReplicaVersion, queryDialect=toint(e.queryDialect), queryResultRows=toint(e.queryResultRows), queryProcessingCpuTimeMs=toint(e.queryProcessingCpuTimeMs), capacityThrottlingMs=toint(e.capacityThrottlingMs), directQueryRequestCount=toint(e.directQueryRequestCount), directQueryTotalRows=toint(e.directQueryTotalRows), datasourceConnectionThrottleTimeMs=toint(e.datasourceConnectionThrottleTimeMs), directQueryConnectionTimeMs=toint(e.directQueryConnectionTimeMs), directQueryExecutionTimeMs=toint(e.directQueryExecutionTimeMs), directQueryIterationTimeMs=toint(e.directQueryIterationTimeMs), directQueryTotalTimeMs=toint(e.directQueryTotalTimeMs), directQueryTimeoutMs=toint(e.directQueryTimeoutMs)
				| extend qsoReplicaVersion=FileTimeToDateTime(qsoReplicaVersion), intendedUsage=ConvertIntendedUsage(intendedUsage)
				| union NoExecutionMetrics
				| lookup (window | summarize LogCnt=count() by XmlaRequestId) on XmlaRequestId
				| extend dimDate=bin(timeStart, 30s)
				, ApplicationName=case (ApplicationName startswith 'PowerBI - Model Change Tracker', 'Power BI - Model Change Tracker'
				, ApplicationName startswith 'Power BI Desktop', 'Power BI Desktop', ApplicationName startswith 'DAX Studio', 'DAX Studio'
				, ApplicationName startswith 'Deployment Utility', 'Deployment Utility', ApplicationName startswith 'PowerBI - ExploreService', 'PowerBI - ExploreService'
				, ApplicationName startswith 'Microsoft SQL Server Management Studio', 'Microsoft SQL Server Management Studio'
				, ApplicationName startswith 'Tabular', 'TabularEditor', ApplicationName startswith 'PowerBI - NaturalLanguageService', 'PowerBI - NaturalLanguageService'
				, ApplicationName startswith 'SQL Server Profiler', 'SQL Server Profiler', ApplicationName)
				| where timeEnd >=RangeStartTime //and timeEnd <RangeEndTime
				| extend timeStart=timeStart+"& Number.ToText(#"UTC Offset Hours") &"h, timeEnd=timeEnd+"& Number.ToText(#"UTC Offset Hours") &"h, qsoReplicaVersion=qsoReplicaVersion+"& Number.ToText(#"UTC Offset Hours") &"h 
				",#"x-ms-app"="OmsAnalyticsPBI",#"prefer"="ai.response-thinning=true"],Timeout=#duration(0,0,5,0)])),
				TypeMap = #table(
				{ "AnalyticsTypes", "Type" }, 
				{ 
				{ "string",   Text.Type },
				{ "int",      Int32.Type },
				{ "long",     Int64.Type },
				{ "real",     Double.Type },
				{ "timespan", Duration.Type },
				{ "datetime", DateTimeZone.Type },
				{ "bool",     Logical.Type },
				{ "guid",     Text.Type },
				{ "dynamic",  Text.Type }
				}),
				DataTable = Source[tables]{0},
				Columns = Table.FromRecords(DataTable[columns]),
				ColumnsWithType = Table.Join(Columns, {"type"}, TypeMap , {"AnalyticsTypes"}),
				Rows = Table.FromRows(DataTable[rows], Columns[name]), 
				Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))
				in
				Table
				in AnalyticsQuery
				```

	annotation PBI_ResultType = Table

