table Query
	lineageTag: 7b523ff6-7678-4578-ac93-cb27cc13beb5

	measure 'Query Count' = COUNTROWS(Query)
		formatString: #,0
		lineageTag: 0608bb7c-7c85-40b4-86b8-1bda223c392a

		changedProperty = FormatString

	measure 'Query CPU (s)' = SUM(Query[CpuTimeMs])/1000
		formatString: #,0
		lineageTag: 4128ba0c-6000-4e73-9fdc-4aa6dbc148c1

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Query / Min' = DIVIDE([Query Count],([Query End]-[Query Start])*24*60)
		formatString: #,0
		lineageTag: 9bd1cb78-37d3-4975-a8e9-ccfb0df7ac00

		changedProperty = FormatString

	measure 'Report Count' = COUNTROWS(FILTER(VALUES(Query[ReportId]),Query[ReportId]<>""))
		formatString: #,0
		lineageTag: 7fba777b-0e25-4ed1-b551-312f9c2c2678

		changedProperty = FormatString

	measure 'User Count' = CALCULATE( DISTINCTCOUNT(ExecutionMetrics[User]), VALUES(Query[XmlaRequestId]))
		formatString: #,0
		lineageTag: 93e1a42b-f2eb-4b9a-9cfb-81c8a6cd874a

		changedProperty = FormatString

	measure 'Visual Count' = COUNTROWS(FILTER( VALUES(Query[VisualId]), Query[VisualId]<>""))
		formatString: #,0
		lineageTag: f03aa0dc-3aec-4ec6-adf0-3d28bc8b4785

		changedProperty = FormatString

	measure 'Dataset Count' = COUNTROWS(FILTER(VALUES('Query'[DatasetId]),'Query'[DatasetId]<>""))
		formatString: #,0
		lineageTag: 63c0e673-1762-4199-bde1-28da38c96aac

		changedProperty = FormatString

	measure 'Query CPU (ms)' = SUM(Query[CpuTimeMs])
		formatString: #,0
		lineageTag: 276f09eb-1615-4a28-abc9-48cb18b6925a

		changedProperty = FormatString

	measure 'Query Duration (ms)' = AVERAGE(Query[DurationMs])
		formatString: #,0
		lineageTag: 34752308-ab8e-47e6-a1b2-a5550db50e85

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'effectiveUser Count' = CALCULATE( DISTINCTCOUNT(ExecutionMetrics[effectiveClaims]), Query)
		formatString: #,0
		lineageTag: df9faa6d-68d9-4f76-b86c-12bec8601070

		changedProperty = FormatString

	measure 'executingUser Count' = CALCULATE( DISTINCTCOUNT(ExecutionMetrics[ExecutingUser]), Query)
		formatString: #,0
		lineageTag: 4e83fa0a-5c7e-4634-b8e8-4df7a2e28b8b

		changedProperty = FormatString

	measure 'Distinct Query' = DISTINCTCOUNT(Query[QueryHash])
		formatString: 0
		lineageTag: aa560731-753a-4ead-ae06-c8226e2416ec

	measure 'Query Request' = CALCULATE( DISTINCTCOUNT(Query[RequestID]), KEEPFILTERS(Query[RequestID]<>""))
		formatString: #,0
		lineageTag: c8447809-893d-441a-bb8f-ee580a46f833

		changedProperty = FormatString

	measure 'Failed Query' = CALCULATE([Query Count],Query[StatusCode]<0)
		formatString: #,0
		lineageTag: 22e2163e-ebc6-4e3a-9fde-4b07a8bcb2d3

		changedProperty = FormatString

	measure 'Failed Query %' = DIVIDE([Failed Query], [Query Count])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 7a0d153c-802b-4962-8936-b42719262d94

		changedProperty = FormatString

	measure 'Query Start' = CALCULATE( [Execution From] , Query)
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 93162eac-35bb-4fea-95fb-758adc069155

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Query End' = CALCULATE( [Execution To], Query)
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: 866290cb-5206-4ccb-a34a-42af6e1a31f5

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Queried DB' = CALCULATE( [Artifact], Query)
		formatString: 0
		lineageTag: 34478581-2e6d-4ca8-8798-a10d94f2cb4a

	measure 'Query CPU Max (s)' = MAX(Query[CpuTimeMs])/1000
		formatString: #,0
		lineageTag: 830d0c62-6e46-4d6a-bd67-d6d23f3822e8

	measure 'Query Duration Max (s)' = MAX(Query[DurationMs])/1000
		formatString: #,0
		lineageTag: d7da7070-dfa7-4cb5-a33f-e09e3444eb17

	measure 'Capacity Throttling Count' = CALCULATE([Query Count],ExecutionMetrics[capacityThrottlingMs]>0)
		formatString: #,0
		lineageTag: 000a1816-7773-4323-b3a2-f4041d10edfa

	measure 'Capacity Throttling %' = DIVIDE([Capacity Throttling Count],[Query Count])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 4a758f28-e0f8-46c8-851e-bfff4bb21445

	measure 'Dataset Mode' = SELECTEDVALUE(Query[DatasetMode])
		lineageTag: dcc5e236-8fb9-4d74-ac82-903ca3d3506f

	measure 'Query Duration (s)' = AVERAGE(Query[DurationMs])/1000
		formatString: #,0.0
		lineageTag: 971ade5a-294b-492e-9f96-a2731cd88600

	column XmlaRequestId
		dataType: string
		lineageTag: c6582012-41f7-46cd-a268-7d12235f7696
		summarizeBy: none
		sourceColumn: XmlaRequestId

		annotation SummarizationSetBy = Automatic

	column DurationMs
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 98e2f69b-5975-46da-9896-ab4343c66aa2
		summarizeBy: sum
		sourceColumn: DurationMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CpuTimeMs
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2de91c47-c57f-43db-9327-2826771dbf9e
		summarizeBy: sum
		sourceColumn: CpuTimeMs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OperationName
		dataType: string
		lineageTag: 12120f18-b3f3-4dff-9ce8-77ae3b7f8b6a
		summarizeBy: none
		sourceColumn: OperationName

		annotation SummarizationSetBy = Automatic

	column OperationDetailName
		dataType: string
		lineageTag: 1750f0c3-6885-412e-8ef7-755c474ba5db
		summarizeBy: none
		sourceColumn: OperationDetailName

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		lineageTag: 4c09b0a9-41cb-40b9-b777-3ad045aeb590
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6bc0211f-6f25-4d1f-b63b-5cdd18711e6e
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column StatusCode
		dataType: int64
		formatString: 0
		lineageTag: 452c982f-a2a0-48c2-b3ef-48eeb0faab21
		summarizeBy: none
		sourceColumn: StatusCode

		annotation SummarizationSetBy = User

	column EventText
		dataType: string
		lineageTag: 15f697a5-b562-46da-82a3-9ee4901c4e8a
		summarizeBy: none
		sourceColumn: EventText

		annotation SummarizationSetBy = Automatic

	column DatasetMode
		dataType: string
		lineageTag: 3dcfab93-a776-493c-8bcb-0f1a3d6ea8e9
		summarizeBy: none
		sourceColumn: DatasetMode

		annotation SummarizationSetBy = Automatic

	column DurationBucket
		dataType: string
		lineageTag: d2b7874d-256b-4319-a0d7-12037e59cee1
		summarizeBy: none
		sourceColumn: DurationBucket

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: 26030e39-25fb-44ce-ab80-f0045cab66eb
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column ReportId
		dataType: string
		lineageTag: 116dff83-4a3f-402c-870e-550991d3179c
		summarizeBy: none
		sourceColumn: ReportId

		annotation SummarizationSetBy = Automatic

	column VisualId
		dataType: string
		lineageTag: a3d577bd-9935-426e-93a0-23e6a59fd082
		summarizeBy: none
		sourceColumn: VisualId

		annotation SummarizationSetBy = Automatic

	column RequestID
		dataType: string
		lineageTag: a7ac7a90-44a4-4020-b43a-c3a6b82598a2
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column QueryHash
		dataType: string
		lineageTag: 791934d1-5586-47f1-b591-083c9330c23c
		summarizeBy: none
		sourceColumn: QueryHash

		annotation SummarizationSetBy = Automatic

	column ReplicaId
		dataType: string
		lineageTag: a80ddd16-8336-4ed6-9f7e-7620fc6e4578
		summarizeBy: none
		sourceColumn: ReplicaId

		annotation SummarizationSetBy = Automatic

	column RequestApp
		dataType: string
		lineageTag: b7f9cfb7-871e-49cb-9648-095a1c3cb15b
		summarizeBy: none
		sourceColumn: RequestApp

		annotation SummarizationSetBy = Automatic

	partition Query-702a0f16-b046-4435-a996-c1cde022b303 = m
		mode: import
		source = ```
				// let RangeStartTime = datetime("& DateTime.ToText(RangeStart, "yyyy-MM-dd HH:mm:ss") &");
				// let RangeEndTime = datetime("& DateTime.ToText(RangeEnd, "yyyy-MM-dd HH:mm:ss") &");
				let AnalyticsQuery =
				let Source = Json.Document(Web.Contents("https://api.loganalytics.io/v1/workspaces/" & #"Azure Log Analytics Workspace Id" & "/query", 
				[Query=[#"query"="
				set notruncation;
				set ClientRequestIdPrefix='BYOLA Query';
				let RangeStartTime = ago(" & Number.ToText(#"Days Ago To Start") & "d);
				let RangeEndTime = ago(" & Number.ToText(#"Days Ago To Finish") & "d);
				let dbid = '"& _ArtifactId &"';
				let wkspid = '"& _WorkspaceId &"';
				let window = PowerBIDatasetsWorkspace
				| extend TimeGenerated=TimeGenerated+"& Number.ToText(#"UTC Offset Hours") &"h 
				| where TimeGenerated >=RangeStartTime-7h and TimeGenerated <RangeEndTime+15m
				;
				window
				| where ArtifactId !='' and ArtifactId has dbid and PowerBIWorkspaceId has wkspid
				//| where OperationName == 'ExecutionMetrics' and ArtifactId !='' and ArtifactId has dbid and PowerBIWorkspaceId has wkspid
				// | extend e=EventText
				// | where e has 'queryDialect' and e !has 'intendedUsage' and e !has '\""queryDialect\"": 4'
				// | summarize by XmlaRequestId
				// | join kind=leftouter (window| where LogAnalyticsCategory == 'Query' and ArtifactId !='') on XmlaRequestId
				| where OperationName startswith 'Query'
				| summarize arg_max(endTime=TimeGenerated, DurationMs, CpuTimeMs, OperationName, OperationDetailName, Level, Status, StatusCode, DatasetMode, ReplicaId)
				, arg_min(startTime=TimeGenerated, XmlaProperties, ApplicationContext, EventText)
				by XmlaRequestId
				| where XmlaProperties !has 'PowerBIEIM' and XmlaProperties !has 'Data Loss Prevention Scan'
				| where endTime >=RangeStartTime and endTime <RangeEndTime
				| extend DurationBucket=case(DurationMs <1000, '[00s, 01s)', DurationMs <10000, '[01s, 10s)', DurationMs <30000, '[10s, 30s)', DurationMs <60000, '[30s, 60s)', DurationMs <225000, '[60s, 225s)', '[Over 225s)')
				| extend DatasetId=ApplicationContext.DatasetId, ReportId = ApplicationContext.Sources.[0].ReportId, VisualId = ApplicationContext.Sources.[0].VisualId
				| parse XmlaProperties with * '<DbpropMsmdRequestID>' RequestID '</DbpropMsmdRequestID>' *
				| parse kind=regex flags=Ui XmlaProperties with '(.?)[a-zA-Z]*<SspropInitAppName>' RequestApp '<' *
				| extend QueryHash=hash_md5(EventText)
				, RequestApp=case (RequestApp startswith 'PowerBI - Model Change Tracker', 'Power BI - Model Change Tracker'
				, RequestApp startswith 'Power BI Desktop', 'Power BI Desktop', RequestApp startswith 'DAX Studio', 'DAX Studio'
				, RequestApp startswith 'Deployment Utility', 'Deployment Utility', RequestApp startswith 'PowerBI - ExploreService', 'PowerBI - ExploreService'
				, RequestApp startswith 'Microsoft SQL Server Management Studio', 'Microsoft SQL Server Management Studio', RequestApp startswith 'Tabular', 'TabularEditor'
				, RequestApp startswith 'PowerBI - NaturalLanguageService', 'PowerBI - NaturalLanguageService'
				, RequestApp startswith 'SQL Server Profiler', 'SQL Server Profiler', RequestApp)
				| project-away XmlaProperties, ApplicationContext, startTime, endTime
				",#"x-ms-app"="OmsAnalyticsPBI",#"prefer"="ai.response-thinning=true"],Timeout=#duration(0,0,4,0)])),
				TypeMap = #table(
				{ "AnalyticsTypes", "Type" }, 
				{ 
				{ "string",   Text.Type },
				{ "int",      Int32.Type },
				{ "long",     Int64.Type },
				{ "real",     Double.Type },
				{ "timespan", Duration.Type },
				{ "datetime", DateTimeZone.Type },
				{ "bool",     Logical.Type },
				{ "guid",     Text.Type },
				{ "dynamic",  Text.Type }
				}),
				DataTable = Source[tables]{0},
				Columns = Table.FromRecords(DataTable[columns]),
				ColumnsWithType = Table.Join(Columns, {"type"}, TypeMap , {"AnalyticsTypes"}),
				Rows = Table.FromRows(DataTable[rows], Columns[name]), 
				Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))
				in
				Table
				in
				    AnalyticsQuery
				```

	annotation PBI_ResultType = Table

