table EndTime
	lineageTag: 5c2f07a8-da1e-424f-a345-1a2f3a6cd25d

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 8a0b5031-53f5-4dda-86d7-a5b60376192d
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Hour
		dataType: int64
		formatString: 0
		lineageTag: b4fcd52d-f86b-4109-8971-df2d9feb2a0c
		summarizeBy: sum
		sourceColumn: Hour

		annotation SummarizationSetBy = Automatic

	column Minute
		dataType: int64
		formatString: 0
		lineageTag: ab049d2d-4480-4d1a-bc6a-62f92089805c
		summarizeBy: sum
		sourceColumn: Minute

		annotation SummarizationSetBy = Automatic

	column AM/PM
		dataType: string
		lineageTag: 1b44bb0f-8f8a-465b-8cdc-2b7c130c45a1
		summarizeBy: none
		sourceColumn: AM/PM

		annotation SummarizationSetBy = Automatic

	column 'Time (h)'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 9c742960-304f-4838-9c0c-55f6c0b761e5
		summarizeBy: none
		sourceColumn: Time (h)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Time (m)'
		dataType: dateTime
		formatString: Long Time
		lineageTag: e57dc6e7-72b0-4a0d-b8e2-c4c3ad5d4d5a
		summarizeBy: none
		sourceColumn: Time (m)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Second
		dataType: int64
		lineageTag: f873db87-02bf-47e1-8e98-ef048fc2f111
		summarizeBy: sum
		sourceColumn: Second

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hour Label'
		dataType: string
		lineageTag: 6a8dea80-8a4c-4bdf-8bf9-f5ef7d9d19f2
		summarizeBy: none
		sourceColumn: Hour Label

		annotation SummarizationSetBy = Automatic

	column 'Minute Label'
		dataType: string
		lineageTag: 9df2c2e3-0daf-4aa2-86d6-45800f9eb8a1
		summarizeBy: none
		sourceColumn: Minute Label

		annotation SummarizationSetBy = Automatic

	column 'Second Label'
		dataType: string
		lineageTag: 07fc409d-9a4c-4fdf-8ba6-0c6e91fbc568
		summarizeBy: none
		sourceColumn: Second Label

		annotation SummarizationSetBy = Automatic

	column Hour(AM/PM)
		dataType: dateTime
		formatString: h:nn AM/PM
		lineageTag: 49ddca95-a979-46bc-bd4c-96e3d99bd022
		summarizeBy: none
		sourceColumn: Hour(AM/PM)

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition EndTime-54cc40b2-0d8e-4f0c-8989-84bdc7297838 = m
		mode: import
		source =
				let
				    Source = List.Times(#time(0,0,0),24*60*60,#duration(0,0,0,1)),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Time"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Time", type time}}),
				    #"Added Time (h)" = Table.AddColumn(#"Changed Type", "Time (h)", each #time(Time.Hour([Time]),0 ,0) as time),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Time (h)",{{"Time (h)", type time}}),
				    #"Added Time (m)" = Table.AddColumn(#"Changed Type2", "Time (m)", each #time(Time.Hour([Time]),Time.Minute([Time]),0) as time),
				    #"Changed Type Time (m)" = Table.TransformColumnTypes(#"Added Time (m)",{{"Time (m)", type time}}),
				    #"Inserted Hour" = Table.AddColumn(#"Changed Type Time (m)", "Hour", each Time.Hour([Time]), Int64.Type),
				    #"Inserted Minute" = Table.AddColumn(#"Inserted Hour", "Minute", each Time.Minute([Time]), Int64.Type),
				    #"Inserted Second" = Table.AddColumn(#"Inserted Minute", "Second", each Time.Second([Time]), type number),
				    #"Added Conditional Column" = Table.AddColumn(#"Inserted Second", "AM/PM", each if [Hour] < 12 then "AM" else "PM"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"AM/PM", type text}}),
				    #"Inserted Prefix" = Table.AddColumn(#"Changed Type1", "Prefix", each "0" & Text.From([Hour], "en-NZ"), type text),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Prefix",{{"Prefix", "Hour Label"}}),
				    #"Extracted Last Characters" = Table.TransformColumns(#"Renamed Columns2", {{"Hour Label", each Text.End(_, 2), type text}}),
				    #"Inserted Prefix1" = Table.AddColumn(#"Extracted Last Characters", "Prefix", each "0" & Text.From([Minute], "en-NZ"), type text),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Prefix1",{{"Prefix", "Minute Label"}}),
				    #"Extracted Last Characters1" = Table.TransformColumns(#"Renamed Columns3", {{"Minute Label", each Text.End(_, 2), type text}}),
				    #"Inserted Prefix2" = Table.AddColumn(#"Extracted Last Characters1", "Prefix", each "0" & Text.From([Second], "en-NZ"), type text),
				    #"Renamed Columns4" = Table.RenameColumns(#"Inserted Prefix2",{{"Prefix", "Second Label"}}),
				    #"Extracted Last Characters2" = Table.TransformColumns(#"Renamed Columns4", {{"Second Label", each Text.End(_, 2), type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Extracted Last Characters2", "Time (h)", "Time (h) - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"Time (h) - Copy", "Hour(AM/PM)"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Hour(AM/PM)", type time}})
				in
				    #"Changed Type3"

	annotation PBI_ResultType = Table

