table StartTime
	lineageTag: 4b57054e-68b0-4b3c-9083-ec40aafd9219

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 38222e14-1b19-4a35-bd7d-41c5c2a97036
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Hour
		dataType: int64
		formatString: 0
		lineageTag: 5494251a-3789-42b3-b340-f0df42b816fb
		summarizeBy: sum
		sourceColumn: Hour

		annotation SummarizationSetBy = Automatic

	column Minute
		dataType: int64
		formatString: 0
		lineageTag: b14e66b8-85ed-49fd-8e6b-a5557f633899
		summarizeBy: sum
		sourceColumn: Minute

		annotation SummarizationSetBy = Automatic

	column Second
		dataType: int64
		lineageTag: e82f80d5-184d-4794-9bf8-d580a297c1d5
		summarizeBy: sum
		sourceColumn: Second

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AM/PM
		dataType: string
		lineageTag: 493e5acc-5ef1-445a-ace9-8fe1d7399461
		summarizeBy: none
		sourceColumn: AM/PM

		annotation SummarizationSetBy = Automatic

	column 'Hour Label'
		dataType: string
		lineageTag: ead907f8-bc50-4bda-8af7-82b219713c81
		summarizeBy: none
		sourceColumn: Hour Label

		annotation SummarizationSetBy = Automatic

	column 'Minute Label'
		dataType: string
		lineageTag: f46e1793-4551-468f-8cb6-58f64526d554
		summarizeBy: none
		sourceColumn: Minute Label

		annotation SummarizationSetBy = Automatic

	column 'Second Label'
		dataType: string
		lineageTag: c938f5e3-d028-48d8-8dc0-f35de08f8947
		summarizeBy: none
		sourceColumn: Second Label

		annotation SummarizationSetBy = Automatic

	column 'Time (h)'
		dataType: dateTime
		formatString: Long Time
		lineageTag: fe5a0099-9347-4817-8e28-afc701f212fa
		summarizeBy: none
		sourceColumn: Time (h)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Time (m)'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 51d647c2-4ba6-4699-b1e4-a3bbb9b6f574
		summarizeBy: none
		sourceColumn: Time (m)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Hour(AM/PM)
		dataType: dateTime
		formatString: h:nn AM/PM
		lineageTag: de2beeac-9fb8-43d0-99d3-fe5503cfd980
		summarizeBy: none
		sourceColumn: Hour(AM/PM)

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition StartTime-76ba2200-5f9e-48d2-9190-0f4c91e0c8f5 = m
		mode: import
		source =
				let
				    Source = List.Times(#time(0,0,0),24*60*60,#duration(0,0,0,1)),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Time"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Time", type time}}),
				    #"Added Time (h)" = Table.AddColumn(#"Changed Type", "Time (h)", each #time(Time.Hour([Time]),0 ,0) as time),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Time (h)",{{"Time (h)", type time}}),
				    #"Added Time (m)" = Table.AddColumn(#"Changed Type2", "Time (m)", each #time(Time.Hour([Time]),Time.Minute([Time]),0) as time),
				    #"Changed Type Time (m)" = Table.TransformColumnTypes(#"Added Time (m)",{{"Time (m)", type time}}),
				    #"Inserted Hour" = Table.AddColumn(#"Changed Type Time (m)", "Hour", each Time.Hour([Time]), Int64.Type),
				    #"Inserted Minute" = Table.AddColumn(#"Inserted Hour", "Minute", each Time.Minute([Time]), Int64.Type),
				    #"Inserted Second" = Table.AddColumn(#"Inserted Minute", "Second", each Time.Second([Time]), type number),
				    #"Added Conditional Column" = Table.AddColumn(#"Inserted Second", "AM/PM", each if [Hour] < 12 then "AM" else "PM"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"AM/PM", type text}}),
				    #"Inserted Prefix" = Table.AddColumn(#"Changed Type1", "Prefix", each "0" & Text.From([Hour], "en-NZ"), type text),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Prefix",{{"Prefix", "Hour Label"}}),
				    #"Extracted Last Characters" = Table.TransformColumns(#"Renamed Columns2", {{"Hour Label", each Text.End(_, 2), type text}}),
				    #"Inserted Prefix1" = Table.AddColumn(#"Extracted Last Characters", "Prefix", each "0" & Text.From([Minute], "en-NZ"), type text),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Prefix1",{{"Prefix", "Minute Label"}}),
				    #"Extracted Last Characters1" = Table.TransformColumns(#"Renamed Columns3", {{"Minute Label", each Text.End(_, 2), type text}}),
				    #"Inserted Prefix2" = Table.AddColumn(#"Extracted Last Characters1", "Prefix", each "0" & Text.From([Second], "en-NZ"), type text),
				    #"Renamed Columns4" = Table.RenameColumns(#"Inserted Prefix2",{{"Prefix", "Second Label"}}),
				    #"Extracted Last Characters2" = Table.TransformColumns(#"Renamed Columns4", {{"Second Label", each Text.End(_, 2), type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Extracted Last Characters2", "Time (h)", "Time (h) - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"Time (h) - Copy", "Hour(AM/PM)"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Hour(AM/PM)", type time}})
				in
				    #"Changed Type3"

	annotation PBI_ResultType = Table

