table 'Suboperation - Refresh'
	lineageTag: 0a46aa30-01a0-4eb7-a69e-1e074906154b

	column 'Duration (ms)'
		dataType: int64
		formatString: 0
		lineageTag: 5b307e1c-919a-4e7f-84da-fc62e8c2495c
		summarizeBy: sum
		sourceColumn: Duration (ms)

		annotation SummarizationSetBy = Automatic

	column ExecutingUser
		dataType: string
		lineageTag: 353d6777-a640-459d-98e9-3aea67851cc9
		summarizeBy: none
		sourceColumn: ExecutingUser

		annotation SummarizationSetBy = Automatic

	column Operation
		dataType: string
		lineageTag: 368f7606-2438-403e-ba91-ae915fa65798
		summarizeBy: none
		sourceColumn: Operation

		annotation SummarizationSetBy = Automatic

	column PremiumCapacityId
		dataType: string
		lineageTag: 34d52e08-2e39-4c53-9571-d93e05eda102
		summarizeBy: none
		sourceColumn: PremiumCapacityId

		annotation SummarizationSetBy = Automatic

	column TenantId
		dataType: string
		lineageTag: 250615ca-75e9-4c25-ad91-5690840fe4fd
		summarizeBy: none
		sourceColumn: TenantId

		annotation SummarizationSetBy = Automatic

	column TextDataHash
		dataType: string
		lineageTag: 89a089e9-6575-4f31-9b72-dd503cda4574
		summarizeBy: none
		sourceColumn: TextDataHash

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 87b601cd-f584-4457-824d-575e08341bac
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column User
		dataType: string
		lineageTag: 8026b7ee-9413-4c7a-a674-d498bfc1f44b
		summarizeBy: none
		sourceColumn: User

		annotation SummarizationSetBy = Automatic

	column WorkspaceId
		dataType: string
		lineageTag: aca85496-00a0-41b5-82f2-5da432ec9943
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column ResourceId
		dataType: string
		lineageTag: 90c6b7fc-f20c-4d2e-806e-c6bc9c478312
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column SubscriptionId
		dataType: string
		lineageTag: 90a7e5dc-8405-46a0-897c-cac373f6819b
		summarizeBy: none
		sourceColumn: SubscriptionId

		annotation SummarizationSetBy = Automatic

	column 'Start Date'
		dataType: dateTime
		formatString: dd-mmm-yyyy
		lineageTag: 0aebdefd-f6a7-4c5a-8650-35fe80ebd72a
		summarizeBy: none
		sourceColumn: Start Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Start Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 4e86eec4-6072-4cd3-a4d3-e7043b613a48
		summarizeBy: none
		sourceColumn: Start Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Start Date/Time'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss AM/PM
		lineageTag: 9fcdcd1b-8ed3-457e-8ed5-c1d864873f56
		summarizeBy: none
		sourceColumn: Start Date/Time

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'ObjectTable + ObjectName' =
			
			'Suboperation - Refresh'[Object Parent Name] & " - " & 'Suboperation - Refresh'[Object]
		dataType: string
		lineageTag: 4cedc084-129f-4879-9a82-2df32f444a22
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column ApplicationName
		dataType: string
		lineageTag: 80f89d0e-4361-4df9-9cfa-eb268abb18b0
		summarizeBy: none
		sourceColumn: ApplicationName

		annotation SummarizationSetBy = Automatic

	column CpuTimeMs
		dataType: int64
		formatString: #,0
		lineageTag: 31d9be39-f0e8-4ebe-8665-cb86a5438c37
		summarizeBy: sum
		sourceColumn: CpuTimeMs

		annotation SummarizationSetBy = Automatic

	column EventText
		dataType: string
		lineageTag: 5916dd39-8460-4119-be8a-7247fa806512
		summarizeBy: none
		sourceColumn: EventText

		annotation SummarizationSetBy = Automatic

	column 'End Date/Time'
		dataType: dateTime
		formatString: dd-mmm-yyyy hh:nn:ss AM/PM
		lineageTag: fbfcac0d-4181-4696-a734-d71ac0dacfb0
		summarizeBy: none
		sourceColumn: End Date/Time

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Operation Detail'
		dataType: string
		lineageTag: e0307f4b-469b-44ab-a7c3-a62cd6a64c58
		summarizeBy: none
		sourceColumn: Operation Detail

		annotation SummarizationSetBy = Automatic

	column SourceSystem
		dataType: string
		lineageTag: 2be98913-f9c2-47de-ab3b-d2eeb75aa27e
		summarizeBy: none
		sourceColumn: SourceSystem

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 8f5737fa-3eee-437f-8849-31e4be35dd48
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column StatusCode
		dataType: string
		lineageTag: 8eb10b67-c9d4-401b-be44-ddb1e3e3c14b
		summarizeBy: none
		sourceColumn: StatusCode

		annotation SummarizationSetBy = Automatic

	column XmlaRequestId
		dataType: string
		lineageTag: b27df79c-0ac7-4c7b-8305-0967b05fbb37
		summarizeBy: none
		sourceColumn: XmlaRequestId

		annotation SummarizationSetBy = Automatic

	column XmlaSessionId
		dataType: string
		lineageTag: 91aa613d-c310-434e-8b66-d21e8f89b904
		summarizeBy: none
		sourceColumn: XmlaSessionId

		annotation SummarizationSetBy = Automatic

	column XmlaObjectPath
		dataType: string
		lineageTag: f11ab72c-3688-4257-b091-417c4f757d05
		summarizeBy: none
		sourceColumn: XmlaObjectPath

		annotation SummarizationSetBy = Automatic

	column Object
		dataType: string
		lineageTag: 565e0bf1-f88b-4658-a4d5-1c718115832a
		summarizeBy: none
		sourceColumn: Object

		annotation SummarizationSetBy = Automatic

	column 'Object Parent Name'
		dataType: string
		lineageTag: 6d981ca7-e815-4d19-b616-fa306a3b3960
		summarizeBy: none
		sourceColumn: Object Parent Name

		annotation SummarizationSetBy = Automatic

	column Workspace
		dataType: string
		lineageTag: 31e72ace-1a32-404e-b6ce-392684e2fb36
		summarizeBy: none
		sourceColumn: Workspace

		annotation SummarizationSetBy = Automatic

	column ArtifactKind
		dataType: string
		lineageTag: 647ebc37-742e-489e-843d-e94585c536b7
		summarizeBy: none
		sourceColumn: ArtifactKind

		annotation SummarizationSetBy = Automatic

	column DatasetMode
		dataType: string
		lineageTag: 0fa3f401-e2f7-4503-a06c-c49e135daea4
		summarizeBy: none
		sourceColumn: DatasetMode

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: d9f9cdf7-8497-4cf2-a80f-5a3d1534a476
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column Dataset
		dataType: string
		lineageTag: 060bdea7-c95c-46e2-b922-2fee55f5ddf9
		summarizeBy: none
		sourceColumn: Dataset

		annotation SummarizationSetBy = Automatic

	column Microsecond
		dataType: int64
		formatString: 0
		lineageTag: ccfbd4d2-4f21-4fb8-b581-7d529796eac5
		summarizeBy: sum
		sourceColumn: Microsecond

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'End Time' = 'Suboperation - Refresh'[End Date/Time]
		dataType: dateTime
		formatString: Long Time
		lineageTag: 9660c937-2492-42c9-a73e-9d69b6e1a49a
		summarizeBy: none
		isDataTypeInferred

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Suboperation - Refresh-cd1ef9b4-26c1-4560-8bd7-2b66f96909f3' = m
		mode: import
		source = ```
				let
				    Source = Table.Combine({RefreshSuboperations, RelatedRefreshOperationsForSubOpTable}),
				    LastDot = Table.AddColumn(Source, "LastDot", each Text.PositionOf([XmlaObjectPath], ".", Occurrence.Last)),
				    #"Len(xmlObject)" = Table.AddColumn(LastDot, "xmlObjectLength", each Text.Length([XmlaObjectPath])),
				    ObjectName = Table.AddColumn(#"Len(xmlObject)", "Object Name", each Text.End([XmlaObjectPath], [xmlObjectLength] - ([LastDot]+1))),
				    #"Remainder before last dot" = Table.AddColumn(ObjectName, "Remainder", each Text.BeforeDelimiter([XmlaObjectPath], ".", {0, RelativePosition.FromEnd})),
				    #"2nd LastDot" = Table.AddColumn(#"Remainder before last dot", "2nd Last Dot", each Text.PositionOf([Remainder], ".", Occurrence.Last)),
				    #"2nd Len" = Table.AddColumn(#"2nd LastDot", "2nd Len(xmlObject)", each Text.Length([Remainder])),
				    #"Added Custom" = Table.AddColumn(#"2nd Len", "Object Parent Name", each Text.End([Remainder], [#"2nd Len(xmlObject)"] - ([2nd Last Dot]+1))),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"LastDot", "xmlObjectLength", "Remainder", "2nd Last Dot", "2nd Len(xmlObject)"}),
				    
				    #"Added Start DateTime (UTC offset)" = Table.AddColumn(#"Removed Columns", "Start DateTime", each[TimeGenerated] + #duration(0,Number.RoundDown(#"UTC Offset Hours"),Number.RoundDown(60 * Number.Mod(#"UTC Offset Hours", 1)),0),type datetime),
				    #"Inserted Date" = Table.AddColumn(#"Added Start DateTime (UTC offset)", "Start Date", each DateTime.Date([Start DateTime]), type date),
				    #"Inserted Time" = Table.AddColumn(#"Inserted Date", "Start Time (s)", each DateTime.Time([Start DateTime]), type time),
				   //#"Renamed Columns" = Table.RenameColumns(#"Start Time (s)",{{"DurationMs", "Duration (ms)"}}),
				    #"Added End Date/Time" = Table.AddColumn(#"Inserted Time", "EndTime", each [Start DateTime] + #duration(0, 0, 0, [#"Duration (ms)"] / 1000)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added End Date/Time",{{"Start Date", type date}, {"Start DateTime", type datetimezone}, {"EndTime", type datetimezone}}),
				    #"Removed StartTime, TimeGenerated" = Table.RemoveColumns(#"Changed Type",{"TimeGenerated", "StartTime"}),
				    
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed StartTime, TimeGenerated",{{"CpuTimeMs", Int64.Type}, {"Duration (ms)", Int64.Type}, {"Start DateTime", type datetimezone}, {"Start Date", type date}, {"Start Time (s)", type time}, {"EndTime", type datetimezone}, {"TextDataHash", type text}}),
				    #"Removed Duplicates1" = Table.Distinct(#"Changed Type1"),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates1",{{"EndTime", "End Date/Time"}, {"Object Name", "Object"}, {"OperationName", "Operation"}, {"OperationDetailName", "Operation Detail"}, {"Start DateTime", "Start Date/Time"}, {"WorkspaceName", "Workspace"}, {"Start Time (s)", "Start Time"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Exception

