table 'Top N Selector'
	lineageTag: c56ddd26-af48-401e-8e4c-537d306e5942

	measure Rank_By_Duration =
			
			IF (
			    ISINSCOPE ( Operation[EventText] ),
			    INT (
			        RANKX (
			            CALCULATETABLE (
			                GROUPBY (
			                    Operation,
			                    Operation[EventText],
			                    Operation[ReportId],
			                    Operation[Dataset],
			                    Operation[Workspace],
			                    Operation[PremiumCapacityId]
			                ),
			                ALLSELECTED (
			                    Operation[EventText],
			                    Operation[ReportId],
			                    Operation[Dataset],
			                    Operation[Workspace],
			                    Operation[PremiumCapacityId]
			                )
			            ),
			            CALCULATE (
			                PERCENTILE.INC (
			                    Operation[Duration (ms)],
			                    .5
			                )
			            )
			        )
			            <= MAX ( 'Top N Selector'[Value] )
			    )
			)
		formatString: #,0
		lineageTag: a846066c-59e0-47cf-a0ea-1b5b7a81e58d

	measure Rank_By_CPU% =
			
			IF (
			    ISINSCOPE ( Operation[EventText] ),
			    INT (
			        RANKX (
			            CALCULATETABLE (
			                GROUPBY (
			                    Operation,
			                    Operation[EventText],
			                    Operation[ReportId],
			                    Operation[Dataset],
			                    Operation[Workspace],
			                    Operation[PremiumCapacityId]
			                ),
			                ALLSELECTED (
			                    Operation[EventText],
			                    Operation[ReportId],
			                    Operation[Dataset],
			                    Operation[Workspace],
			                    Operation[PremiumCapacityId]
			                )
			            ),
			            CALCULATE (
			                DIVIDE (
			                    [CPU Time Std Dev],
			                    [CPU Time Mean]
			                )
			            )
			        )
			            <= MAX ( 'Top N Selector'[Value] )
			    )
			)
		formatString: #,0
		lineageTag: 9d7ba982-cb6b-41ef-bde6-0e1ea5d402b2

	measure 'Title_by CPU%' =
			
			"Top "
			    & SELECTEDVALUE ( 'Top N Selector'[SelectorSort] ) & " queries by CPU variability"
		lineageTag: b729353e-978a-4bbf-8df8-76dac7414460

	measure 'Title_by Duration' =
			
			"Top "
			    & SELECTEDVALUE ( 'Top N Selector'[SelectorSort] ) & " queries by duration P50"
		lineageTag: 860c2713-d337-404b-8050-4c828025aac1

	measure 'Rank_By_CPU time' = ```
			
			IF (
			    ISINSCOPE ( Operation[Workspace] ),
			    INT (
			        RANKX (
			            CALCULATETABLE (
			                GROUPBY (
			                    Operation,
			                    Operation[ReportId],
			                    Operation[Workspace],
			                    Operation[PremiumCapacityId]
			                ),
			                ALLSELECTED (
			                    Operation[ReportId],
			                    Operation[Workspace],
			                    Operation[PremiumCapacityId]
			                )
			            ),
			            CALCULATE (
			                SWITCH (
			                    MIN ( Scenario[ID] ),
			                    1, [CPU Time - Refresh],
			                    2, [CPU Time - Query],
			                    [CPU Time (ms)]
			                )
			            )
			        )
			            <= MAX ( 'Top N Selector'[Value] )
			    )
			)
			
			```
		formatString: 0
		lineageTag: ea744942-1409-48e0-95c1-340ed4e1c5f1

	measure Rank_Reports_By_CPUTime =
			
			IF (
			    ISINSCOPE ( Operation[ReportId] ),
			    INT (
			        RANKX (
			            CALCULATETABLE (
			                GROUPBY (
			                    Operation,
			                    Operation[ReportId]
			                ),
			                ALLSELECTED ( Operation[ReportId] )
			            ),
			            CALCULATE (
			                SUM ( Operation[CPUTime (ms)] )
			            )
			        )
			            <= MAX ( 'Top N Selector'[Value] )
			    )
			)
		formatString: 0
		lineageTag: be9b4acb-ad83-487f-897c-b09f3ce1479e

	measure Rank_User_By_CPUTime =
			
			IF (
			    ISINSCOPE (  User[Executing User]),
			    INT (
			        RANKX (
			            CALCULATETABLE (
			                GROUPBY (
			                    User,
			                     User[Executing User]
			                ),
			                ALLSELECTED (  User[Executing User] )
			            ),
			            CALCULATE (
			                SUM ( Operation[CPUTime (ms)] )
			            )
			        )
			            <= MAX ( 'Top N Selector'[Value] )
			    )
			)
		formatString: 0
		lineageTag: 58badb84-5d08-4c6e-a6c5-50011651be43

	measure Rank_User_By_Queries = ```
			IF (
			    ISINSCOPE (  User[Executing User]),
			    INT (
			        RANKX (
			            CALCULATETABLE (
			                GROUPBY (
			                    User,
			                     User[Executing User]
			                ),
			                ALLSELECTED (  User[Executing User] )
			            ),
			            CALCULATE (
			                [Queries]
			            )
			        )
			            <= MAX ( 'Top N Selector'[Value] )
			    )
			)
			
			```
		formatString: 0
		lineageTag: d4d7b45a-eb50-4d2a-a535-5dd2be474b8b

	measure Rank_User_By_Operations =
			
			IF (
			    ISINSCOPE (  User[Executing User]),
			    INT (
			        RANKX (
			            CALCULATETABLE (
			                GROUPBY (
			                    User,
			                     User[Executing User]
			                ),
			                ALLSELECTED (  User[Executing User] )
			            ),
			            CALCULATE (
			                [Operations]
			            )
			        )
			            <= MAX ( 'Top N Selector'[Value] )
			    )
			)
		formatString: 0
		lineageTag: 106265b9-76a8-4df5-b5b7-837f485bf672

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 5b0a9731-a116-4ae5-945d-6f5d7589ddf9
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	column SelectorSort
		dataType: int64
		formatString: 0
		lineageTag: 16ff4de2-4345-402c-b617-2634cd92ef03
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: [SelectorSort]

		annotation SummarizationSetBy = Automatic

	column Selector =
			
			IF (
			    'Top N Selector'[SelectorSort] = 0,
			    "All",
			    "Top "
			        & FORMAT (
			            'Top N Selector'[SelectorSort],
			            ""
			        )
			)
		dataType: string
		lineageTag: 2b3d856a-3959-42a0-8b5e-1f8812b346bd
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition 'Top N Selector-715fc1fb-eb7f-4a3d-8804-03d220962517' = calculated
		mode: import
		source =
				
				ADDCOLUMNS (
				    GENERATESERIES (
				        1,
				        25,
				        1
				    ),
				    "SelectorSort",
				        SWITCH (
				            TRUE (),
				            [Value] <= 5, 5,
				            [Value] <= 10, 10,
				            [Value] <= 15, 15,
				            [Value] <= 20, 20,
				            [Value] <= 25, 25,
				            [Value]
				        )
				)

	annotation PBI_Id = 72af1c9b44cb491a98170c13173596de

